// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: cB98qoa8i3odyeQmSRqxXv
// Component: vei3rpQpAq
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_mc_usa.module.css"; // plasmic-import: cB98qoa8i3odyeQmSRqxXv/projectcss
import * as sty from "./PlasmicMinusTablet.module.css"; // plasmic-import: vei3rpQpAq/css
import MinusIcon from "./icons/PlasmicIcon__Minus"; // plasmic-import: O-vtwbpHS7L/icon

export const PlasmicMinusTablet__VariantProps = new Array();

export const PlasmicMinusTablet__ArgProps = new Array();

function PlasmicMinusTablet__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <MinusIcon
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
      role={"img"}
    />
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicMinusTablet__ArgProps,
      internalVariantPropNames: PlasmicMinusTablet__VariantProps
    });

    return PlasmicMinusTablet__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMinusTablet";
  } else {
    func.displayName = `PlasmicMinusTablet.${nodeName}`;
  }
  return func;
}

export const PlasmicMinusTablet = Object.assign(
  // Top-level PlasmicMinusTablet renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicMinusTablet
    internalVariantProps: PlasmicMinusTablet__VariantProps,
    internalArgProps: PlasmicMinusTablet__ArgProps
  }
);

export default PlasmicMinusTablet;
/* prettier-ignore-end */
