// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: cB98qoa8i3odyeQmSRqxXv
// Component: WRsiZiFPv5J
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import CheckTablet from "../../CheckTablet"; // plasmic-import: EmIE1wl7mq/component
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_mc_usa.module.css"; // plasmic-import: cB98qoa8i3odyeQmSRqxXv/projectcss
import * as sty from "./PlasmicBasic.module.css"; // plasmic-import: WRsiZiFPv5J/css

export const PlasmicBasic__VariantProps = new Array();

export const PlasmicBasic__ArgProps = new Array();

function PlasmicBasic__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div
        data-plasmic-name={"software2"}
        data-plasmic-override={overrides.software2}
        className={classNames(defaultcss.all, sty.software2)}
      >
        <div
          data-plasmic-name={"pricingPagesRowHeader11"}
          data-plasmic-override={overrides.pricingPagesRowHeader11}
          className={classNames(defaultcss.all, sty.pricingPagesRowHeader11)}
        >
          <div
            data-plasmic-name={"topBorder51"}
            data-plasmic-override={overrides.topBorder51}
            className={classNames(defaultcss.all, sty.topBorder51)}
          />
        </div>

        <div
          data-plasmic-name={"pricingPagesCell41"}
          data-plasmic-override={overrides.pricingPagesCell41}
          className={classNames(defaultcss.all, sty.pricingPagesCell41)}
        >
          <div
            data-plasmic-name={"topBorder52"}
            data-plasmic-override={overrides.topBorder52}
            className={classNames(defaultcss.all, sty.topBorder52)}
          />

          <CheckTablet
            className={classNames("__wab_instance", sty.checkTablet__bfv81)}
          />
        </div>

        <div
          data-plasmic-name={"pricingPagesCell42"}
          data-plasmic-override={overrides.pricingPagesCell42}
          className={classNames(defaultcss.all, sty.pricingPagesCell42)}
        >
          <div
            data-plasmic-name={"topBorder53"}
            data-plasmic-override={overrides.topBorder53}
            className={classNames(defaultcss.all, sty.topBorder53)}
          />

          <CheckTablet
            className={classNames("__wab_instance", sty.checkTablet__deBrz)}
          />
        </div>

        <div
          data-plasmic-name={"pricingPagesCell43"}
          data-plasmic-override={overrides.pricingPagesCell43}
          className={classNames(defaultcss.all, sty.pricingPagesCell43)}
        >
          <div
            data-plasmic-name={"topBorder54"}
            data-plasmic-override={overrides.topBorder54}
            className={classNames(defaultcss.all, sty.topBorder54)}
          />

          <CheckTablet
            className={classNames("__wab_instance", sty.checkTablet__fq9Io)}
          />
        </div>

        <div
          data-plasmic-name={"pricingPagesCell44"}
          data-plasmic-override={overrides.pricingPagesCell44}
          className={classNames(defaultcss.all, sty.pricingPagesCell44)}
        >
          <div
            data-plasmic-name={"topBorder55"}
            data-plasmic-override={overrides.topBorder55}
            className={classNames(defaultcss.all, sty.topBorder55)}
          />

          <CheckTablet
            className={classNames("__wab_instance", sty.checkTablet__hKTkD)}
          />
        </div>
      </div>

      <div
        data-plasmic-name={"hardware4"}
        data-plasmic-override={overrides.hardware4}
        className={classNames(defaultcss.all, sty.hardware4)}
      >
        <div
          data-plasmic-name={"pricingPagesRowHeader8"}
          data-plasmic-override={overrides.pricingPagesRowHeader8}
          className={classNames(defaultcss.all, sty.pricingPagesRowHeader8)}
        >
          <div
            data-plasmic-name={"topBorder36"}
            data-plasmic-override={overrides.topBorder36}
            className={classNames(defaultcss.all, sty.topBorder36)}
          />
        </div>

        <div
          data-plasmic-name={"pricingPagesCell29"}
          data-plasmic-override={overrides.pricingPagesCell29}
          className={classNames(defaultcss.all, sty.pricingPagesCell29)}
        >
          <div
            data-plasmic-name={"topBorder37"}
            data-plasmic-override={overrides.topBorder37}
            className={classNames(defaultcss.all, sty.topBorder37)}
          />

          <CheckTablet
            className={classNames("__wab_instance", sty.checkTablet__cxXwO)}
          />
        </div>

        <div
          data-plasmic-name={"pricingPagesCell30"}
          data-plasmic-override={overrides.pricingPagesCell30}
          className={classNames(defaultcss.all, sty.pricingPagesCell30)}
        >
          <div
            data-plasmic-name={"topBorder38"}
            data-plasmic-override={overrides.topBorder38}
            className={classNames(defaultcss.all, sty.topBorder38)}
          />

          <CheckTablet
            className={classNames("__wab_instance", sty.checkTablet__ufheH)}
          />
        </div>

        <div
          data-plasmic-name={"pricingPagesCell31"}
          data-plasmic-override={overrides.pricingPagesCell31}
          className={classNames(defaultcss.all, sty.pricingPagesCell31)}
        >
          <div
            data-plasmic-name={"topBorder39"}
            data-plasmic-override={overrides.topBorder39}
            className={classNames(defaultcss.all, sty.topBorder39)}
          />

          <CheckTablet
            className={classNames("__wab_instance", sty.checkTablet___7408Y)}
          />
        </div>

        <div
          data-plasmic-name={"pricingPagesCell32"}
          data-plasmic-override={overrides.pricingPagesCell32}
          className={classNames(defaultcss.all, sty.pricingPagesCell32)}
        >
          <div
            data-plasmic-name={"topBorder40"}
            data-plasmic-override={overrides.topBorder40}
            className={classNames(defaultcss.all, sty.topBorder40)}
          />

          <CheckTablet
            className={classNames("__wab_instance", sty.checkTablet__j7Y6H)}
          />
        </div>
      </div>

      <div
        data-plasmic-name={"support4"}
        data-plasmic-override={overrides.support4}
        className={classNames(defaultcss.all, sty.support4)}
      >
        <div
          data-plasmic-name={"section3"}
          data-plasmic-override={overrides.section3}
          className={classNames(defaultcss.all, sty.section3)}
        >
          <div
            data-plasmic-name={"pricingPagesRowHeader3"}
            data-plasmic-override={overrides.pricingPagesRowHeader3}
            className={classNames(defaultcss.all, sty.pricingPagesRowHeader3)}
          >
            <div
              data-plasmic-name={"topBorder11"}
              data-plasmic-override={overrides.topBorder11}
              className={classNames(defaultcss.all, sty.topBorder11)}
            />
          </div>

          <div
            data-plasmic-name={"pricingPagesCell9"}
            data-plasmic-override={overrides.pricingPagesCell9}
            className={classNames(defaultcss.all, sty.pricingPagesCell9)}
          >
            <div
              data-plasmic-name={"topBorder12"}
              data-plasmic-override={overrides.topBorder12}
              className={classNames(defaultcss.all, sty.topBorder12)}
            />

            <CheckTablet
              className={classNames("__wab_instance", sty.checkTablet__wv7F0)}
            />
          </div>

          <div
            data-plasmic-name={"pricingPagesCell10"}
            data-plasmic-override={overrides.pricingPagesCell10}
            className={classNames(defaultcss.all, sty.pricingPagesCell10)}
          >
            <div
              data-plasmic-name={"topBorder13"}
              data-plasmic-override={overrides.topBorder13}
              className={classNames(defaultcss.all, sty.topBorder13)}
            />

            <CheckTablet
              className={classNames("__wab_instance", sty.checkTablet__qjda4)}
            />
          </div>

          <div
            data-plasmic-name={"pricingPagesCell11"}
            data-plasmic-override={overrides.pricingPagesCell11}
            className={classNames(defaultcss.all, sty.pricingPagesCell11)}
          >
            <div
              data-plasmic-name={"topBorder14"}
              data-plasmic-override={overrides.topBorder14}
              className={classNames(defaultcss.all, sty.topBorder14)}
            />

            <CheckTablet
              className={classNames("__wab_instance", sty.checkTablet__zJvPu)}
            />
          </div>

          <div
            data-plasmic-name={"pricingPagesCell12"}
            data-plasmic-override={overrides.pricingPagesCell12}
            className={classNames(defaultcss.all, sty.pricingPagesCell12)}
          >
            <div
              data-plasmic-name={"topBorder15"}
              data-plasmic-override={overrides.topBorder15}
              className={classNames(defaultcss.all, sty.topBorder15)}
            />

            <CheckTablet
              className={classNames("__wab_instance", sty.checkTablet__lTGza)}
            />
          </div>
        </div>

        <div
          data-plasmic-name={"cta3"}
          data-plasmic-override={overrides.cta3}
          className={classNames(defaultcss.all, sty.cta3)}
        >
          <div
            data-plasmic-name={"divider3"}
            data-plasmic-override={overrides.divider3}
            className={classNames(defaultcss.all, sty.divider3)}
          />

          <div
            data-plasmic-name={"content23"}
            data-plasmic-override={overrides.content23}
            className={classNames(defaultcss.all, sty.content23)}
          >
            <div
              data-plasmic-name={"pricingPagesButtonLink2"}
              data-plasmic-override={overrides.pricingPagesButtonLink2}
              className={classNames(
                defaultcss.all,
                sty.pricingPagesButtonLink2
              )}
            >
              <div
                data-plasmic-name={"text17"}
                data-plasmic-override={overrides.text17}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text17
                )}
              >
                {"Buy Basic"}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "software2",
    "pricingPagesRowHeader11",
    "topBorder51",
    "pricingPagesCell41",
    "topBorder52",
    "pricingPagesCell42",
    "topBorder53",
    "pricingPagesCell43",
    "topBorder54",
    "pricingPagesCell44",
    "topBorder55",
    "hardware4",
    "pricingPagesRowHeader8",
    "topBorder36",
    "pricingPagesCell29",
    "topBorder37",
    "pricingPagesCell30",
    "topBorder38",
    "pricingPagesCell31",
    "topBorder39",
    "pricingPagesCell32",
    "topBorder40",
    "support4",
    "section3",
    "pricingPagesRowHeader3",
    "topBorder11",
    "pricingPagesCell9",
    "topBorder12",
    "pricingPagesCell10",
    "topBorder13",
    "pricingPagesCell11",
    "topBorder14",
    "pricingPagesCell12",
    "topBorder15",
    "cta3",
    "divider3",
    "content23",
    "pricingPagesButtonLink2",
    "text17"
  ],

  software2: [
    "software2",
    "pricingPagesRowHeader11",
    "topBorder51",
    "pricingPagesCell41",
    "topBorder52",
    "pricingPagesCell42",
    "topBorder53",
    "pricingPagesCell43",
    "topBorder54",
    "pricingPagesCell44",
    "topBorder55"
  ],

  pricingPagesRowHeader11: ["pricingPagesRowHeader11", "topBorder51"],
  topBorder51: ["topBorder51"],
  pricingPagesCell41: ["pricingPagesCell41", "topBorder52"],
  topBorder52: ["topBorder52"],
  pricingPagesCell42: ["pricingPagesCell42", "topBorder53"],
  topBorder53: ["topBorder53"],
  pricingPagesCell43: ["pricingPagesCell43", "topBorder54"],
  topBorder54: ["topBorder54"],
  pricingPagesCell44: ["pricingPagesCell44", "topBorder55"],
  topBorder55: ["topBorder55"],
  hardware4: [
    "hardware4",
    "pricingPagesRowHeader8",
    "topBorder36",
    "pricingPagesCell29",
    "topBorder37",
    "pricingPagesCell30",
    "topBorder38",
    "pricingPagesCell31",
    "topBorder39",
    "pricingPagesCell32",
    "topBorder40"
  ],

  pricingPagesRowHeader8: ["pricingPagesRowHeader8", "topBorder36"],
  topBorder36: ["topBorder36"],
  pricingPagesCell29: ["pricingPagesCell29", "topBorder37"],
  topBorder37: ["topBorder37"],
  pricingPagesCell30: ["pricingPagesCell30", "topBorder38"],
  topBorder38: ["topBorder38"],
  pricingPagesCell31: ["pricingPagesCell31", "topBorder39"],
  topBorder39: ["topBorder39"],
  pricingPagesCell32: ["pricingPagesCell32", "topBorder40"],
  topBorder40: ["topBorder40"],
  support4: [
    "support4",
    "section3",
    "pricingPagesRowHeader3",
    "topBorder11",
    "pricingPagesCell9",
    "topBorder12",
    "pricingPagesCell10",
    "topBorder13",
    "pricingPagesCell11",
    "topBorder14",
    "pricingPagesCell12",
    "topBorder15",
    "cta3",
    "divider3",
    "content23",
    "pricingPagesButtonLink2",
    "text17"
  ],

  section3: [
    "section3",
    "pricingPagesRowHeader3",
    "topBorder11",
    "pricingPagesCell9",
    "topBorder12",
    "pricingPagesCell10",
    "topBorder13",
    "pricingPagesCell11",
    "topBorder14",
    "pricingPagesCell12",
    "topBorder15"
  ],

  pricingPagesRowHeader3: ["pricingPagesRowHeader3", "topBorder11"],
  topBorder11: ["topBorder11"],
  pricingPagesCell9: ["pricingPagesCell9", "topBorder12"],
  topBorder12: ["topBorder12"],
  pricingPagesCell10: ["pricingPagesCell10", "topBorder13"],
  topBorder13: ["topBorder13"],
  pricingPagesCell11: ["pricingPagesCell11", "topBorder14"],
  topBorder14: ["topBorder14"],
  pricingPagesCell12: ["pricingPagesCell12", "topBorder15"],
  topBorder15: ["topBorder15"],
  cta3: ["cta3", "divider3", "content23", "pricingPagesButtonLink2", "text17"],
  divider3: ["divider3"],
  content23: ["content23", "pricingPagesButtonLink2", "text17"],
  pricingPagesButtonLink2: ["pricingPagesButtonLink2", "text17"],
  text17: ["text17"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicBasic__ArgProps,
      internalVariantPropNames: PlasmicBasic__VariantProps
    });

    return PlasmicBasic__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBasic";
  } else {
    func.displayName = `PlasmicBasic.${nodeName}`;
  }
  return func;
}

export const PlasmicBasic = Object.assign(
  // Top-level PlasmicBasic renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    software2: makeNodeComponent("software2"),
    pricingPagesRowHeader11: makeNodeComponent("pricingPagesRowHeader11"),
    topBorder51: makeNodeComponent("topBorder51"),
    pricingPagesCell41: makeNodeComponent("pricingPagesCell41"),
    topBorder52: makeNodeComponent("topBorder52"),
    pricingPagesCell42: makeNodeComponent("pricingPagesCell42"),
    topBorder53: makeNodeComponent("topBorder53"),
    pricingPagesCell43: makeNodeComponent("pricingPagesCell43"),
    topBorder54: makeNodeComponent("topBorder54"),
    pricingPagesCell44: makeNodeComponent("pricingPagesCell44"),
    topBorder55: makeNodeComponent("topBorder55"),
    hardware4: makeNodeComponent("hardware4"),
    pricingPagesRowHeader8: makeNodeComponent("pricingPagesRowHeader8"),
    topBorder36: makeNodeComponent("topBorder36"),
    pricingPagesCell29: makeNodeComponent("pricingPagesCell29"),
    topBorder37: makeNodeComponent("topBorder37"),
    pricingPagesCell30: makeNodeComponent("pricingPagesCell30"),
    topBorder38: makeNodeComponent("topBorder38"),
    pricingPagesCell31: makeNodeComponent("pricingPagesCell31"),
    topBorder39: makeNodeComponent("topBorder39"),
    pricingPagesCell32: makeNodeComponent("pricingPagesCell32"),
    topBorder40: makeNodeComponent("topBorder40"),
    support4: makeNodeComponent("support4"),
    section3: makeNodeComponent("section3"),
    pricingPagesRowHeader3: makeNodeComponent("pricingPagesRowHeader3"),
    topBorder11: makeNodeComponent("topBorder11"),
    pricingPagesCell9: makeNodeComponent("pricingPagesCell9"),
    topBorder12: makeNodeComponent("topBorder12"),
    pricingPagesCell10: makeNodeComponent("pricingPagesCell10"),
    topBorder13: makeNodeComponent("topBorder13"),
    pricingPagesCell11: makeNodeComponent("pricingPagesCell11"),
    topBorder14: makeNodeComponent("topBorder14"),
    pricingPagesCell12: makeNodeComponent("pricingPagesCell12"),
    topBorder15: makeNodeComponent("topBorder15"),
    cta3: makeNodeComponent("cta3"),
    divider3: makeNodeComponent("divider3"),
    content23: makeNodeComponent("content23"),
    pricingPagesButtonLink2: makeNodeComponent("pricingPagesButtonLink2"),
    text17: makeNodeComponent("text17"),
    // Metadata about props expected for PlasmicBasic
    internalVariantProps: PlasmicBasic__VariantProps,
    internalArgProps: PlasmicBasic__ArgProps
  }
);

export default PlasmicBasic;
/* prettier-ignore-end */
