// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: cB98qoa8i3odyeQmSRqxXv
// Component: EmIE1wl7mq
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_mc_usa.module.css"; // plasmic-import: cB98qoa8i3odyeQmSRqxXv/projectcss
import * as sty from "./PlasmicCheckTablet.module.css"; // plasmic-import: EmIE1wl7mq/css
import CheckIcon from "./icons/PlasmicIcon__Check"; // plasmic-import: aL7LNK6o7h3/icon

export const PlasmicCheckTablet__VariantProps = new Array();

export const PlasmicCheckTablet__ArgProps = new Array();

function PlasmicCheckTablet__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <CheckIcon
        data-plasmic-name={"svg"}
        data-plasmic-override={overrides.svg}
        className={classNames(defaultcss.all, sty.svg)}
        role={"img"}
      />
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "svg"],
  svg: ["svg"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicCheckTablet__ArgProps,
      internalVariantPropNames: PlasmicCheckTablet__VariantProps
    });

    return PlasmicCheckTablet__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCheckTablet";
  } else {
    func.displayName = `PlasmicCheckTablet.${nodeName}`;
  }
  return func;
}

export const PlasmicCheckTablet = Object.assign(
  // Top-level PlasmicCheckTablet renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent("svg"),
    // Metadata about props expected for PlasmicCheckTablet
    internalVariantProps: PlasmicCheckTablet__VariantProps,
    internalArgProps: PlasmicCheckTablet__ArgProps
  }
);

export default PlasmicCheckTablet;
/* prettier-ignore-end */
