// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: cB98qoa8i3odyeQmSRqxXv
// Component: OC6BaJS9BD
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_mc_usa.module.css"; // plasmic-import: cB98qoa8i3odyeQmSRqxXv/projectcss
import * as sty from "./PlasmicCheck.module.css"; // plasmic-import: OC6BaJS9BD/css
import CheckIcon from "./icons/PlasmicIcon__Check"; // plasmic-import: aL7LNK6o7h3/icon

export const PlasmicCheck__VariantProps = new Array();

export const PlasmicCheck__ArgProps = new Array();

function PlasmicCheck__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <CheckIcon
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
      role={"img"}
    />
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicCheck__ArgProps,
      internalVariantPropNames: PlasmicCheck__VariantProps
    });

    return PlasmicCheck__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCheck";
  } else {
    func.displayName = `PlasmicCheck.${nodeName}`;
  }
  return func;
}

export const PlasmicCheck = Object.assign(
  // Top-level PlasmicCheck renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicCheck
    internalVariantProps: PlasmicCheck__VariantProps,
    internalArgProps: PlasmicCheck__ArgProps
  }
);

export default PlasmicCheck;
/* prettier-ignore-end */
