
    // @ts-nocheck
    /* eslint-disable */
    /* tslint:disable */
    /* prettier-ignore-start */
    /** @jsxRuntime classic */
    /** @jsx createPlasmicElementProxy */
    /** @jsxFrag React.Fragment */
    // This class is auto-generated by Plasmic; please do not edit!
    // Plasmic Project: cB98qoa8i3odyeQmSRqxXv
    // Component: vajCZel_JAG
    // plasmic-unformatted
    import * as React from "react";
    
    import * as p from  "@plasmicapp/react-web";
    import {hasVariant, classNames, wrapWithClassName, createPlasmicElementProxy, makeFragment, MultiChoiceArg, SingleBooleanChoiceArg, SingleChoiceArg, pick, omit, useTrigger, StrictProps, deriveRenderOpts, ensureGlobalVariants} from "@plasmicapp/react-web";
    
    
    
    import "@plasmicapp/react-web/lib/plasmic.css";
    import  "./plasmic__default_style.css"; // plasmic-import: global/defaultcss
    import  "./plasmic_final_not_exported.css"; // plasmic-import: cB98qoa8i3odyeQmSRqxXv/projectcss
    import  "./PlasmicFeatures.css" // plasmic-import: vajCZel_JAG/css
  
    import GlobeAltIcon from "./PlasmicIcon__GlobeAlt";  // plasmic-import: cotA1AFhJEB/icon
import ScaleIcon from "./PlasmicIcon__Scale";  // plasmic-import: levw2wPNh7_/icon
import LightningBoltIcon from "./PlasmicIcon__LightningBolt";  // plasmic-import: esLao0IVyYj/icon
import AnnotationIcon from "./PlasmicIcon__Annotation";  // plasmic-import: kbpRokNj1MS/icon
import MailIcon from "./PlasmicIcon__Mail";  // plasmic-import: CB8289oITqR/icon
    

    
    export type PlasmicFeatures__VariantMembers = {
      
    };
    export type PlasmicFeatures__VariantsArgs = {};
    type VariantPropType = keyof PlasmicFeatures__VariantsArgs;
    export const PlasmicFeatures__VariantProps = new Array<VariantPropType>();
  

    
    export type PlasmicFeatures__ArgsType = {};
    type ArgPropType = keyof PlasmicFeatures__ArgsType;
    export const PlasmicFeatures__ArgProps = new Array<ArgPropType>();
  

    export type PlasmicFeatures__OverridesType = {
    frame2Features?: p.Flex<"div">;
features?: p.Flex<"div">;
alternativeSideBySideWithImagesDesktop?: p.Flex<"div">;
container3?: p.Flex<"div">;
retireOutdatedElectronics?: p.Flex<"div">;
supportingText2?: p.Flex<"div">;
solveUniqueProblems?: p.Flex<"div">;
leadingContent2?: p.Flex<"div">;
header2?: p.Flex<"div">;
supportingText3?: p.Flex<"div">;
features2?: p.Flex<"div">;
featureSectionsFeature?: p.Flex<"div">;
brandIcon?: p.Flex<"div">;
content3?: p.Flex<"div">;
description?: p.Flex<"div">;
featureSectionsFeature2?: p.Flex<"div">;
brandIcon2?: p.Flex<"div">;
content4?: p.Flex<"div">;
title?: p.Flex<"div">;
description2?: p.Flex<"div">;
featureSectionsFeature3?: p.Flex<"div">;
brandIcon3?: p.Flex<"div">;
content5?: p.Flex<"div">;
title2?: p.Flex<"div">;
description3?: p.Flex<"div">;
image?: p.Flex<"div">;
sharedDotPattern?: p.Flex<"div">;
grid?: p.Flex<"div">;
column?: p.Flex<"div">;
pattern?: p.Flex<"div">;
pattern2?: p.Flex<"div">;
pattern3?: p.Flex<"div">;
column2?: p.Flex<"div">;
pattern4?: p.Flex<"div">;
pattern5?: p.Flex<"div">;
pattern6?: p.Flex<"div">;
column3?: p.Flex<"div">;
pattern7?: p.Flex<"div">;
pattern8?: p.Flex<"div">;
pattern9?: p.Flex<"div">;
featureExample?: p.Flex<"div">;
alwaysInTheLoop?: p.Flex<"div">;
image2?: p.Flex<"div">;
sharedDotPattern2?: p.Flex<"div">;
grid2?: p.Flex<"div">;
column4?: p.Flex<"div">;
pattern92?: p.Flex<"div">;
pattern82?: p.Flex<"div">;
pattern72?: p.Flex<"div">;
column5?: p.Flex<"div">;
pattern62?: p.Flex<"div">;
pattern52?: p.Flex<"div">;
pattern42?: p.Flex<"div">;
column6?: p.Flex<"div">;
pattern32?: p.Flex<"div">;
pattern22?: p.Flex<"div">;
pattern1?: p.Flex<"div">;
featureExample2?: p.Flex<"div">;
leadingContent3?: p.Flex<"div">;
header3?: p.Flex<"div">;
supportingText4?: p.Flex<"div">;
features3?: p.Flex<"div">;
featureSectionsFeature4?: p.Flex<"div">;
brandIcon4?: p.Flex<"div">;
content6?: p.Flex<"div">;
title3?: p.Flex<"div">;
description4?: p.Flex<"div">;
featureSectionsFeature5?: p.Flex<"div">;
brandIcon5?: p.Flex<"div">;
content7?: p.Flex<"div">;
title4?: p.Flex<"div">;
description5?: p.Flex<"div">;
  };

    
    export interface DefaultFeaturesProps {
      
      className?: string;
    }
  

    
    function PlasmicFeatures__RenderFunc(
      props: {
        variants: PlasmicFeatures__VariantsArgs,
        args: PlasmicFeatures__ArgsType
        overrides: PlasmicFeatures__OverridesType
        forNode?: string
      }
    ) {
      const {variants, args, overrides, forNode} = props;

      
      
      return (
        
  <div
    
    data-plasmic-name={"frame2Features"}
    data-plasmic-override={overrides.frame2Features}
    data-plasmic-root={true}
    data-plasmic-for-node={forNode}
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "root_reset_cB98qoa8i3odyeQmSRqxXv", "Features__frame2Features__gnQ19")}
    
    >
          
  <div
    
    data-plasmic-name={"features"}
    data-plasmic-override={overrides.features}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__features__zLrrB")}
    
    >
          
  <div
    
    data-plasmic-name={"alternativeSideBySideWithImagesDesktop"}
    data-plasmic-override={overrides.alternativeSideBySideWithImagesDesktop}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__alternativeSideBySideWithImagesDesktop__ztP9I")}
    
    >
          
  <p.Stack
    as={"div"}
    data-plasmic-name={"container3"}
    data-plasmic-override={overrides.container3}
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__container3__r04OL")}
    
    >
          
  <p.Stack
    as={"div"}
    data-plasmic-name={"retireOutdatedElectronics"}
    data-plasmic-override={overrides.retireOutdatedElectronics}
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__retireOutdatedElectronics__vBj0")}
    
    >
          
  <div
    
    
    
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "Features__box__hgJ0T")}
    
    >
          { "Retire outdated electronics and electricals" }
        </div>
  

  <div
    
    data-plasmic-name={"supportingText2"}
    data-plasmic-override={overrides.supportingText2}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "Features__supportingText2__tGmhz")}
    
    >
          { "Explore our range of digital and harware solutions. Save time, increase transparency and become a more sustainable organization." }
        </div>
  
        </p.Stack>
  

  <p.Stack
    as={"div"}
    data-plasmic-name={"solveUniqueProblems"}
    data-plasmic-override={overrides.solveUniqueProblems}
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__solveUniqueProblems___1L5Ou")}
    
    >
          
  <p.Stack
    as={"div"}
    data-plasmic-name={"leadingContent2"}
    data-plasmic-override={overrides.leadingContent2}
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__leadingContent2__y1Ohl")}
    
    >
          
  <p.Stack
    as={"div"}
    data-plasmic-name={"header2"}
    data-plasmic-override={overrides.header2}
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__header2__qd9Kt")}
    
    >
          
  <div
    
    
    
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "Features__box__mrmo")}
    
    >
          { "Solve unique problems" }
        </div>
  

  <div
    
    data-plasmic-name={"supportingText3"}
    data-plasmic-override={overrides.supportingText3}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "Features__supportingText3__x0Uju")}
    
    >
          { "Electronic waste contains potentially recyclable materials that could be used to power the next cutting edge electronic devices.  If treated improperly, toxins such as mercury, cadmium, chromium, and ozone-depleting chlorofluorocarbons can pollute the planet." }
        </div>
  
        </p.Stack>
  

  <p.Stack
    as={"div"}
    data-plasmic-name={"features2"}
    data-plasmic-override={overrides.features2}
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__features2___9VmfY")}
    
    >
          
  <p.Stack
    as={"div"}
    data-plasmic-name={"featureSectionsFeature"}
    data-plasmic-override={overrides.featureSectionsFeature}
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__featureSectionsFeature__lXsna")}
    
    >
          
  <div
    
    data-plasmic-name={"brandIcon"}
    data-plasmic-override={overrides.brandIcon}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__brandIcon__xPe9")}
    
    >
          
  <GlobeAltIcon
    
    
    
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__svg", "Features__svg__nqShf")}
role={"img"}
    
    />
  
        </div>
  

  <p.Stack
    as={"div"}
    data-plasmic-name={"content3"}
    data-plasmic-override={overrides.content3}
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__content3__jxRP")}
    
    >
          
  <div
    
    
    
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "Features__box__cH24B")}
    
    >
          { "Transparency" }
        </div>
  

  <div
    
    data-plasmic-name={"description"}
    data-plasmic-override={overrides.description}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "Features__description__yyVo8")}
    
    >
          { "Your data tells a story about how your electronic waste is handled. Our data scientists can work with your company to uncover insights into how your electronics are handled." }
        </div>
  
        </p.Stack>
  
        </p.Stack>
  

  <p.Stack
    as={"div"}
    data-plasmic-name={"featureSectionsFeature2"}
    data-plasmic-override={overrides.featureSectionsFeature2}
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__featureSectionsFeature2__kF8Il")}
    
    >
          
  <div
    
    data-plasmic-name={"brandIcon2"}
    data-plasmic-override={overrides.brandIcon2}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__brandIcon2___2JJqj")}
    
    >
          
  <ScaleIcon
    
    
    
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__svg", "Features__svg__g4DRm")}
role={"img"}
    
    />
  
        </div>
  

  <p.Stack
    as={"div"}
    data-plasmic-name={"content4"}
    data-plasmic-override={overrides.content4}
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__content4__eioYc")}
    
    >
          
  <div
    
    data-plasmic-name={"title"}
    data-plasmic-override={overrides.title}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "Features__title__iPltX")}
    
    >
          { "Reputation risk" }
        </div>
  

  <div
    
    data-plasmic-name={"description2"}
    data-plasmic-override={overrides.description2}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "Features__description2___3QdGc")}
    
    >
          { "Fines for the improper disposal of electronic waste can cost your organization millions. With our digital and hardware tech solutions, you can protect your company’s hard earned green credentials." }
        </div>
  
        </p.Stack>
  
        </p.Stack>
  

  <p.Stack
    as={"div"}
    data-plasmic-name={"featureSectionsFeature3"}
    data-plasmic-override={overrides.featureSectionsFeature3}
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__featureSectionsFeature3__inpni")}
    
    >
          
  <div
    
    data-plasmic-name={"brandIcon3"}
    data-plasmic-override={overrides.brandIcon3}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__brandIcon3___1Z8ZO")}
    
    >
          
  <LightningBoltIcon
    
    
    
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__svg", "Features__svg__f8MXm")}
role={"img"}
    
    />
  
        </div>
  

  <p.Stack
    as={"div"}
    data-plasmic-name={"content5"}
    data-plasmic-override={overrides.content5}
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__content5___4Ozbo")}
    
    >
          
  <div
    
    data-plasmic-name={"title2"}
    data-plasmic-override={overrides.title2}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "Features__title2__vDppB")}
    
    >
          { "Sustainability goals" }
        </div>
  

  <div
    
    data-plasmic-name={"description3"}
    data-plasmic-override={overrides.description3}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "Features__description3__njcT")}
    
    >
          { "Climate change will impact your ability to operate in drastic ways in the future. Electronic waste programs can count towards your efforts to minimize the repercussions from a warming planet." }
        </div>
  
        </p.Stack>
  
        </p.Stack>
  
        </p.Stack>
  
        </p.Stack>
  

  <div
    
    data-plasmic-name={"image"}
    data-plasmic-override={overrides.image}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__image__lv3Qr")}
    
    >
          
  <div
    
    data-plasmic-name={"sharedDotPattern"}
    data-plasmic-override={overrides.sharedDotPattern}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__sharedDotPattern__g8Dlg")}
    
    >
          
  <p.Stack
    as={"div"}
    data-plasmic-name={"grid"}
    data-plasmic-override={overrides.grid}
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__grid__e9OGp")}
    
    >
          
  <p.Stack
    as={"div"}
    data-plasmic-name={"column"}
    data-plasmic-override={overrides.column}
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__column__mMiBg")}
    
    >
          
  <div
    
    data-plasmic-name={"pattern"}
    data-plasmic-override={overrides.pattern}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__pattern__cg6")}
    
    />
  

  <div
    
    data-plasmic-name={"pattern2"}
    data-plasmic-override={overrides.pattern2}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__pattern2__qae2Y")}
    
    />
  

  <div
    
    data-plasmic-name={"pattern3"}
    data-plasmic-override={overrides.pattern3}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__pattern3__xzGMt")}
    
    />
  
        </p.Stack>
  

  <p.Stack
    as={"div"}
    data-plasmic-name={"column2"}
    data-plasmic-override={overrides.column2}
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__column2__uxGeY")}
    
    >
          
  <div
    
    data-plasmic-name={"pattern4"}
    data-plasmic-override={overrides.pattern4}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__pattern4__s27Xm")}
    
    />
  

  <div
    
    data-plasmic-name={"pattern5"}
    data-plasmic-override={overrides.pattern5}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__pattern5__vHwkp")}
    
    />
  

  <div
    
    data-plasmic-name={"pattern6"}
    data-plasmic-override={overrides.pattern6}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__pattern6__qovm2")}
    
    />
  
        </p.Stack>
  

  <p.Stack
    as={"div"}
    data-plasmic-name={"column3"}
    data-plasmic-override={overrides.column3}
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__column3__huzr")}
    
    >
          
  <div
    
    data-plasmic-name={"pattern7"}
    data-plasmic-override={overrides.pattern7}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__pattern7__w90Qd")}
    
    />
  

  <div
    
    data-plasmic-name={"pattern8"}
    data-plasmic-override={overrides.pattern8}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__pattern8__hiUjC")}
    
    />
  

  <div
    
    data-plasmic-name={"pattern9"}
    data-plasmic-override={overrides.pattern9}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__pattern9___9UqQt")}
    
    />
  
        </p.Stack>
  
        </p.Stack>
  
        </div>
  
{ (false) ? (
  <div
    
    data-plasmic-name={"featureExample"}
    data-plasmic-override={overrides.featureExample}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__featureExample__d0Ia")}
    
    />
  ) : null }
        </div>
  
        </p.Stack>
  

  <p.Stack
    as={"div"}
    data-plasmic-name={"alwaysInTheLoop"}
    data-plasmic-override={overrides.alwaysInTheLoop}
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__alwaysInTheLoop___7FFvr")}
    
    >
          
  <div
    
    data-plasmic-name={"image2"}
    data-plasmic-override={overrides.image2}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__image2___7Plyv")}
    
    >
          
  <div
    
    data-plasmic-name={"sharedDotPattern2"}
    data-plasmic-override={overrides.sharedDotPattern2}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__sharedDotPattern2__jJeom")}
    
    >
          
  <p.Stack
    as={"div"}
    data-plasmic-name={"grid2"}
    data-plasmic-override={overrides.grid2}
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__grid2__bvu9O")}
    
    >
          
  <p.Stack
    as={"div"}
    data-plasmic-name={"column4"}
    data-plasmic-override={overrides.column4}
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__column4___4EoH")}
    
    >
          
  <div
    
    data-plasmic-name={"pattern92"}
    data-plasmic-override={overrides.pattern92}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__pattern92__uYoj")}
    
    />
  

  <div
    
    data-plasmic-name={"pattern82"}
    data-plasmic-override={overrides.pattern82}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__pattern82__ogexp")}
    
    />
  

  <div
    
    data-plasmic-name={"pattern72"}
    data-plasmic-override={overrides.pattern72}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__pattern72__p8PPi")}
    
    />
  
        </p.Stack>
  

  <p.Stack
    as={"div"}
    data-plasmic-name={"column5"}
    data-plasmic-override={overrides.column5}
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__column5___4OJlb")}
    
    >
          
  <div
    
    data-plasmic-name={"pattern62"}
    data-plasmic-override={overrides.pattern62}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__pattern62__zMuL4")}
    
    />
  

  <div
    
    data-plasmic-name={"pattern52"}
    data-plasmic-override={overrides.pattern52}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__pattern52__ll4Js")}
    
    />
  

  <div
    
    data-plasmic-name={"pattern42"}
    data-plasmic-override={overrides.pattern42}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__pattern42__c1SsX")}
    
    />
  
        </p.Stack>
  

  <p.Stack
    as={"div"}
    data-plasmic-name={"column6"}
    data-plasmic-override={overrides.column6}
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__column6__qdOBu")}
    
    >
          
  <div
    
    data-plasmic-name={"pattern32"}
    data-plasmic-override={overrides.pattern32}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__pattern32__puj1Y")}
    
    />
  

  <div
    
    data-plasmic-name={"pattern22"}
    data-plasmic-override={overrides.pattern22}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__pattern22__x7Zhx")}
    
    />
  

  <div
    
    data-plasmic-name={"pattern1"}
    data-plasmic-override={overrides.pattern1}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__pattern1__iGVpe")}
    
    />
  
        </p.Stack>
  
        </p.Stack>
  
        </div>
  
{ (false) ? (
  <div
    
    data-plasmic-name={"featureExample2"}
    data-plasmic-override={overrides.featureExample2}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__featureExample2__gBjI6")}
    
    />
  ) : null }
        </div>
  

  <p.Stack
    as={"div"}
    data-plasmic-name={"leadingContent3"}
    data-plasmic-override={overrides.leadingContent3}
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__leadingContent3__b8D4Q")}
    
    >
          
  <p.Stack
    as={"div"}
    data-plasmic-name={"header3"}
    data-plasmic-override={overrides.header3}
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__header3__ekwcN")}
    
    >
          
  <div
    
    
    
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "Features__box___3WX7Y")}
    
    >
          { "Always in the loop" }
        </div>
  

  <div
    
    data-plasmic-name={"supportingText4"}
    data-plasmic-override={overrides.supportingText4}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "Features__supportingText4__h7VCm")}
    
    >
          { "Clear answers to what we should do when a product’s software doesn’t outlive its hardware, or when its electronics don’t outlast their usefulness. " }
        </div>
  
        </p.Stack>
  

  <p.Stack
    as={"div"}
    data-plasmic-name={"features3"}
    data-plasmic-override={overrides.features3}
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__features3__n4B5F")}
    
    >
          
  <p.Stack
    as={"div"}
    data-plasmic-name={"featureSectionsFeature4"}
    data-plasmic-override={overrides.featureSectionsFeature4}
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__featureSectionsFeature4__bbCg")}
    
    >
          
  <div
    
    data-plasmic-name={"brandIcon4"}
    data-plasmic-override={overrides.brandIcon4}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__brandIcon4__vBsm3")}
    
    >
          
  <AnnotationIcon
    
    
    
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__svg", "Features__svg__iTdAg")}
role={"img"}
    
    />
  
        </div>
  

  <p.Stack
    as={"div"}
    data-plasmic-name={"content6"}
    data-plasmic-override={overrides.content6}
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__content6___48Ar")}
    
    >
          
  <div
    
    data-plasmic-name={"title3"}
    data-plasmic-override={overrides.title3}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "Features__title3__mFIn7")}
    
    >
          { "Wherever you happen to be" }
        </div>
  

  <div
    
    data-plasmic-name={"description4"}
    data-plasmic-override={overrides.description4}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "Features__description4__finqI")}
    
    >
          { "Call us today to discuss your needs." }
        </div>
  
        </p.Stack>
  
        </p.Stack>
  

  <p.Stack
    as={"div"}
    data-plasmic-name={"featureSectionsFeature5"}
    data-plasmic-override={overrides.featureSectionsFeature5}
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__featureSectionsFeature5__bnjXn")}
    
    >
          
  <div
    
    data-plasmic-name={"brandIcon5"}
    data-plasmic-override={overrides.brandIcon5}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__brandIcon5__jRjzq")}
    
    >
          
  <MailIcon
    
    
    
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__svg", "Features__svg___8Q8Iq")}
role={"img"}
    
    />
  
        </div>
  

  <p.Stack
    as={"div"}
    data-plasmic-name={"content7"}
    data-plasmic-override={overrides.content7}
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "Features__content7__hlrBd")}
    
    >
          
  <div
    
    data-plasmic-name={"title4"}
    data-plasmic-override={overrides.title4}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "Features__title4__er4I")}
    
    >
          { "Find a partner for the long term" }
        </div>
  

  <div
    
    data-plasmic-name={"description5"}
    data-plasmic-override={overrides.description5}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "Features__description5__tOnLt")}
    
    >
          { "We can help you with independent, unbiased advice and best practices that leverage cutting edge technologies." }
        </div>
  
        </p.Stack>
  
        </p.Stack>
  
        </p.Stack>
  
        </p.Stack>
  
        </p.Stack>
  
        </p.Stack>
  
        </div>
  
        </div>
  
        </div>
  
      ) as React.ReactElement | null;
    }

    
    const PlasmicDescendants = {
      frame2Features: ["frame2Features", "features", "alternativeSideBySideWithImagesDesktop", "container3", "retireOutdatedElectronics", "supportingText2", "solveUniqueProblems", "leadingContent2", "header2", "supportingText3", "features2", "featureSectionsFeature", "brandIcon", "content3", "description", "featureSectionsFeature2", "brandIcon2", "content4", "title", "description2", "featureSectionsFeature3", "brandIcon3", "content5", "title2", "description3", "image", "sharedDotPattern", "grid", "column", "pattern", "pattern2", "pattern3", "column2", "pattern4", "pattern5", "pattern6", "column3", "pattern7", "pattern8", "pattern9", "featureExample", "alwaysInTheLoop", "image2", "sharedDotPattern2", "grid2", "column4", "pattern92", "pattern82", "pattern72", "column5", "pattern62", "pattern52", "pattern42", "column6", "pattern32", "pattern22", "pattern1", "featureExample2", "leadingContent3", "header3", "supportingText4", "features3", "featureSectionsFeature4", "brandIcon4", "content6", "title3", "description4", "featureSectionsFeature5", "brandIcon5", "content7", "title4", "description5"],
features: ["features", "alternativeSideBySideWithImagesDesktop", "container3", "retireOutdatedElectronics", "supportingText2", "solveUniqueProblems", "leadingContent2", "header2", "supportingText3", "features2", "featureSectionsFeature", "brandIcon", "content3", "description", "featureSectionsFeature2", "brandIcon2", "content4", "title", "description2", "featureSectionsFeature3", "brandIcon3", "content5", "title2", "description3", "image", "sharedDotPattern", "grid", "column", "pattern", "pattern2", "pattern3", "column2", "pattern4", "pattern5", "pattern6", "column3", "pattern7", "pattern8", "pattern9", "featureExample", "alwaysInTheLoop", "image2", "sharedDotPattern2", "grid2", "column4", "pattern92", "pattern82", "pattern72", "column5", "pattern62", "pattern52", "pattern42", "column6", "pattern32", "pattern22", "pattern1", "featureExample2", "leadingContent3", "header3", "supportingText4", "features3", "featureSectionsFeature4", "brandIcon4", "content6", "title3", "description4", "featureSectionsFeature5", "brandIcon5", "content7", "title4", "description5"],
alternativeSideBySideWithImagesDesktop: ["alternativeSideBySideWithImagesDesktop", "container3", "retireOutdatedElectronics", "supportingText2", "solveUniqueProblems", "leadingContent2", "header2", "supportingText3", "features2", "featureSectionsFeature", "brandIcon", "content3", "description", "featureSectionsFeature2", "brandIcon2", "content4", "title", "description2", "featureSectionsFeature3", "brandIcon3", "content5", "title2", "description3", "image", "sharedDotPattern", "grid", "column", "pattern", "pattern2", "pattern3", "column2", "pattern4", "pattern5", "pattern6", "column3", "pattern7", "pattern8", "pattern9", "featureExample", "alwaysInTheLoop", "image2", "sharedDotPattern2", "grid2", "column4", "pattern92", "pattern82", "pattern72", "column5", "pattern62", "pattern52", "pattern42", "column6", "pattern32", "pattern22", "pattern1", "featureExample2", "leadingContent3", "header3", "supportingText4", "features3", "featureSectionsFeature4", "brandIcon4", "content6", "title3", "description4", "featureSectionsFeature5", "brandIcon5", "content7", "title4", "description5"],
container3: ["container3", "retireOutdatedElectronics", "supportingText2", "solveUniqueProblems", "leadingContent2", "header2", "supportingText3", "features2", "featureSectionsFeature", "brandIcon", "content3", "description", "featureSectionsFeature2", "brandIcon2", "content4", "title", "description2", "featureSectionsFeature3", "brandIcon3", "content5", "title2", "description3", "image", "sharedDotPattern", "grid", "column", "pattern", "pattern2", "pattern3", "column2", "pattern4", "pattern5", "pattern6", "column3", "pattern7", "pattern8", "pattern9", "featureExample", "alwaysInTheLoop", "image2", "sharedDotPattern2", "grid2", "column4", "pattern92", "pattern82", "pattern72", "column5", "pattern62", "pattern52", "pattern42", "column6", "pattern32", "pattern22", "pattern1", "featureExample2", "leadingContent3", "header3", "supportingText4", "features3", "featureSectionsFeature4", "brandIcon4", "content6", "title3", "description4", "featureSectionsFeature5", "brandIcon5", "content7", "title4", "description5"],
retireOutdatedElectronics: ["retireOutdatedElectronics", "supportingText2"],
supportingText2: ["supportingText2"],
solveUniqueProblems: ["solveUniqueProblems", "leadingContent2", "header2", "supportingText3", "features2", "featureSectionsFeature", "brandIcon", "content3", "description", "featureSectionsFeature2", "brandIcon2", "content4", "title", "description2", "featureSectionsFeature3", "brandIcon3", "content5", "title2", "description3", "image", "sharedDotPattern", "grid", "column", "pattern", "pattern2", "pattern3", "column2", "pattern4", "pattern5", "pattern6", "column3", "pattern7", "pattern8", "pattern9", "featureExample"],
leadingContent2: ["leadingContent2", "header2", "supportingText3", "features2", "featureSectionsFeature", "brandIcon", "content3", "description", "featureSectionsFeature2", "brandIcon2", "content4", "title", "description2", "featureSectionsFeature3", "brandIcon3", "content5", "title2", "description3"],
header2: ["header2", "supportingText3"],
supportingText3: ["supportingText3"],
features2: ["features2", "featureSectionsFeature", "brandIcon", "content3", "description", "featureSectionsFeature2", "brandIcon2", "content4", "title", "description2", "featureSectionsFeature3", "brandIcon3", "content5", "title2", "description3"],
featureSectionsFeature: ["featureSectionsFeature", "brandIcon", "content3", "description"],
brandIcon: ["brandIcon"],
content3: ["content3", "description"],
description: ["description"],
featureSectionsFeature2: ["featureSectionsFeature2", "brandIcon2", "content4", "title", "description2"],
brandIcon2: ["brandIcon2"],
content4: ["content4", "title", "description2"],
title: ["title"],
description2: ["description2"],
featureSectionsFeature3: ["featureSectionsFeature3", "brandIcon3", "content5", "title2", "description3"],
brandIcon3: ["brandIcon3"],
content5: ["content5", "title2", "description3"],
title2: ["title2"],
description3: ["description3"],
image: ["image", "sharedDotPattern", "grid", "column", "pattern", "pattern2", "pattern3", "column2", "pattern4", "pattern5", "pattern6", "column3", "pattern7", "pattern8", "pattern9", "featureExample"],
sharedDotPattern: ["sharedDotPattern", "grid", "column", "pattern", "pattern2", "pattern3", "column2", "pattern4", "pattern5", "pattern6", "column3", "pattern7", "pattern8", "pattern9"],
grid: ["grid", "column", "pattern", "pattern2", "pattern3", "column2", "pattern4", "pattern5", "pattern6", "column3", "pattern7", "pattern8", "pattern9"],
column: ["column", "pattern", "pattern2", "pattern3"],
pattern: ["pattern"],
pattern2: ["pattern2"],
pattern3: ["pattern3"],
column2: ["column2", "pattern4", "pattern5", "pattern6"],
pattern4: ["pattern4"],
pattern5: ["pattern5"],
pattern6: ["pattern6"],
column3: ["column3", "pattern7", "pattern8", "pattern9"],
pattern7: ["pattern7"],
pattern8: ["pattern8"],
pattern9: ["pattern9"],
featureExample: ["featureExample"],
alwaysInTheLoop: ["alwaysInTheLoop", "image2", "sharedDotPattern2", "grid2", "column4", "pattern92", "pattern82", "pattern72", "column5", "pattern62", "pattern52", "pattern42", "column6", "pattern32", "pattern22", "pattern1", "featureExample2", "leadingContent3", "header3", "supportingText4", "features3", "featureSectionsFeature4", "brandIcon4", "content6", "title3", "description4", "featureSectionsFeature5", "brandIcon5", "content7", "title4", "description5"],
image2: ["image2", "sharedDotPattern2", "grid2", "column4", "pattern92", "pattern82", "pattern72", "column5", "pattern62", "pattern52", "pattern42", "column6", "pattern32", "pattern22", "pattern1", "featureExample2"],
sharedDotPattern2: ["sharedDotPattern2", "grid2", "column4", "pattern92", "pattern82", "pattern72", "column5", "pattern62", "pattern52", "pattern42", "column6", "pattern32", "pattern22", "pattern1"],
grid2: ["grid2", "column4", "pattern92", "pattern82", "pattern72", "column5", "pattern62", "pattern52", "pattern42", "column6", "pattern32", "pattern22", "pattern1"],
column4: ["column4", "pattern92", "pattern82", "pattern72"],
pattern92: ["pattern92"],
pattern82: ["pattern82"],
pattern72: ["pattern72"],
column5: ["column5", "pattern62", "pattern52", "pattern42"],
pattern62: ["pattern62"],
pattern52: ["pattern52"],
pattern42: ["pattern42"],
column6: ["column6", "pattern32", "pattern22", "pattern1"],
pattern32: ["pattern32"],
pattern22: ["pattern22"],
pattern1: ["pattern1"],
featureExample2: ["featureExample2"],
leadingContent3: ["leadingContent3", "header3", "supportingText4", "features3", "featureSectionsFeature4", "brandIcon4", "content6", "title3", "description4", "featureSectionsFeature5", "brandIcon5", "content7", "title4", "description5"],
header3: ["header3", "supportingText4"],
supportingText4: ["supportingText4"],
features3: ["features3", "featureSectionsFeature4", "brandIcon4", "content6", "title3", "description4", "featureSectionsFeature5", "brandIcon5", "content7", "title4", "description5"],
featureSectionsFeature4: ["featureSectionsFeature4", "brandIcon4", "content6", "title3", "description4"],
brandIcon4: ["brandIcon4"],
content6: ["content6", "title3", "description4"],
title3: ["title3"],
description4: ["description4"],
featureSectionsFeature5: ["featureSectionsFeature5", "brandIcon5", "content7", "title4", "description5"],
brandIcon5: ["brandIcon5"],
content7: ["content7", "title4", "description5"],
title4: ["title4"],
description5: ["description5"],
    } as const;
    type NodeNameType = keyof typeof PlasmicDescendants;
    type DescendantsType<T extends NodeNameType> = (typeof PlasmicDescendants)[T][number];
    type NodeDefaultElementType = {
      frame2Features: "div";
features: "div";
alternativeSideBySideWithImagesDesktop: "div";
container3: "div";
retireOutdatedElectronics: "div";
supportingText2: "div";
solveUniqueProblems: "div";
leadingContent2: "div";
header2: "div";
supportingText3: "div";
features2: "div";
featureSectionsFeature: "div";
brandIcon: "div";
content3: "div";
description: "div";
featureSectionsFeature2: "div";
brandIcon2: "div";
content4: "div";
title: "div";
description2: "div";
featureSectionsFeature3: "div";
brandIcon3: "div";
content5: "div";
title2: "div";
description3: "div";
image: "div";
sharedDotPattern: "div";
grid: "div";
column: "div";
pattern: "div";
pattern2: "div";
pattern3: "div";
column2: "div";
pattern4: "div";
pattern5: "div";
pattern6: "div";
column3: "div";
pattern7: "div";
pattern8: "div";
pattern9: "div";
featureExample: "div";
alwaysInTheLoop: "div";
image2: "div";
sharedDotPattern2: "div";
grid2: "div";
column4: "div";
pattern92: "div";
pattern82: "div";
pattern72: "div";
column5: "div";
pattern62: "div";
pattern52: "div";
pattern42: "div";
column6: "div";
pattern32: "div";
pattern22: "div";
pattern1: "div";
featureExample2: "div";
leadingContent3: "div";
header3: "div";
supportingText4: "div";
features3: "div";
featureSectionsFeature4: "div";
brandIcon4: "div";
content6: "div";
title3: "div";
description4: "div";
featureSectionsFeature5: "div";
brandIcon5: "div";
content7: "div";
title4: "div";
description5: "div"
    };
  

    
    type ReservedPropsType = "variants" | "args" | "overrides";
    type NodeOverridesType<T extends NodeNameType> = Pick<PlasmicFeatures__OverridesType, DescendantsType<T>>;
    type NodeComponentProps<T extends NodeNameType> = (
      // Explicitly specify variants, args, and overrides as objects
      & {
        variants?: PlasmicFeatures__VariantsArgs;
        args?: PlasmicFeatures__ArgsType;
        overrides?: NodeOverridesType<T>;
      }
      // Specify variants directly as props
      & Omit<PlasmicFeatures__VariantsArgs, ReservedPropsType>
      // Specify args directly as props
      & Omit<PlasmicFeatures__ArgsType, ReservedPropsType>
      // Specify overrides for each element directly as props
      & Omit<NodeOverridesType<T>, ReservedPropsType | VariantPropType | ArgPropType>
      // Specify props for the root element
      & Omit<Partial<React.ComponentProps<NodeDefaultElementType[T]>>, ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>>
    );
    function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
      type PropsType = NodeComponentProps<NodeName> & {key?: React.Key};
      const func = function<T extends PropsType>(props: T & StrictProps<T, PropsType>) {
        const {variants, args, overrides} = deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicFeatures__ArgProps,
          internalVariantPropNames: PlasmicFeatures__VariantProps,
        });

        return PlasmicFeatures__RenderFunc({
          variants, args, overrides, forNode: nodeName
        });
      };
      if (nodeName === "frame2Features") {
        func.displayName = "PlasmicFeatures";
      } else {
        func.displayName = `PlasmicFeatures.${nodeName}`;
      }
      return func;
    }

    export const PlasmicFeatures = Object.assign(
      // Top-level PlasmicFeatures renders the root element
      makeNodeComponent("frame2Features"),
      {
        // Helper components rendering sub-elements
        features: makeNodeComponent("features"),
alternativeSideBySideWithImagesDesktop: makeNodeComponent("alternativeSideBySideWithImagesDesktop"),
container3: makeNodeComponent("container3"),
retireOutdatedElectronics: makeNodeComponent("retireOutdatedElectronics"),
supportingText2: makeNodeComponent("supportingText2"),
solveUniqueProblems: makeNodeComponent("solveUniqueProblems"),
leadingContent2: makeNodeComponent("leadingContent2"),
header2: makeNodeComponent("header2"),
supportingText3: makeNodeComponent("supportingText3"),
features2: makeNodeComponent("features2"),
featureSectionsFeature: makeNodeComponent("featureSectionsFeature"),
brandIcon: makeNodeComponent("brandIcon"),
content3: makeNodeComponent("content3"),
description: makeNodeComponent("description"),
featureSectionsFeature2: makeNodeComponent("featureSectionsFeature2"),
brandIcon2: makeNodeComponent("brandIcon2"),
content4: makeNodeComponent("content4"),
title: makeNodeComponent("title"),
description2: makeNodeComponent("description2"),
featureSectionsFeature3: makeNodeComponent("featureSectionsFeature3"),
brandIcon3: makeNodeComponent("brandIcon3"),
content5: makeNodeComponent("content5"),
title2: makeNodeComponent("title2"),
description3: makeNodeComponent("description3"),
image: makeNodeComponent("image"),
sharedDotPattern: makeNodeComponent("sharedDotPattern"),
grid: makeNodeComponent("grid"),
column: makeNodeComponent("column"),
pattern: makeNodeComponent("pattern"),
pattern2: makeNodeComponent("pattern2"),
pattern3: makeNodeComponent("pattern3"),
column2: makeNodeComponent("column2"),
pattern4: makeNodeComponent("pattern4"),
pattern5: makeNodeComponent("pattern5"),
pattern6: makeNodeComponent("pattern6"),
column3: makeNodeComponent("column3"),
pattern7: makeNodeComponent("pattern7"),
pattern8: makeNodeComponent("pattern8"),
pattern9: makeNodeComponent("pattern9"),
featureExample: makeNodeComponent("featureExample"),
alwaysInTheLoop: makeNodeComponent("alwaysInTheLoop"),
image2: makeNodeComponent("image2"),
sharedDotPattern2: makeNodeComponent("sharedDotPattern2"),
grid2: makeNodeComponent("grid2"),
column4: makeNodeComponent("column4"),
pattern92: makeNodeComponent("pattern92"),
pattern82: makeNodeComponent("pattern82"),
pattern72: makeNodeComponent("pattern72"),
column5: makeNodeComponent("column5"),
pattern62: makeNodeComponent("pattern62"),
pattern52: makeNodeComponent("pattern52"),
pattern42: makeNodeComponent("pattern42"),
column6: makeNodeComponent("column6"),
pattern32: makeNodeComponent("pattern32"),
pattern22: makeNodeComponent("pattern22"),
pattern1: makeNodeComponent("pattern1"),
featureExample2: makeNodeComponent("featureExample2"),
leadingContent3: makeNodeComponent("leadingContent3"),
header3: makeNodeComponent("header3"),
supportingText4: makeNodeComponent("supportingText4"),
features3: makeNodeComponent("features3"),
featureSectionsFeature4: makeNodeComponent("featureSectionsFeature4"),
brandIcon4: makeNodeComponent("brandIcon4"),
content6: makeNodeComponent("content6"),
title3: makeNodeComponent("title3"),
description4: makeNodeComponent("description4"),
featureSectionsFeature5: makeNodeComponent("featureSectionsFeature5"),
brandIcon5: makeNodeComponent("brandIcon5"),
content7: makeNodeComponent("content7"),
title4: makeNodeComponent("title4"),
description5: makeNodeComponent("description5"),

        // Metadata about props expected for PlasmicFeatures
        internalVariantProps: PlasmicFeatures__VariantProps,
        internalArgProps: PlasmicFeatures__ArgProps,
      }
    );
  

    export default PlasmicFeatures;
    /* prettier-ignore-end */
  