
    // @ts-nocheck
    /* eslint-disable */
    /* tslint:disable */
    /* prettier-ignore-start */
    /** @jsxRuntime classic */
    /** @jsx createPlasmicElementProxy */
    /** @jsxFrag React.Fragment */
    // This class is auto-generated by Plasmic; please do not edit!
    // Plasmic Project: cB98qoa8i3odyeQmSRqxXv
    // Component: Tzd-YJ2bsFkzO
    // plasmic-unformatted
    import * as React from "react";
    
    import * as p from  "@plasmicapp/react-web";
    import {hasVariant, classNames, wrapWithClassName, createPlasmicElementProxy, makeFragment, MultiChoiceArg, SingleBooleanChoiceArg, SingleChoiceArg, pick, omit, useTrigger, StrictProps, deriveRenderOpts, ensureGlobalVariants} from "@plasmicapp/react-web";
    import BaseCard from "..//BaseCard";  // plasmic-import: 2y0k2cwVaTHJA/component
import Bullet from "..//Bullet";  // plasmic-import: W62hJLXSC_eY3/component
import LinkButton from "..//LinkButton";  // plasmic-import: ctwQTDVMmkzF/component
    
    
    import "@plasmicapp/react-web/lib/plasmic.css";
    import  "./plasmic__default_style.css"; // plasmic-import: global/defaultcss
    import  "./plasmic_final_not_exported.css"; // plasmic-import: cB98qoa8i3odyeQmSRqxXv/projectcss
    import  "./PlasmicPlan.css" // plasmic-import: Tzd-YJ2bsFkzO/css
  
    
    

    
    export type PlasmicPlan__VariantMembers = {
      
    };
    export type PlasmicPlan__VariantsArgs = {};
    type VariantPropType = keyof PlasmicPlan__VariantsArgs;
    export const PlasmicPlan__VariantProps = new Array<VariantPropType>();
  

    
    export type PlasmicPlan__ArgsType = {
    price?: React.ReactNode;
name?: React.ReactNode;
description?: React.ReactNode;
children?: React.ReactNode
  };
    type ArgPropType = keyof PlasmicPlan__ArgsType;
    export const PlasmicPlan__ArgProps = new Array<ArgPropType>("price","name","description","children");
  

    export type PlasmicPlan__OverridesType = {
    root?: p.Flex<typeof BaseCard>;
linkButton?: p.Flex<typeof LinkButton>;
  };

    
    export interface DefaultPlanProps {
      price?: React.ReactNode;
name?: React.ReactNode;
description?: React.ReactNode;
children?: React.ReactNode
      className?: string;
    }
  

    
    function PlasmicPlan__RenderFunc(
      props: {
        variants: PlasmicPlan__VariantsArgs,
        args: PlasmicPlan__ArgsType
        overrides: PlasmicPlan__OverridesType
        forNode?: string
      }
    ) {
      const {variants, args, overrides, forNode} = props;

      
      
      return (
        
  <BaseCard
    
    data-plasmic-name={"root"}
    data-plasmic-override={overrides.root}
    data-plasmic-root={true}
    data-plasmic-for-node={forNode}
    
    className={classNames("__wab_instance", "Plan__root__svtm4")}
    
    >
          
  <div
    
    
    
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "Plan__box__vTz0Y")}
    
    >
          
  <p.Stack
    as={"div"}
    
    
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "Plan__box__fNCxB")}
    
    >
          <p.PlasmicSlot
      defaultContents={"Basic"}
      value={args.name}
       />
<p.PlasmicSlot
      defaultContents={
  <div
    
    
    
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "Plan__box__xyEBq")}
    
    >
          { "$10" }
        </div>
  }
      value={args.price}
       />
<p.PlasmicSlot
      defaultContents={
  <p.Stack
    as={"div"}
    
    
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "Plan__box__b8IDh")}
    
    >
          
  <Bullet
    
    
    
    
    
    
    className={classNames("__wab_instance", "Plan__bullet__py9Rc")}
    
    />
  

  <Bullet
    
    
    
    
    
    
    className={classNames("__wab_instance", "Plan__bullet___0Dv1W")}
    
    />
  

  <Bullet
    
    
    
    
    
    
    className={classNames("__wab_instance", "Plan__bullet__aH5S")}
    
    />
  
        </p.Stack>
  }
      value={args.description}
       />

  <div
    
    
    
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "Plan__box__eBufd")}
    
    >
          <p.PlasmicSlot
      defaultContents={
  <LinkButton
    
    data-plasmic-name={"linkButton"}
    data-plasmic-override={overrides.linkButton}
    
    
    
    href={("" as const)}
text={"Get started"}
type={("outlineBlue" as const)}
    
    />
  }
      value={args.children}
       />
        </div>
  
        </p.Stack>
  
        </div>
  
        </BaseCard>
  
      ) as React.ReactElement | null;
    }

    
    const PlasmicDescendants = {
      root: ["root", "linkButton"],
linkButton: ["linkButton"],
    } as const;
    type NodeNameType = keyof typeof PlasmicDescendants;
    type DescendantsType<T extends NodeNameType> = (typeof PlasmicDescendants)[T][number];
    type NodeDefaultElementType = {
      root: typeof BaseCard;
linkButton: typeof LinkButton
    };
  

    
    type ReservedPropsType = "variants" | "args" | "overrides";
    type NodeOverridesType<T extends NodeNameType> = Pick<PlasmicPlan__OverridesType, DescendantsType<T>>;
    type NodeComponentProps<T extends NodeNameType> = (
      // Explicitly specify variants, args, and overrides as objects
      & {
        variants?: PlasmicPlan__VariantsArgs;
        args?: PlasmicPlan__ArgsType;
        overrides?: NodeOverridesType<T>;
      }
      // Specify variants directly as props
      & Omit<PlasmicPlan__VariantsArgs, ReservedPropsType>
      // Specify args directly as props
      & Omit<PlasmicPlan__ArgsType, ReservedPropsType>
      // Specify overrides for each element directly as props
      & Omit<NodeOverridesType<T>, ReservedPropsType | VariantPropType | ArgPropType>
      // Specify props for the root element
      & Omit<Partial<React.ComponentProps<NodeDefaultElementType[T]>>, ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>>
    );
    function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
      type PropsType = NodeComponentProps<NodeName> & {key?: React.Key};
      const func = function<T extends PropsType>(props: T & StrictProps<T, PropsType>) {
        const {variants, args, overrides} = deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicPlan__ArgProps,
          internalVariantPropNames: PlasmicPlan__VariantProps,
        });

        return PlasmicPlan__RenderFunc({
          variants, args, overrides, forNode: nodeName
        });
      };
      if (nodeName === "root") {
        func.displayName = "PlasmicPlan";
      } else {
        func.displayName = `PlasmicPlan.${nodeName}`;
      }
      return func;
    }

    export const PlasmicPlan = Object.assign(
      // Top-level PlasmicPlan renders the root element
      makeNodeComponent("root"),
      {
        // Helper components rendering sub-elements
        linkButton: makeNodeComponent("linkButton"),

        // Metadata about props expected for PlasmicPlan
        internalVariantProps: PlasmicPlan__VariantProps,
        internalArgProps: PlasmicPlan__ArgProps,
      }
    );
  

    export default PlasmicPlan;
    /* prettier-ignore-end */
  