
    // @ts-nocheck
    /* eslint-disable */
    /* tslint:disable */
    /* prettier-ignore-start */
    /** @jsxRuntime classic */
    /** @jsx createPlasmicElementProxy */
    /** @jsxFrag React.Fragment */
    // This class is auto-generated by Plasmic; please do not edit!
    // Plasmic Project: cB98qoa8i3odyeQmSRqxXv
    // Component: ctwQTDVMmkzF
    // plasmic-unformatted
    import * as React from "react";
    
    import * as p from  "@plasmicapp/react-web";
    import {hasVariant, classNames, wrapWithClassName, createPlasmicElementProxy, makeFragment, MultiChoiceArg, SingleBooleanChoiceArg, SingleChoiceArg, pick, omit, useTrigger, StrictProps, deriveRenderOpts, ensureGlobalVariants} from "@plasmicapp/react-web";
    
    
    
    import "@plasmicapp/react-web/lib/plasmic.css";
    import  "./plasmic__default_style.css"; // plasmic-import: global/defaultcss
    import  "./plasmic_final_not_exported.css"; // plasmic-import: cB98qoa8i3odyeQmSRqxXv/projectcss
    import  "./PlasmicLinkButton.css" // plasmic-import: ctwQTDVMmkzF/css
  
    
    

    
    export type PlasmicLinkButton__VariantMembers = {
      type: "solidBlue" | "solidBlack" | "outlineBlue" | "small";
    };
    export type PlasmicLinkButton__VariantsArgs = {
    type?: SingleChoiceArg<"solidBlue" | "solidBlack" | "outlineBlue" | "small">
  };
    type VariantPropType = keyof PlasmicLinkButton__VariantsArgs;
    export const PlasmicLinkButton__VariantProps = new Array<VariantPropType>("type");
  

    
    export type PlasmicLinkButton__ArgsType = {
    href?: string;
text?: React.ReactNode
  };
    type ArgPropType = keyof PlasmicLinkButton__ArgsType;
    export const PlasmicLinkButton__ArgProps = new Array<ArgPropType>("href","text");
  

    export type PlasmicLinkButton__OverridesType = {
    root?: p.Flex<"a">;
  };

    
    export interface DefaultLinkButtonProps {
      href?: string;
text?: React.ReactNode;
type?: SingleChoiceArg<"solidBlue" | "solidBlack" | "outlineBlue" | "small">
      className?: string;
    }
  

    
    function PlasmicLinkButton__RenderFunc(
      props: {
        variants: PlasmicLinkButton__VariantsArgs,
        args: PlasmicLinkButton__ArgsType
        overrides: PlasmicLinkButton__OverridesType
        forNode?: string
      }
    ) {
      const {variants, args, overrides, forNode} = props;

      
      
      return (
        
  <a
    
    data-plasmic-name={"root"}
    data-plasmic-override={overrides.root}
    data-plasmic-root={true}
    data-plasmic-for-node={forNode}
    
    className={classNames("plasmic_default__all", "plasmic_default__a", "root_reset_cB98qoa8i3odyeQmSRqxXv", "LinkButton__root__gz3U7", { "LinkButton__root__type_outlineBlue__gz3U7OyHiI": hasVariant(variants, "type", "outlineBlue"), "LinkButton__root__type_small__gz3U7NJph5": hasVariant(variants, "type", "small"), "LinkButton__root__type_solidBlack__gz3U7SBreV": hasVariant(variants, "type", "solidBlack"), "LinkButton__root__type_solidBlue__gz3U7CiDc": hasVariant(variants, "type", "solidBlue") })}
href={args.href !== undefined ? args.href : "#"}
    
    >
          <p.PlasmicSlot
      defaultContents={"Do the thing"}
      value={args.text}
      className={classNames("LinkButton__slotText__kAfhu", { "LinkButton__slotText__type_outlineBlue__kAfhuoyHiI": hasVariant(variants, "type", "outlineBlue"), "LinkButton__slotText__type_solidBlack__kAfhuSBreV": hasVariant(variants, "type", "solidBlack"), "LinkButton__slotText__type_solidBlue__kAfhuCiDc": hasVariant(variants, "type", "solidBlue") })} />
        </a>
  
      ) as React.ReactElement | null;
    }

    
    const PlasmicDescendants = {
      root: ["root"],
    } as const;
    type NodeNameType = keyof typeof PlasmicDescendants;
    type DescendantsType<T extends NodeNameType> = (typeof PlasmicDescendants)[T][number];
    type NodeDefaultElementType = {
      root: "a"
    };
  

    
    type ReservedPropsType = "variants" | "args" | "overrides";
    type NodeOverridesType<T extends NodeNameType> = Pick<PlasmicLinkButton__OverridesType, DescendantsType<T>>;
    type NodeComponentProps<T extends NodeNameType> = (
      // Explicitly specify variants, args, and overrides as objects
      & {
        variants?: PlasmicLinkButton__VariantsArgs;
        args?: PlasmicLinkButton__ArgsType;
        overrides?: NodeOverridesType<T>;
      }
      // Specify variants directly as props
      & Omit<PlasmicLinkButton__VariantsArgs, ReservedPropsType>
      // Specify args directly as props
      & Omit<PlasmicLinkButton__ArgsType, ReservedPropsType>
      // Specify overrides for each element directly as props
      & Omit<NodeOverridesType<T>, ReservedPropsType | VariantPropType | ArgPropType>
      // Specify props for the root element
      & Omit<Partial<React.ComponentProps<NodeDefaultElementType[T]>>, ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>>
    );
    function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
      type PropsType = NodeComponentProps<NodeName> & {key?: React.Key};
      const func = function<T extends PropsType>(props: T & StrictProps<T, PropsType>) {
        const {variants, args, overrides} = deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicLinkButton__ArgProps,
          internalVariantPropNames: PlasmicLinkButton__VariantProps,
        });

        return PlasmicLinkButton__RenderFunc({
          variants, args, overrides, forNode: nodeName
        });
      };
      if (nodeName === "root") {
        func.displayName = "PlasmicLinkButton";
      } else {
        func.displayName = `PlasmicLinkButton.${nodeName}`;
      }
      return func;
    }

    export const PlasmicLinkButton = Object.assign(
      // Top-level PlasmicLinkButton renders the root element
      makeNodeComponent("root"),
      {
        // Helper components rendering sub-elements
        

        // Metadata about props expected for PlasmicLinkButton
        internalVariantProps: PlasmicLinkButton__VariantProps,
        internalArgProps: PlasmicLinkButton__ArgProps,
      }
    );
  

    export default PlasmicLinkButton;
    /* prettier-ignore-end */
  