
    // @ts-nocheck
    /* eslint-disable */
    /* tslint:disable */
    /* prettier-ignore-start */
    /** @jsxRuntime classic */
    /** @jsx createPlasmicElementProxy */
    /** @jsxFrag React.Fragment */
    // This class is auto-generated by Plasmic; please do not edit!
    // Plasmic Project: cB98qoa8i3odyeQmSRqxXv
    // Component: LSgneob4-QJ
    // plasmic-unformatted
    import * as React from "react";
    
    import * as p from  "@plasmicapp/react-web";
    import {hasVariant, classNames, wrapWithClassName, createPlasmicElementProxy, makeFragment, MultiChoiceArg, SingleBooleanChoiceArg, SingleChoiceArg, pick, omit, useTrigger, StrictProps, deriveRenderOpts, ensureGlobalVariants} from "@plasmicapp/react-web";
    
    
    
    import "@plasmicapp/react-web/lib/plasmic.css";
    import  "./plasmic__default_style.css"; // plasmic-import: global/defaultcss
    import  "./plasmic_final_not_exported.css"; // plasmic-import: cB98qoa8i3odyeQmSRqxXv/projectcss
    import  "./PlasmicPricingTableHeader.css" // plasmic-import: LSgneob4-QJ/css
  
    
    

    
    export type PlasmicPricingTableHeader__VariantMembers = {
      
    };
    export type PlasmicPricingTableHeader__VariantsArgs = {};
    type VariantPropType = keyof PlasmicPricingTableHeader__VariantsArgs;
    export const PlasmicPricingTableHeader__VariantProps = new Array<VariantPropType>();
  

    
    export type PlasmicPricingTableHeader__ArgsType = {};
    type ArgPropType = keyof PlasmicPricingTableHeader__ArgsType;
    export const PlasmicPricingTableHeader__ArgProps = new Array<ArgPropType>();
  

    export type PlasmicPricingTableHeader__OverridesType = {
    root?: p.Flex<"div">;
description9?: p.Flex<"div">;
rowHead?: p.Flex<"div">;
text31?: p.Flex<"div">;
rowHead2?: p.Flex<"div">;
topBorder61?: p.Flex<"div">;
content63?: p.Flex<"div">;
text32?: p.Flex<"div">;
basic4?: p.Flex<"div">;
columnHead?: p.Flex<"div">;
text33?: p.Flex<"div">;
cell?: p.Flex<"div">;
topBorder62?: p.Flex<"div">;
content64?: p.Flex<"div">;
details?: p.Flex<"div">;
pricing?: p.Flex<"div">;
price?: p.Flex<"div">;
frequency?: p.Flex<"div">;
supportingText5?: p.Flex<"div">;
pricingPagesButtonLink4?: p.Flex<"div">;
text34?: p.Flex<"div">;
essential4?: p.Flex<"div">;
columnHead2?: p.Flex<"div">;
text35?: p.Flex<"div">;
cell2?: p.Flex<"div">;
topBorder63?: p.Flex<"div">;
content65?: p.Flex<"div">;
details2?: p.Flex<"div">;
pricing2?: p.Flex<"div">;
price2?: p.Flex<"div">;
frequency2?: p.Flex<"div">;
supportingText6?: p.Flex<"div">;
pricingPagesButtonLink5?: p.Flex<"div">;
text36?: p.Flex<"div">;
premium4?: p.Flex<"div">;
columnHead3?: p.Flex<"div">;
text37?: p.Flex<"div">;
cell3?: p.Flex<"div">;
topBorder64?: p.Flex<"div">;
content66?: p.Flex<"div">;
details3?: p.Flex<"div">;
pricing3?: p.Flex<"div">;
price3?: p.Flex<"div">;
frequency3?: p.Flex<"div">;
supportingText7?: p.Flex<"div">;
pricingPagesButtonLink6?: p.Flex<"div">;
text38?: p.Flex<"div">;
  };

    
    export interface DefaultPricingTableHeaderProps {
      
      className?: string;
    }
  

    
    function PlasmicPricingTableHeader__RenderFunc(
      props: {
        variants: PlasmicPricingTableHeader__VariantsArgs,
        args: PlasmicPricingTableHeader__ArgsType
        overrides: PlasmicPricingTableHeader__OverridesType
        forNode?: string
      }
    ) {
      const {variants, args, overrides, forNode} = props;

      
      
      return (
        
  <p.Stack
    as={"div"}
    data-plasmic-name={"root"}
    data-plasmic-override={overrides.root}
    data-plasmic-root={true}
    data-plasmic-for-node={forNode}
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "root_reset_cB98qoa8i3odyeQmSRqxXv", "PricingTableHeader__root__ofIr")}
    
    >
          
  <div
    
    data-plasmic-name={"description9"}
    data-plasmic-override={overrides.description9}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "PricingTableHeader__description9__gpCd")}
    
    >
          
  <div
    
    data-plasmic-name={"rowHead"}
    data-plasmic-override={overrides.rowHead}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "PricingTableHeader__rowHead___4JvBj")}
    
    >
          
  <div
    
    data-plasmic-name={"text31"}
    data-plasmic-override={overrides.text31}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "PricingTableHeader__text31__exik0")}
    
    >
          { "Plans" }
        </div>
  
        </div>
  

  <div
    
    data-plasmic-name={"rowHead2"}
    data-plasmic-override={overrides.rowHead2}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "PricingTableHeader__rowHead2__gnV2Q")}
    
    >
          
  <div
    
    data-plasmic-name={"topBorder61"}
    data-plasmic-override={overrides.topBorder61}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "PricingTableHeader__topBorder61___43DfT")}
    
    />
  

  <div
    
    data-plasmic-name={"content63"}
    data-plasmic-override={overrides.content63}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "PricingTableHeader__content63__oasbd")}
    
    >
          
  <div
    
    data-plasmic-name={"text32"}
    data-plasmic-override={overrides.text32}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "PricingTableHeader__text32__fOaCd")}
    
    >
          { "Pricing" }
        </div>
  
        </div>
  
        </div>
  
        </div>
  

  <div
    
    data-plasmic-name={"basic4"}
    data-plasmic-override={overrides.basic4}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "PricingTableHeader__basic4___8Znz4")}
    
    >
          
  <div
    
    data-plasmic-name={"columnHead"}
    data-plasmic-override={overrides.columnHead}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "PricingTableHeader__columnHead___4P4I4")}
    
    >
          
  <div
    
    data-plasmic-name={"text33"}
    data-plasmic-override={overrides.text33}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "PricingTableHeader__text33___8Blmn")}
    
    >
          { "Basic" }
        </div>
  
        </div>
  

  <div
    
    data-plasmic-name={"cell"}
    data-plasmic-override={overrides.cell}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "PricingTableHeader__cell__klOy")}
    
    >
          
  <div
    
    data-plasmic-name={"topBorder62"}
    data-plasmic-override={overrides.topBorder62}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "PricingTableHeader__topBorder62___3OE9W")}
    
    />
  

  <p.Stack
    as={"div"}
    data-plasmic-name={"content64"}
    data-plasmic-override={overrides.content64}
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "PricingTableHeader__content64__b3Yr0")}
    
    >
          
  <p.Stack
    as={"div"}
    data-plasmic-name={"details"}
    data-plasmic-override={overrides.details}
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "PricingTableHeader__details__idDhM")}
    
    >
          
  <p.Stack
    as={"div"}
    data-plasmic-name={"pricing"}
    data-plasmic-override={overrides.pricing}
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "PricingTableHeader__pricing__qtg4G")}
    
    >
          
  <div
    
    data-plasmic-name={"price"}
    data-plasmic-override={overrides.price}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "PricingTableHeader__price__mRknU")}
    
    >
          { "$20" }
        </div>
  

  <div
    
    data-plasmic-name={"frequency"}
    data-plasmic-override={overrides.frequency}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "PricingTableHeader__frequency__sTrF6")}
    
    >
          { "/mo" }
        </div>
  
        </p.Stack>
  

  <div
    
    data-plasmic-name={"supportingText5"}
    data-plasmic-override={overrides.supportingText5}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "PricingTableHeader__supportingText5__s80Cy")}
    
    >
          { "software solutions." }
        </div>
  
        </p.Stack>
  

  <div
    
    data-plasmic-name={"pricingPagesButtonLink4"}
    data-plasmic-override={overrides.pricingPagesButtonLink4}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "PricingTableHeader__pricingPagesButtonLink4__hsk8I")}
    
    >
          
  <div
    
    data-plasmic-name={"text34"}
    data-plasmic-override={overrides.text34}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "PricingTableHeader__text34___8Uw4V")}
    
    >
          { "Buy Basic" }
        </div>
  
        </div>
  
        </p.Stack>
  
        </div>
  
        </div>
  

  <div
    
    data-plasmic-name={"essential4"}
    data-plasmic-override={overrides.essential4}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "PricingTableHeader__essential4__ee6YI")}
    
    >
          
  <div
    
    data-plasmic-name={"columnHead2"}
    data-plasmic-override={overrides.columnHead2}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "PricingTableHeader__columnHead2__s1ET")}
    
    >
          
  <div
    
    data-plasmic-name={"text35"}
    data-plasmic-override={overrides.text35}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "PricingTableHeader__text35__lnL5N")}
    
    >
          { "Essential" }
        </div>
  
        </div>
  

  <div
    
    data-plasmic-name={"cell2"}
    data-plasmic-override={overrides.cell2}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "PricingTableHeader__cell2__oX8LN")}
    
    >
          
  <div
    
    data-plasmic-name={"topBorder63"}
    data-plasmic-override={overrides.topBorder63}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "PricingTableHeader__topBorder63__hhDxw")}
    
    />
  

  <p.Stack
    as={"div"}
    data-plasmic-name={"content65"}
    data-plasmic-override={overrides.content65}
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "PricingTableHeader__content65__cSuRy")}
    
    >
          
  <p.Stack
    as={"div"}
    data-plasmic-name={"details2"}
    data-plasmic-override={overrides.details2}
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "PricingTableHeader__details2___9ZEeb")}
    
    >
          
  <p.Stack
    as={"div"}
    data-plasmic-name={"pricing2"}
    data-plasmic-override={overrides.pricing2}
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "PricingTableHeader__pricing2__wGeyA")}
    
    >
          
  <div
    
    data-plasmic-name={"price2"}
    data-plasmic-override={overrides.price2}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "PricingTableHeader__price2__ij0Ko")}
    
    >
          { "$100" }
        </div>
  

  <div
    
    data-plasmic-name={"frequency2"}
    data-plasmic-override={overrides.frequency2}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "PricingTableHeader__frequency2__iYhZt")}
    
    >
          { "/mo" }
        </div>
  
        </p.Stack>
  

  <div
    
    data-plasmic-name={"supportingText6"}
    data-plasmic-override={overrides.supportingText6}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "PricingTableHeader__supportingText6___1YVyc")}
    
    >
          { "hardware solutions." }
        </div>
  
        </p.Stack>
  

  <div
    
    data-plasmic-name={"pricingPagesButtonLink5"}
    data-plasmic-override={overrides.pricingPagesButtonLink5}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "PricingTableHeader__pricingPagesButtonLink5__rawoT")}
    
    >
          
  <div
    
    data-plasmic-name={"text36"}
    data-plasmic-override={overrides.text36}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "PricingTableHeader__text36__wwx6Y")}
    
    >
          { "Buy Essential" }
        </div>
  
        </div>
  
        </p.Stack>
  
        </div>
  
        </div>
  

  <div
    
    data-plasmic-name={"premium4"}
    data-plasmic-override={overrides.premium4}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "PricingTableHeader__premium4__t1A2")}
    
    >
          
  <div
    
    data-plasmic-name={"columnHead3"}
    data-plasmic-override={overrides.columnHead3}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "PricingTableHeader__columnHead3__tZSas")}
    
    >
          
  <div
    
    data-plasmic-name={"text37"}
    data-plasmic-override={overrides.text37}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "PricingTableHeader__text37___538Wu")}
    
    >
          { "Premium" }
        </div>
  
        </div>
  

  <div
    
    data-plasmic-name={"cell3"}
    data-plasmic-override={overrides.cell3}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "PricingTableHeader__cell3__sxsvR")}
    
    >
          
  <div
    
    data-plasmic-name={"topBorder64"}
    data-plasmic-override={overrides.topBorder64}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "PricingTableHeader__topBorder64__zlIyk")}
    
    />
  

  <p.Stack
    as={"div"}
    data-plasmic-name={"content66"}
    data-plasmic-override={overrides.content66}
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "PricingTableHeader__content66__dr0Yb")}
    
    >
          
  <p.Stack
    as={"div"}
    data-plasmic-name={"details3"}
    data-plasmic-override={overrides.details3}
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "PricingTableHeader__details3__jPq2R")}
    
    >
          
  <p.Stack
    as={"div"}
    data-plasmic-name={"pricing3"}
    data-plasmic-override={overrides.pricing3}
    
    
    hasGap={true}
    className={classNames("plasmic_default__all", "plasmic_default__div", "PricingTableHeader__pricing3__dtbuv")}
    
    >
          
  <div
    
    data-plasmic-name={"price3"}
    data-plasmic-override={overrides.price3}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "PricingTableHeader__price3___7ZJe")}
    
    >
          { "$300" }
        </div>
  

  <div
    
    data-plasmic-name={"frequency3"}
    data-plasmic-override={overrides.frequency3}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "PricingTableHeader__frequency3__dYbt")}
    
    >
          { "/mo" }
        </div>
  
        </p.Stack>
  

  <div
    
    data-plasmic-name={"supportingText7"}
    data-plasmic-override={overrides.supportingText7}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "PricingTableHeader__supportingText7__ycZyp")}
    
    >
          { "software and hardware solutions." }
        </div>
  
        </p.Stack>
  

  <div
    
    data-plasmic-name={"pricingPagesButtonLink6"}
    data-plasmic-override={overrides.pricingPagesButtonLink6}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "PricingTableHeader__pricingPagesButtonLink6__q887F")}
    
    >
          
  <div
    
    data-plasmic-name={"text38"}
    data-plasmic-override={overrides.text38}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "__wab_text", "PricingTableHeader__text38__w0O6J")}
    
    >
          { "Buy Premium" }
        </div>
  
        </div>
  
        </p.Stack>
  
        </div>
  
        </div>
  
        </p.Stack>
  
      ) as React.ReactElement | null;
    }

    
    const PlasmicDescendants = {
      root: ["root", "description9", "rowHead", "text31", "rowHead2", "topBorder61", "content63", "text32", "basic4", "columnHead", "text33", "cell", "topBorder62", "content64", "details", "pricing", "price", "frequency", "supportingText5", "pricingPagesButtonLink4", "text34", "essential4", "columnHead2", "text35", "cell2", "topBorder63", "content65", "details2", "pricing2", "price2", "frequency2", "supportingText6", "pricingPagesButtonLink5", "text36", "premium4", "columnHead3", "text37", "cell3", "topBorder64", "content66", "details3", "pricing3", "price3", "frequency3", "supportingText7", "pricingPagesButtonLink6", "text38"],
description9: ["description9", "rowHead", "text31", "rowHead2", "topBorder61", "content63", "text32"],
rowHead: ["rowHead", "text31"],
text31: ["text31"],
rowHead2: ["rowHead2", "topBorder61", "content63", "text32"],
topBorder61: ["topBorder61"],
content63: ["content63", "text32"],
text32: ["text32"],
basic4: ["basic4", "columnHead", "text33", "cell", "topBorder62", "content64", "details", "pricing", "price", "frequency", "supportingText5", "pricingPagesButtonLink4", "text34"],
columnHead: ["columnHead", "text33"],
text33: ["text33"],
cell: ["cell", "topBorder62", "content64", "details", "pricing", "price", "frequency", "supportingText5", "pricingPagesButtonLink4", "text34"],
topBorder62: ["topBorder62"],
content64: ["content64", "details", "pricing", "price", "frequency", "supportingText5", "pricingPagesButtonLink4", "text34"],
details: ["details", "pricing", "price", "frequency", "supportingText5"],
pricing: ["pricing", "price", "frequency"],
price: ["price"],
frequency: ["frequency"],
supportingText5: ["supportingText5"],
pricingPagesButtonLink4: ["pricingPagesButtonLink4", "text34"],
text34: ["text34"],
essential4: ["essential4", "columnHead2", "text35", "cell2", "topBorder63", "content65", "details2", "pricing2", "price2", "frequency2", "supportingText6", "pricingPagesButtonLink5", "text36"],
columnHead2: ["columnHead2", "text35"],
text35: ["text35"],
cell2: ["cell2", "topBorder63", "content65", "details2", "pricing2", "price2", "frequency2", "supportingText6", "pricingPagesButtonLink5", "text36"],
topBorder63: ["topBorder63"],
content65: ["content65", "details2", "pricing2", "price2", "frequency2", "supportingText6", "pricingPagesButtonLink5", "text36"],
details2: ["details2", "pricing2", "price2", "frequency2", "supportingText6"],
pricing2: ["pricing2", "price2", "frequency2"],
price2: ["price2"],
frequency2: ["frequency2"],
supportingText6: ["supportingText6"],
pricingPagesButtonLink5: ["pricingPagesButtonLink5", "text36"],
text36: ["text36"],
premium4: ["premium4", "columnHead3", "text37", "cell3", "topBorder64", "content66", "details3", "pricing3", "price3", "frequency3", "supportingText7", "pricingPagesButtonLink6", "text38"],
columnHead3: ["columnHead3", "text37"],
text37: ["text37"],
cell3: ["cell3", "topBorder64", "content66", "details3", "pricing3", "price3", "frequency3", "supportingText7", "pricingPagesButtonLink6", "text38"],
topBorder64: ["topBorder64"],
content66: ["content66", "details3", "pricing3", "price3", "frequency3", "supportingText7", "pricingPagesButtonLink6", "text38"],
details3: ["details3", "pricing3", "price3", "frequency3", "supportingText7"],
pricing3: ["pricing3", "price3", "frequency3"],
price3: ["price3"],
frequency3: ["frequency3"],
supportingText7: ["supportingText7"],
pricingPagesButtonLink6: ["pricingPagesButtonLink6", "text38"],
text38: ["text38"],
    } as const;
    type NodeNameType = keyof typeof PlasmicDescendants;
    type DescendantsType<T extends NodeNameType> = (typeof PlasmicDescendants)[T][number];
    type NodeDefaultElementType = {
      root: "div";
description9: "div";
rowHead: "div";
text31: "div";
rowHead2: "div";
topBorder61: "div";
content63: "div";
text32: "div";
basic4: "div";
columnHead: "div";
text33: "div";
cell: "div";
topBorder62: "div";
content64: "div";
details: "div";
pricing: "div";
price: "div";
frequency: "div";
supportingText5: "div";
pricingPagesButtonLink4: "div";
text34: "div";
essential4: "div";
columnHead2: "div";
text35: "div";
cell2: "div";
topBorder63: "div";
content65: "div";
details2: "div";
pricing2: "div";
price2: "div";
frequency2: "div";
supportingText6: "div";
pricingPagesButtonLink5: "div";
text36: "div";
premium4: "div";
columnHead3: "div";
text37: "div";
cell3: "div";
topBorder64: "div";
content66: "div";
details3: "div";
pricing3: "div";
price3: "div";
frequency3: "div";
supportingText7: "div";
pricingPagesButtonLink6: "div";
text38: "div"
    };
  

    
    type ReservedPropsType = "variants" | "args" | "overrides";
    type NodeOverridesType<T extends NodeNameType> = Pick<PlasmicPricingTableHeader__OverridesType, DescendantsType<T>>;
    type NodeComponentProps<T extends NodeNameType> = (
      // Explicitly specify variants, args, and overrides as objects
      & {
        variants?: PlasmicPricingTableHeader__VariantsArgs;
        args?: PlasmicPricingTableHeader__ArgsType;
        overrides?: NodeOverridesType<T>;
      }
      // Specify variants directly as props
      & Omit<PlasmicPricingTableHeader__VariantsArgs, ReservedPropsType>
      // Specify args directly as props
      & Omit<PlasmicPricingTableHeader__ArgsType, ReservedPropsType>
      // Specify overrides for each element directly as props
      & Omit<NodeOverridesType<T>, ReservedPropsType | VariantPropType | ArgPropType>
      // Specify props for the root element
      & Omit<Partial<React.ComponentProps<NodeDefaultElementType[T]>>, ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>>
    );
    function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
      type PropsType = NodeComponentProps<NodeName> & {key?: React.Key};
      const func = function<T extends PropsType>(props: T & StrictProps<T, PropsType>) {
        const {variants, args, overrides} = deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicPricingTableHeader__ArgProps,
          internalVariantPropNames: PlasmicPricingTableHeader__VariantProps,
        });

        return PlasmicPricingTableHeader__RenderFunc({
          variants, args, overrides, forNode: nodeName
        });
      };
      if (nodeName === "root") {
        func.displayName = "PlasmicPricingTableHeader";
      } else {
        func.displayName = `PlasmicPricingTableHeader.${nodeName}`;
      }
      return func;
    }

    export const PlasmicPricingTableHeader = Object.assign(
      // Top-level PlasmicPricingTableHeader renders the root element
      makeNodeComponent("root"),
      {
        // Helper components rendering sub-elements
        description9: makeNodeComponent("description9"),
rowHead: makeNodeComponent("rowHead"),
text31: makeNodeComponent("text31"),
rowHead2: makeNodeComponent("rowHead2"),
topBorder61: makeNodeComponent("topBorder61"),
content63: makeNodeComponent("content63"),
text32: makeNodeComponent("text32"),
basic4: makeNodeComponent("basic4"),
columnHead: makeNodeComponent("columnHead"),
text33: makeNodeComponent("text33"),
cell: makeNodeComponent("cell"),
topBorder62: makeNodeComponent("topBorder62"),
content64: makeNodeComponent("content64"),
details: makeNodeComponent("details"),
pricing: makeNodeComponent("pricing"),
price: makeNodeComponent("price"),
frequency: makeNodeComponent("frequency"),
supportingText5: makeNodeComponent("supportingText5"),
pricingPagesButtonLink4: makeNodeComponent("pricingPagesButtonLink4"),
text34: makeNodeComponent("text34"),
essential4: makeNodeComponent("essential4"),
columnHead2: makeNodeComponent("columnHead2"),
text35: makeNodeComponent("text35"),
cell2: makeNodeComponent("cell2"),
topBorder63: makeNodeComponent("topBorder63"),
content65: makeNodeComponent("content65"),
details2: makeNodeComponent("details2"),
pricing2: makeNodeComponent("pricing2"),
price2: makeNodeComponent("price2"),
frequency2: makeNodeComponent("frequency2"),
supportingText6: makeNodeComponent("supportingText6"),
pricingPagesButtonLink5: makeNodeComponent("pricingPagesButtonLink5"),
text36: makeNodeComponent("text36"),
premium4: makeNodeComponent("premium4"),
columnHead3: makeNodeComponent("columnHead3"),
text37: makeNodeComponent("text37"),
cell3: makeNodeComponent("cell3"),
topBorder64: makeNodeComponent("topBorder64"),
content66: makeNodeComponent("content66"),
details3: makeNodeComponent("details3"),
pricing3: makeNodeComponent("pricing3"),
price3: makeNodeComponent("price3"),
frequency3: makeNodeComponent("frequency3"),
supportingText7: makeNodeComponent("supportingText7"),
pricingPagesButtonLink6: makeNodeComponent("pricingPagesButtonLink6"),
text38: makeNodeComponent("text38"),

        // Metadata about props expected for PlasmicPricingTableHeader
        internalVariantProps: PlasmicPricingTableHeader__VariantProps,
        internalArgProps: PlasmicPricingTableHeader__ArgProps,
      }
    );
  

    export default PlasmicPricingTableHeader;
    /* prettier-ignore-end */
  