
    // @ts-nocheck
    /* eslint-disable */
    /* tslint:disable */
    /* prettier-ignore-start */
    /** @jsxRuntime classic */
    /** @jsx createPlasmicElementProxy */
    /** @jsxFrag React.Fragment */
    // This class is auto-generated by Plasmic; please do not edit!
    // Plasmic Project: cB98qoa8i3odyeQmSRqxXv
    // Component: VghJE9o1Ao
    // plasmic-unformatted
    import * as React from "react";
    
    import * as p from  "@plasmicapp/react-web";
    import {hasVariant, classNames, wrapWithClassName, createPlasmicElementProxy, makeFragment, MultiChoiceArg, SingleBooleanChoiceArg, SingleChoiceArg, pick, omit, useTrigger, StrictProps, deriveRenderOpts, ensureGlobalVariants} from "@plasmicapp/react-web";
    
    
    
    import "@plasmicapp/react-web/lib/plasmic.css";
    import  "./plasmic__default_style.css"; // plasmic-import: global/defaultcss
    import  "./plasmic_final_not_exported.css"; // plasmic-import: cB98qoa8i3odyeQmSRqxXv/projectcss
    import  "./PlasmicSecondPage.css" // plasmic-import: VghJE9o1Ao/css
  
    
    

    
    export type PlasmicSecondPage__VariantMembers = {
      
    };
    export type PlasmicSecondPage__VariantsArgs = {};
    type VariantPropType = keyof PlasmicSecondPage__VariantsArgs;
    export const PlasmicSecondPage__VariantProps = new Array<VariantPropType>();
  

    
    export type PlasmicSecondPage__ArgsType = {};
    type ArgPropType = keyof PlasmicSecondPage__ArgsType;
    export const PlasmicSecondPage__ArgProps = new Array<ArgPropType>();
  

    export type PlasmicSecondPage__OverridesType = {
    root?: p.Flex<"div">;
  };

    
    export interface DefaultSecondPageProps {
      
      className?: string;
    }
  

    
    function PlasmicSecondPage__RenderFunc(
      props: {
        variants: PlasmicSecondPage__VariantsArgs,
        args: PlasmicSecondPage__ArgsType
        overrides: PlasmicSecondPage__OverridesType
        forNode?: string
      }
    ) {
      const {variants, args, overrides, forNode} = props;

      
      
      return (
        <React.Fragment>
    
    
    
      <div className={"plasmic_page_wrapper"}>
        
  <div
    
    data-plasmic-name={"root"}
    data-plasmic-override={overrides.root}
    data-plasmic-root={true}
    data-plasmic-for-node={forNode}
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "root_reset_cB98qoa8i3odyeQmSRqxXv", "SecondPage__root__vsIft")}
    
    />
  
      </div>
    
  </React.Fragment>
      ) as React.ReactElement | null;
    }

    
    const PlasmicDescendants = {
      root: ["root"],
    } as const;
    type NodeNameType = keyof typeof PlasmicDescendants;
    type DescendantsType<T extends NodeNameType> = (typeof PlasmicDescendants)[T][number];
    type NodeDefaultElementType = {
      root: "div"
    };
  

    
    type ReservedPropsType = "variants" | "args" | "overrides";
    type NodeOverridesType<T extends NodeNameType> = Pick<PlasmicSecondPage__OverridesType, DescendantsType<T>>;
    type NodeComponentProps<T extends NodeNameType> = (
      // Explicitly specify variants, args, and overrides as objects
      & {
        variants?: PlasmicSecondPage__VariantsArgs;
        args?: PlasmicSecondPage__ArgsType;
        overrides?: NodeOverridesType<T>;
      }
      // Specify variants directly as props
      & Omit<PlasmicSecondPage__VariantsArgs, ReservedPropsType>
      // Specify args directly as props
      & Omit<PlasmicSecondPage__ArgsType, ReservedPropsType>
      // Specify overrides for each element directly as props
      & Omit<NodeOverridesType<T>, ReservedPropsType | VariantPropType | ArgPropType>
      // Specify props for the root element
      & Omit<Partial<React.ComponentProps<NodeDefaultElementType[T]>>, ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>>
    );
    function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
      type PropsType = NodeComponentProps<NodeName> & {key?: React.Key};
      const func = function<T extends PropsType>(props: T & StrictProps<T, PropsType>) {
        const {variants, args, overrides} = deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicSecondPage__ArgProps,
          internalVariantPropNames: PlasmicSecondPage__VariantProps,
        });

        return PlasmicSecondPage__RenderFunc({
          variants, args, overrides, forNode: nodeName
        });
      };
      if (nodeName === "root") {
        func.displayName = "PlasmicSecondPage";
      } else {
        func.displayName = `PlasmicSecondPage.${nodeName}`;
      }
      return func;
    }

    export const PlasmicSecondPage = Object.assign(
      // Top-level PlasmicSecondPage renders the root element
      makeNodeComponent("root"),
      {
        // Helper components rendering sub-elements
        

        // Metadata about props expected for PlasmicSecondPage
        internalVariantProps: PlasmicSecondPage__VariantProps,
        internalArgProps: PlasmicSecondPage__ArgProps,
      }
    );
  

    export default PlasmicSecondPage;
    /* prettier-ignore-end */
  