
    // @ts-nocheck
    /* eslint-disable */
    /* tslint:disable */
    /* prettier-ignore-start */
    /** @jsxRuntime classic */
    /** @jsx createPlasmicElementProxy */
    /** @jsxFrag React.Fragment */
    // This class is auto-generated by Plasmic; please do not edit!
    // Plasmic Project: cB98qoa8i3odyeQmSRqxXv
    // Component: 8QN9vThq_d
    // plasmic-unformatted
    import * as React from "react";
    
    import * as p from  "@plasmicapp/react-web";
    import {hasVariant, classNames, wrapWithClassName, createPlasmicElementProxy, makeFragment, MultiChoiceArg, SingleBooleanChoiceArg, SingleChoiceArg, pick, omit, useTrigger, StrictProps, deriveRenderOpts, ensureGlobalVariants} from "@plasmicapp/react-web";
    
    
    
    import "@plasmicapp/react-web/lib/plasmic.css";
    import  "./plasmic__default_style.css"; // plasmic-import: global/defaultcss
    import  "./plasmic_final_not_exported.css"; // plasmic-import: cB98qoa8i3odyeQmSRqxXv/projectcss
    import  "./PlasmicBox.css" // plasmic-import: 8QN9vThq_d/css
  
    
    

    
    export type PlasmicBox__VariantMembers = {
      
    };
    export type PlasmicBox__VariantsArgs = {};
    type VariantPropType = keyof PlasmicBox__VariantsArgs;
    export const PlasmicBox__VariantProps = new Array<VariantPropType>();
  

    
    export type PlasmicBox__ArgsType = {};
    type ArgPropType = keyof PlasmicBox__ArgsType;
    export const PlasmicBox__ArgProps = new Array<ArgPropType>();
  

    export type PlasmicBox__OverridesType = {
    root?: p.Flex<"div">;
  };

    
    export interface DefaultBoxProps {
      
      className?: string;
    }
  

    
    function PlasmicBox__RenderFunc(
      props: {
        variants: PlasmicBox__VariantsArgs,
        args: PlasmicBox__ArgsType
        overrides: PlasmicBox__OverridesType
        forNode?: string
      }
    ) {
      const {variants, args, overrides, forNode} = props;

      
      
      return (
        
  <div
    
    data-plasmic-name={"root"}
    data-plasmic-override={overrides.root}
    data-plasmic-root={true}
    data-plasmic-for-node={forNode}
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "root_reset_cB98qoa8i3odyeQmSRqxXv", "Box__root__yXpMy")}
    
    />
  
      ) as React.ReactElement | null;
    }

    
    const PlasmicDescendants = {
      root: ["root"],
    } as const;
    type NodeNameType = keyof typeof PlasmicDescendants;
    type DescendantsType<T extends NodeNameType> = (typeof PlasmicDescendants)[T][number];
    type NodeDefaultElementType = {
      root: "div"
    };
  

    
    type ReservedPropsType = "variants" | "args" | "overrides";
    type NodeOverridesType<T extends NodeNameType> = Pick<PlasmicBox__OverridesType, DescendantsType<T>>;
    type NodeComponentProps<T extends NodeNameType> = (
      // Explicitly specify variants, args, and overrides as objects
      & {
        variants?: PlasmicBox__VariantsArgs;
        args?: PlasmicBox__ArgsType;
        overrides?: NodeOverridesType<T>;
      }
      // Specify variants directly as props
      & Omit<PlasmicBox__VariantsArgs, ReservedPropsType>
      // Specify args directly as props
      & Omit<PlasmicBox__ArgsType, ReservedPropsType>
      // Specify overrides for each element directly as props
      & Omit<NodeOverridesType<T>, ReservedPropsType | VariantPropType | ArgPropType>
      // Specify props for the root element
      & Omit<Partial<React.ComponentProps<NodeDefaultElementType[T]>>, ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>>
    );
    function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
      type PropsType = NodeComponentProps<NodeName> & {key?: React.Key};
      const func = function<T extends PropsType>(props: T & StrictProps<T, PropsType>) {
        const {variants, args, overrides} = deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicBox__ArgProps,
          internalVariantPropNames: PlasmicBox__VariantProps,
        });

        return PlasmicBox__RenderFunc({
          variants, args, overrides, forNode: nodeName
        });
      };
      if (nodeName === "root") {
        func.displayName = "PlasmicBox";
      } else {
        func.displayName = `PlasmicBox.${nodeName}`;
      }
      return func;
    }

    export const PlasmicBox = Object.assign(
      // Top-level PlasmicBox renders the root element
      makeNodeComponent("root"),
      {
        // Helper components rendering sub-elements
        

        // Metadata about props expected for PlasmicBox
        internalVariantProps: PlasmicBox__VariantProps,
        internalArgProps: PlasmicBox__ArgProps,
      }
    );
  

    export default PlasmicBox;
    /* prettier-ignore-end */
  