
    // @ts-nocheck
    /* eslint-disable */
    /* tslint:disable */
    /* prettier-ignore-start */
    /** @jsxRuntime classic */
    /** @jsx createPlasmicElementProxy */
    /** @jsxFrag React.Fragment */
    // This class is auto-generated by Plasmic; please do not edit!
    // Plasmic Project: cB98qoa8i3odyeQmSRqxXv
    // Component: 0Ji4ThxiGlwdl
    // plasmic-unformatted
    import * as React from "react";
    
    import * as p from  "@plasmicapp/react-web";
    import {hasVariant, classNames, wrapWithClassName, createPlasmicElementProxy, makeFragment, MultiChoiceArg, SingleBooleanChoiceArg, SingleChoiceArg, pick, omit, useTrigger, StrictProps, deriveRenderOpts, ensureGlobalVariants} from "@plasmicapp/react-web";
    
    
    
    import "@plasmicapp/react-web/lib/plasmic.css";
    import  "./plasmic__default_style.css"; // plasmic-import: global/defaultcss
    import  "./plasmic_final_not_exported.css"; // plasmic-import: cB98qoa8i3odyeQmSRqxXv/projectcss
    import  "./PlasmicAvatar.css" // plasmic-import: 0Ji4ThxiGlwdl/css
  
    
    

    
    export type PlasmicAvatar__VariantMembers = {
      
    };
    export type PlasmicAvatar__VariantsArgs = {};
    type VariantPropType = keyof PlasmicAvatar__VariantsArgs;
    export const PlasmicAvatar__VariantProps = new Array<VariantPropType>();
  

    
    export type PlasmicAvatar__ArgsType = {
    pic?: React.ReactNode
  };
    type ArgPropType = keyof PlasmicAvatar__ArgsType;
    export const PlasmicAvatar__ArgProps = new Array<ArgPropType>("pic");
  

    export type PlasmicAvatar__OverridesType = {
    root?: p.Flex<"div">;
img?: p.Flex<"img">;
  };

    
    export interface DefaultAvatarProps {
      pic?: React.ReactNode
      className?: string;
    }
  

    
    function PlasmicAvatar__RenderFunc(
      props: {
        variants: PlasmicAvatar__VariantsArgs,
        args: PlasmicAvatar__ArgsType
        overrides: PlasmicAvatar__OverridesType
        forNode?: string
      }
    ) {
      const {variants, args, overrides, forNode} = props;

      
      
      return (
        
  <div
    
    data-plasmic-name={"root"}
    data-plasmic-override={overrides.root}
    data-plasmic-root={true}
    data-plasmic-for-node={forNode}
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "root_reset_cB98qoa8i3odyeQmSRqxXv", "Avatar__root__oBtKc")}
    
    >
          <p.PlasmicSlot
      defaultContents={
  <img
    
    data-plasmic-name={"img"}
    data-plasmic-override={overrides.img}
    
    
    
    alt={""}
className={classNames("plasmic_default__all", "plasmic_default__img", "Avatar__img__lwgao")}
role={"img"}
src={"Plasmic_Image_VzNGPO9M8sAca__Ref"}
    
    />
  }
      value={args.pic}
       />
        </div>
  
      ) as React.ReactElement | null;
    }

    
    const PlasmicDescendants = {
      root: ["root", "img"],
img: ["img"],
    } as const;
    type NodeNameType = keyof typeof PlasmicDescendants;
    type DescendantsType<T extends NodeNameType> = (typeof PlasmicDescendants)[T][number];
    type NodeDefaultElementType = {
      root: "div";
img: "img"
    };
  

    
    type ReservedPropsType = "variants" | "args" | "overrides";
    type NodeOverridesType<T extends NodeNameType> = Pick<PlasmicAvatar__OverridesType, DescendantsType<T>>;
    type NodeComponentProps<T extends NodeNameType> = (
      // Explicitly specify variants, args, and overrides as objects
      & {
        variants?: PlasmicAvatar__VariantsArgs;
        args?: PlasmicAvatar__ArgsType;
        overrides?: NodeOverridesType<T>;
      }
      // Specify variants directly as props
      & Omit<PlasmicAvatar__VariantsArgs, ReservedPropsType>
      // Specify args directly as props
      & Omit<PlasmicAvatar__ArgsType, ReservedPropsType>
      // Specify overrides for each element directly as props
      & Omit<NodeOverridesType<T>, ReservedPropsType | VariantPropType | ArgPropType>
      // Specify props for the root element
      & Omit<Partial<React.ComponentProps<NodeDefaultElementType[T]>>, ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>>
    );
    function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
      type PropsType = NodeComponentProps<NodeName> & {key?: React.Key};
      const func = function<T extends PropsType>(props: T & StrictProps<T, PropsType>) {
        const {variants, args, overrides} = deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicAvatar__ArgProps,
          internalVariantPropNames: PlasmicAvatar__VariantProps,
        });

        return PlasmicAvatar__RenderFunc({
          variants, args, overrides, forNode: nodeName
        });
      };
      if (nodeName === "root") {
        func.displayName = "PlasmicAvatar";
      } else {
        func.displayName = `PlasmicAvatar.${nodeName}`;
      }
      return func;
    }

    export const PlasmicAvatar = Object.assign(
      // Top-level PlasmicAvatar renders the root element
      makeNodeComponent("root"),
      {
        // Helper components rendering sub-elements
        img: makeNodeComponent("img"),

        // Metadata about props expected for PlasmicAvatar
        internalVariantProps: PlasmicAvatar__VariantProps,
        internalArgProps: PlasmicAvatar__ArgProps,
      }
    );
  

    export default PlasmicAvatar;
    /* prettier-ignore-end */
  