
    // @ts-nocheck
    /* eslint-disable */
    /* tslint:disable */
    /* prettier-ignore-start */
    /** @jsxRuntime classic */
    /** @jsx createPlasmicElementProxy */
    /** @jsxFrag React.Fragment */
    // This class is auto-generated by Plasmic; please do not edit!
    // Plasmic Project: cB98qoa8i3odyeQmSRqxXv
    // Component: EP8K9-aLBP
    // plasmic-unformatted
    import * as React from "react";
    
    import * as p from  "@plasmicapp/react-web";
    import {hasVariant, classNames, wrapWithClassName, createPlasmicElementProxy, makeFragment, MultiChoiceArg, SingleBooleanChoiceArg, SingleChoiceArg, pick, omit, useTrigger, StrictProps, deriveRenderOpts, ensureGlobalVariants} from "@plasmicapp/react-web";
    import Header2 from "..//Header2";  // plasmic-import: VzjRiKj8lhN/component
import Features2 from "..//Features2";  // plasmic-import: vajCZel_JAG/component
import Table2 from "..//Table2";  // plasmic-import: uyExJbZ7mqv6/component
import Footer from "..//Footer";  // plasmic-import: n6U105Bf0n-C/component
    
    
    import "@plasmicapp/react-web/lib/plasmic.css";
    import  "./plasmic__default_style.css"; // plasmic-import: global/defaultcss
    import  "./plasmic_final_not_exported.css"; // plasmic-import: cB98qoa8i3odyeQmSRqxXv/projectcss
    import  "./PlasmicHomepage2.css" // plasmic-import: EP8K9-aLBP/css
  
    
    

    
    export type PlasmicHomepage2__VariantMembers = {
      
    };
    export type PlasmicHomepage2__VariantsArgs = {};
    type VariantPropType = keyof PlasmicHomepage2__VariantsArgs;
    export const PlasmicHomepage2__VariantProps = new Array<VariantPropType>();
  

    
    export type PlasmicHomepage2__ArgsType = {};
    type ArgPropType = keyof PlasmicHomepage2__ArgsType;
    export const PlasmicHomepage2__ArgProps = new Array<ArgPropType>();
  

    export type PlasmicHomepage2__OverridesType = {
    root?: p.Flex<"div">;
header2?: p.Flex<typeof Header2>;
features2?: p.Flex<typeof Features2>;
table2?: p.Flex<typeof Table2>;
footer?: p.Flex<typeof Footer>;
  };

    
    export interface DefaultHomepage2Props {
      
      className?: string;
    }
  

    
    function PlasmicHomepage2__RenderFunc(
      props: {
        variants: PlasmicHomepage2__VariantsArgs,
        args: PlasmicHomepage2__ArgsType
        overrides: PlasmicHomepage2__OverridesType
        forNode?: string
      }
    ) {
      const {variants, args, overrides, forNode} = props;

      
      
      return (
        
  <div
    
    data-plasmic-name={"root"}
    data-plasmic-override={overrides.root}
    data-plasmic-root={true}
    data-plasmic-for-node={forNode}
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "root_reset_cB98qoa8i3odyeQmSRqxXv", "Homepage2__root__dzVt")}
    
    >
          
  <Header2
    
    data-plasmic-name={"header2"}
    data-plasmic-override={overrides.header2}
    
    
    
    className={classNames("__wab_instance", "Homepage2__header2__mwlUn")}
    
    />
  

  <Features2
    
    data-plasmic-name={"features2"}
    data-plasmic-override={overrides.features2}
    
    
    
    className={classNames("__wab_instance", "Homepage2__features2__hnVal")}
    
    />
  

  <Table2
    
    data-plasmic-name={"table2"}
    data-plasmic-override={overrides.table2}
    
    
    
    className={classNames("__wab_instance", "Homepage2__table2__zgrXm")}
    
    />
  

  <Footer
    
    data-plasmic-name={"footer"}
    data-plasmic-override={overrides.footer}
    
    
    
    className={classNames("__wab_instance", "Homepage2__footer__wkIdB")}
    
    />
  
        </div>
  
      ) as React.ReactElement | null;
    }

    
    const PlasmicDescendants = {
      root: ["root", "header2", "features2", "table2", "footer"],
header2: ["header2"],
features2: ["features2"],
table2: ["table2"],
footer: ["footer"],
    } as const;
    type NodeNameType = keyof typeof PlasmicDescendants;
    type DescendantsType<T extends NodeNameType> = (typeof PlasmicDescendants)[T][number];
    type NodeDefaultElementType = {
      root: "div";
header2: typeof Header2;
features2: typeof Features2;
table2: typeof Table2;
footer: typeof Footer
    };
  

    
    type ReservedPropsType = "variants" | "args" | "overrides";
    type NodeOverridesType<T extends NodeNameType> = Pick<PlasmicHomepage2__OverridesType, DescendantsType<T>>;
    type NodeComponentProps<T extends NodeNameType> = (
      // Explicitly specify variants, args, and overrides as objects
      & {
        variants?: PlasmicHomepage2__VariantsArgs;
        args?: PlasmicHomepage2__ArgsType;
        overrides?: NodeOverridesType<T>;
      }
      // Specify variants directly as props
      & Omit<PlasmicHomepage2__VariantsArgs, ReservedPropsType>
      // Specify args directly as props
      & Omit<PlasmicHomepage2__ArgsType, ReservedPropsType>
      // Specify overrides for each element directly as props
      & Omit<NodeOverridesType<T>, ReservedPropsType | VariantPropType | ArgPropType>
      // Specify props for the root element
      & Omit<Partial<React.ComponentProps<NodeDefaultElementType[T]>>, ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>>
    );
    function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
      type PropsType = NodeComponentProps<NodeName> & {key?: React.Key};
      const func = function<T extends PropsType>(props: T & StrictProps<T, PropsType>) {
        const {variants, args, overrides} = deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHomepage2__ArgProps,
          internalVariantPropNames: PlasmicHomepage2__VariantProps,
        });

        return PlasmicHomepage2__RenderFunc({
          variants, args, overrides, forNode: nodeName
        });
      };
      if (nodeName === "root") {
        func.displayName = "PlasmicHomepage2";
      } else {
        func.displayName = `PlasmicHomepage2.${nodeName}`;
      }
      return func;
    }

    export const PlasmicHomepage2 = Object.assign(
      // Top-level PlasmicHomepage2 renders the root element
      makeNodeComponent("root"),
      {
        // Helper components rendering sub-elements
        header2: makeNodeComponent("header2"),
features2: makeNodeComponent("features2"),
table2: makeNodeComponent("table2"),
footer: makeNodeComponent("footer"),

        // Metadata about props expected for PlasmicHomepage2
        internalVariantProps: PlasmicHomepage2__VariantProps,
        internalArgProps: PlasmicHomepage2__ArgProps,
      }
    );
  

    export default PlasmicHomepage2;
    /* prettier-ignore-end */
  