
    // @ts-nocheck
    /* eslint-disable */
    /* tslint:disable */
    /* prettier-ignore-start */
    /** @jsxRuntime classic */
    /** @jsx createPlasmicElementProxy */
    /** @jsxFrag React.Fragment */
    // This class is auto-generated by Plasmic; please do not edit!
    // Plasmic Project: cB98qoa8i3odyeQmSRqxXv
    // Component: Nm2hEkjzPN
    // plasmic-unformatted
    import * as React from "react";
    
    import * as p from  "@plasmicapp/react-web";
    import {hasVariant, classNames, wrapWithClassName, createPlasmicElementProxy, makeFragment, MultiChoiceArg, SingleBooleanChoiceArg, SingleChoiceArg, pick, omit, useTrigger, StrictProps, deriveRenderOpts, ensureGlobalVariants} from "@plasmicapp/react-web";
    import Header2 from "..//Header2";  // plasmic-import: VzjRiKj8lhN/component
import Features2 from "..//Features2";  // plasmic-import: vajCZel_JAG/component
import Table2 from "..//Table2";  // plasmic-import: uyExJbZ7mqv6/component
import Footer from "..//Footer";  // plasmic-import: n6U105Bf0n-C/component
    
    
    import "@plasmicapp/react-web/lib/plasmic.css";
    import  "./plasmic__default_style.css"; // plasmic-import: global/defaultcss
    import  "./plasmic_final_not_exported.css"; // plasmic-import: cB98qoa8i3odyeQmSRqxXv/projectcss
    import  "./PlasmicHomepageFinal.css" // plasmic-import: Nm2hEkjzPN/css
  
    
    

    
    export type PlasmicHomepageFinal__VariantMembers = {
      
    };
    export type PlasmicHomepageFinal__VariantsArgs = {};
    type VariantPropType = keyof PlasmicHomepageFinal__VariantsArgs;
    export const PlasmicHomepageFinal__VariantProps = new Array<VariantPropType>();
  

    
    export type PlasmicHomepageFinal__ArgsType = {};
    type ArgPropType = keyof PlasmicHomepageFinal__ArgsType;
    export const PlasmicHomepageFinal__ArgProps = new Array<ArgPropType>();
  

    export type PlasmicHomepageFinal__OverridesType = {
    root?: p.Flex<"div">;
box?: p.Flex<"div">;
header2?: p.Flex<typeof Header2>;
features2?: p.Flex<typeof Features2>;
table2?: p.Flex<typeof Table2>;
footer?: p.Flex<typeof Footer>;
  };

    
    export interface DefaultHomepageFinalProps {
      
      className?: string;
    }
  

    
    function PlasmicHomepageFinal__RenderFunc(
      props: {
        variants: PlasmicHomepageFinal__VariantsArgs,
        args: PlasmicHomepageFinal__ArgsType
        overrides: PlasmicHomepageFinal__OverridesType
        forNode?: string
      }
    ) {
      const {variants, args, overrides, forNode} = props;

      
      
      return (
        <React.Fragment>
    
    
    
      <div className={"plasmic_page_wrapper"}>
        
  <div
    
    data-plasmic-name={"root"}
    data-plasmic-override={overrides.root}
    data-plasmic-root={true}
    data-plasmic-for-node={forNode}
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "root_reset_cB98qoa8i3odyeQmSRqxXv", "HomepageFinal__root__vvV8P")}
    
    >
          
  <div
    
    data-plasmic-name={"box"}
    data-plasmic-override={overrides.box}
    
    
    
    className={classNames("plasmic_default__all", "plasmic_default__div", "HomepageFinal__box__ei5Wh")}
    
    >
          
  <Header2
    
    data-plasmic-name={"header2"}
    data-plasmic-override={overrides.header2}
    
    
    
    className={classNames("__wab_instance", "HomepageFinal__header2__x1Lm3")}
    
    />
  

  <Features2
    
    data-plasmic-name={"features2"}
    data-plasmic-override={overrides.features2}
    
    
    
    className={classNames("__wab_instance", "HomepageFinal__features2___8Qfoq")}
    
    />
  

  <Table2
    
    data-plasmic-name={"table2"}
    data-plasmic-override={overrides.table2}
    
    
    
    className={classNames("__wab_instance", "HomepageFinal__table2__g8Rs0")}
    
    />
  

  <Footer
    
    data-plasmic-name={"footer"}
    data-plasmic-override={overrides.footer}
    
    
    
    className={classNames("__wab_instance", "HomepageFinal__footer__tx10")}
    
    />
  
        </div>
  
        </div>
  
      </div>
    
  </React.Fragment>
      ) as React.ReactElement | null;
    }

    
    const PlasmicDescendants = {
      root: ["root", "box", "header2", "features2", "table2", "footer"],
box: ["box", "header2", "features2", "table2", "footer"],
header2: ["header2"],
features2: ["features2"],
table2: ["table2"],
footer: ["footer"],
    } as const;
    type NodeNameType = keyof typeof PlasmicDescendants;
    type DescendantsType<T extends NodeNameType> = (typeof PlasmicDescendants)[T][number];
    type NodeDefaultElementType = {
      root: "div";
box: "div";
header2: typeof Header2;
features2: typeof Features2;
table2: typeof Table2;
footer: typeof Footer
    };
  

    
    type ReservedPropsType = "variants" | "args" | "overrides";
    type NodeOverridesType<T extends NodeNameType> = Pick<PlasmicHomepageFinal__OverridesType, DescendantsType<T>>;
    type NodeComponentProps<T extends NodeNameType> = (
      // Explicitly specify variants, args, and overrides as objects
      & {
        variants?: PlasmicHomepageFinal__VariantsArgs;
        args?: PlasmicHomepageFinal__ArgsType;
        overrides?: NodeOverridesType<T>;
      }
      // Specify variants directly as props
      & Omit<PlasmicHomepageFinal__VariantsArgs, ReservedPropsType>
      // Specify args directly as props
      & Omit<PlasmicHomepageFinal__ArgsType, ReservedPropsType>
      // Specify overrides for each element directly as props
      & Omit<NodeOverridesType<T>, ReservedPropsType | VariantPropType | ArgPropType>
      // Specify props for the root element
      & Omit<Partial<React.ComponentProps<NodeDefaultElementType[T]>>, ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>>
    );
    function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
      type PropsType = NodeComponentProps<NodeName> & {key?: React.Key};
      const func = function<T extends PropsType>(props: T & StrictProps<T, PropsType>) {
        const {variants, args, overrides} = deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHomepageFinal__ArgProps,
          internalVariantPropNames: PlasmicHomepageFinal__VariantProps,
        });

        return PlasmicHomepageFinal__RenderFunc({
          variants, args, overrides, forNode: nodeName
        });
      };
      if (nodeName === "root") {
        func.displayName = "PlasmicHomepageFinal";
      } else {
        func.displayName = `PlasmicHomepageFinal.${nodeName}`;
      }
      return func;
    }

    export const PlasmicHomepageFinal = Object.assign(
      // Top-level PlasmicHomepageFinal renders the root element
      makeNodeComponent("root"),
      {
        // Helper components rendering sub-elements
        box: makeNodeComponent("box"),
header2: makeNodeComponent("header2"),
features2: makeNodeComponent("features2"),
table2: makeNodeComponent("table2"),
footer: makeNodeComponent("footer"),

        // Metadata about props expected for PlasmicHomepageFinal
        internalVariantProps: PlasmicHomepageFinal__VariantProps,
        internalArgProps: PlasmicHomepageFinal__ArgProps,
      }
    );
  

    export default PlasmicHomepageFinal;
    /* prettier-ignore-end */
  