// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vT2hQ48dTqvVqB6oYdpEi1
// Component: w5OyoOXrVf
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import projectcss from "./plasmic_untitled_project.module.css"; // plasmic-import: vT2hQ48dTqvVqB6oYdpEi1/projectcss
import sty from "./PlasmicFooter.module.css"; // plasmic-import: w5OyoOXrVf/css

export const PlasmicFooter__VariantProps = new Array();

export const PlasmicFooter__ArgProps = new Array();

function PlasmicFooter__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div
        data-plasmic-name={"footerComponent"}
        data-plasmic-override={overrides.footerComponent}
        className={classNames(defaultcss.all, sty.footerComponent)}
      >
        <div
          data-plasmic-name={"rectangle"}
          data-plasmic-override={overrides.rectangle}
          className={classNames(defaultcss.all, sty.rectangle)}
        />

        <div
          data-plasmic-name={"frame"}
          data-plasmic-override={overrides.frame}
          className={classNames(defaultcss.all, sty.frame)}
        >
          <div
            data-plasmic-name={"rectangle2"}
            data-plasmic-override={overrides.rectangle2}
            className={classNames(defaultcss.all, sty.rectangle2)}
          />

          <div
            data-plasmic-name={"frame2"}
            data-plasmic-override={overrides.frame2}
            className={classNames(defaultcss.all, sty.frame2)}
          >
            <div
              data-plasmic-name={"rectangle3"}
              data-plasmic-override={overrides.rectangle3}
              className={classNames(defaultcss.all, sty.rectangle3)}
            />

            <div
              data-plasmic-name={"frame3"}
              data-plasmic-override={overrides.frame3}
              className={classNames(defaultcss.all, sty.frame3)}
            >
              <div
                data-plasmic-name={"rectangle4"}
                data-plasmic-override={overrides.rectangle4}
                className={classNames(defaultcss.all, sty.rectangle4)}
              />

              <div
                data-plasmic-name={"frame4"}
                data-plasmic-override={overrides.frame4}
                className={classNames(defaultcss.all, sty.frame4)}
              >
                <div
                  data-plasmic-name={"rectangle5"}
                  data-plasmic-override={overrides.rectangle5}
                  className={classNames(defaultcss.all, sty.rectangle5)}
                />

                <div
                  data-plasmic-name={"frame5"}
                  data-plasmic-override={overrides.frame5}
                  className={classNames(defaultcss.all, sty.frame5)}
                >
                  <div
                    data-plasmic-name={"rectangle6"}
                    data-plasmic-override={overrides.rectangle6}
                    className={classNames(defaultcss.all, sty.rectangle6)}
                  />

                  <div
                    data-plasmic-name={"frame6"}
                    data-plasmic-override={overrides.frame6}
                    className={classNames(defaultcss.all, sty.frame6)}
                  >
                    <div
                      data-plasmic-name={"rectangle7"}
                      data-plasmic-override={overrides.rectangle7}
                      className={classNames(defaultcss.all, sty.rectangle7)}
                    />

                    <div
                      data-plasmic-name={"frame7"}
                      data-plasmic-override={overrides.frame7}
                      className={classNames(defaultcss.all, sty.frame7)}
                    >
                      <div
                        data-plasmic-name={"rectangle8"}
                        data-plasmic-override={overrides.rectangle8}
                        className={classNames(defaultcss.all, sty.rectangle8)}
                      />

                      <div
                        data-plasmic-name={"frame8"}
                        data-plasmic-override={overrides.frame8}
                        className={classNames(defaultcss.all, sty.frame8)}
                      >
                        <div
                          data-plasmic-name={"rectangle9"}
                          data-plasmic-override={overrides.rectangle9}
                          className={classNames(defaultcss.all, sty.rectangle9)}
                        />

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box___8NMbV
                          )}
                        >
                          {"Pricing"}
                        </div>
                      </div>
                    </div>

                    <div
                      data-plasmic-name={"frame9"}
                      data-plasmic-override={overrides.frame9}
                      className={classNames(defaultcss.all, sty.frame9)}
                    >
                      <div
                        data-plasmic-name={"rectangle10"}
                        data-plasmic-override={overrides.rectangle10}
                        className={classNames(defaultcss.all, sty.rectangle10)}
                      />

                      <div
                        data-plasmic-name={"frame10"}
                        data-plasmic-override={overrides.frame10}
                        className={classNames(defaultcss.all, sty.frame10)}
                      >
                        <div
                          data-plasmic-name={"rectangle11"}
                          data-plasmic-override={overrides.rectangle11}
                          className={classNames(
                            defaultcss.all,
                            sty.rectangle11
                          )}
                        />

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__qsVc3
                          )}
                        >
                          {"Guides"}
                        </div>
                      </div>
                    </div>

                    <div
                      data-plasmic-name={"frame11"}
                      data-plasmic-override={overrides.frame11}
                      className={classNames(defaultcss.all, sty.frame11)}
                    >
                      <div
                        data-plasmic-name={"rectangle12"}
                        data-plasmic-override={overrides.rectangle12}
                        className={classNames(defaultcss.all, sty.rectangle12)}
                      />

                      <div
                        data-plasmic-name={"frame12"}
                        data-plasmic-override={overrides.frame12}
                        className={classNames(defaultcss.all, sty.frame12)}
                      >
                        <div
                          data-plasmic-name={"rectangle13"}
                          data-plasmic-override={overrides.rectangle13}
                          className={classNames(
                            defaultcss.all,
                            sty.rectangle13
                          )}
                        />
                      </div>
                    </div>

                    <div
                      data-plasmic-name={"frame13"}
                      data-plasmic-override={overrides.frame13}
                      className={classNames(defaultcss.all, sty.frame13)}
                    >
                      <div
                        data-plasmic-name={"rectangle14"}
                        data-plasmic-override={overrides.rectangle14}
                        className={classNames(defaultcss.all, sty.rectangle14)}
                      />

                      <div
                        data-plasmic-name={"frame14"}
                        data-plasmic-override={overrides.frame14}
                        className={classNames(defaultcss.all, sty.frame14)}
                      >
                        <div
                          data-plasmic-name={"rectangle15"}
                          data-plasmic-override={overrides.rectangle15}
                          className={classNames(
                            defaultcss.all,
                            sty.rectangle15
                          )}
                        />

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box___8UiG5
                          )}
                        >
                          {"Documentation"}
                        </div>
                      </div>
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"frame15"}
                    data-plasmic-override={overrides.frame15}
                    className={classNames(defaultcss.all, sty.frame15)}
                  >
                    <div
                      data-plasmic-name={"rectangle16"}
                      data-plasmic-override={overrides.rectangle16}
                      className={classNames(defaultcss.all, sty.rectangle16)}
                    />

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__u6Cnu
                      )}
                    >
                      {"Support"}
                    </div>
                  </div>
                </div>

                <div
                  data-plasmic-name={"frame16"}
                  data-plasmic-override={overrides.frame16}
                  className={classNames(defaultcss.all, sty.frame16)}
                >
                  <div
                    data-plasmic-name={"rectangle17"}
                    data-plasmic-override={overrides.rectangle17}
                    className={classNames(defaultcss.all, sty.rectangle17)}
                  />

                  <div
                    data-plasmic-name={"frame17"}
                    data-plasmic-override={overrides.frame17}
                    className={classNames(defaultcss.all, sty.frame17)}
                  >
                    <div
                      data-plasmic-name={"rectangle18"}
                      data-plasmic-override={overrides.rectangle18}
                      className={classNames(defaultcss.all, sty.rectangle18)}
                    />

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__yPCh
                      )}
                    >
                      {"Solutions"}
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"frame18"}
                    data-plasmic-override={overrides.frame18}
                    className={classNames(defaultcss.all, sty.frame18)}
                  >
                    <div
                      data-plasmic-name={"rectangle19"}
                      data-plasmic-override={overrides.rectangle19}
                      className={classNames(defaultcss.all, sty.rectangle19)}
                    />

                    <div
                      data-plasmic-name={"frame19"}
                      data-plasmic-override={overrides.frame19}
                      className={classNames(defaultcss.all, sty.frame19)}
                    >
                      <div
                        data-plasmic-name={"rectangle20"}
                        data-plasmic-override={overrides.rectangle20}
                        className={classNames(defaultcss.all, sty.rectangle20)}
                      />

                      <div
                        data-plasmic-name={"frame20"}
                        data-plasmic-override={overrides.frame20}
                        className={classNames(defaultcss.all, sty.frame20)}
                      >
                        <div
                          data-plasmic-name={"rectangle21"}
                          data-plasmic-override={overrides.rectangle21}
                          className={classNames(
                            defaultcss.all,
                            sty.rectangle21
                          )}
                        />

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__mtyqw
                          )}
                        >
                          {"Hardware"}
                        </div>
                      </div>
                    </div>

                    <div
                      data-plasmic-name={"frame21"}
                      data-plasmic-override={overrides.frame21}
                      className={classNames(defaultcss.all, sty.frame21)}
                    >
                      <div
                        data-plasmic-name={"rectangle22"}
                        data-plasmic-override={overrides.rectangle22}
                        className={classNames(defaultcss.all, sty.rectangle22)}
                      />

                      <div
                        data-plasmic-name={"frame22"}
                        data-plasmic-override={overrides.frame22}
                        className={classNames(defaultcss.all, sty.frame22)}
                      >
                        <div
                          data-plasmic-name={"rectangle23"}
                          data-plasmic-override={overrides.rectangle23}
                          className={classNames(
                            defaultcss.all,
                            sty.rectangle23
                          )}
                        />

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box___69KIv
                          )}
                        >
                          {"Software"}
                        </div>
                      </div>
                    </div>

                    <div
                      data-plasmic-name={"frame23"}
                      data-plasmic-override={overrides.frame23}
                      className={classNames(defaultcss.all, sty.frame23)}
                    >
                      <div
                        data-plasmic-name={"rectangle24"}
                        data-plasmic-override={overrides.rectangle24}
                        className={classNames(defaultcss.all, sty.rectangle24)}
                      />

                      <div
                        data-plasmic-name={"frame24"}
                        data-plasmic-override={overrides.frame24}
                        className={classNames(defaultcss.all, sty.frame24)}
                      >
                        <div
                          data-plasmic-name={"rectangle25"}
                          data-plasmic-override={overrides.rectangle25}
                          className={classNames(
                            defaultcss.all,
                            sty.rectangle25
                          )}
                        />

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__gbVjZ
                          )}
                        >
                          {"Analytics"}
                        </div>
                      </div>
                    </div>

                    <div
                      data-plasmic-name={"frame25"}
                      data-plasmic-override={overrides.frame25}
                      className={classNames(defaultcss.all, sty.frame25)}
                    >
                      <div
                        data-plasmic-name={"rectangle26"}
                        data-plasmic-override={overrides.rectangle26}
                        className={classNames(defaultcss.all, sty.rectangle26)}
                      />

                      <div
                        data-plasmic-name={"frame26"}
                        data-plasmic-override={overrides.frame26}
                        className={classNames(defaultcss.all, sty.frame26)}
                      >
                        <div
                          data-plasmic-name={"rectangle27"}
                          data-plasmic-override={overrides.rectangle27}
                          className={classNames(
                            defaultcss.all,
                            sty.rectangle27
                          )}
                        />
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div
                data-plasmic-name={"frame27"}
                data-plasmic-override={overrides.frame27}
                className={classNames(defaultcss.all, sty.frame27)}
              >
                <div
                  data-plasmic-name={"rectangle28"}
                  data-plasmic-override={overrides.rectangle28}
                  className={classNames(defaultcss.all, sty.rectangle28)}
                />

                <div
                  data-plasmic-name={"frame28"}
                  data-plasmic-override={overrides.frame28}
                  className={classNames(defaultcss.all, sty.frame28)}
                >
                  <div
                    data-plasmic-name={"rectangle29"}
                    data-plasmic-override={overrides.rectangle29}
                    className={classNames(defaultcss.all, sty.rectangle29)}
                  />

                  <div
                    data-plasmic-name={"frame29"}
                    data-plasmic-override={overrides.frame29}
                    className={classNames(defaultcss.all, sty.frame29)}
                  >
                    <div
                      data-plasmic-name={"rectangle30"}
                      data-plasmic-override={overrides.rectangle30}
                      className={classNames(defaultcss.all, sty.rectangle30)}
                    />

                    <div
                      data-plasmic-name={"frame30"}
                      data-plasmic-override={overrides.frame30}
                      className={classNames(defaultcss.all, sty.frame30)}
                    >
                      <div
                        data-plasmic-name={"rectangle31"}
                        data-plasmic-override={overrides.rectangle31}
                        className={classNames(defaultcss.all, sty.rectangle31)}
                      />

                      <div
                        data-plasmic-name={"frame31"}
                        data-plasmic-override={overrides.frame31}
                        className={classNames(defaultcss.all, sty.frame31)}
                      >
                        <div
                          data-plasmic-name={"rectangle32"}
                          data-plasmic-override={overrides.rectangle32}
                          className={classNames(
                            defaultcss.all,
                            sty.rectangle32
                          )}
                        />

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__g4X6C
                          )}
                        >
                          {"About"}
                        </div>
                      </div>
                    </div>

                    <div
                      data-plasmic-name={"frame32"}
                      data-plasmic-override={overrides.frame32}
                      className={classNames(defaultcss.all, sty.frame32)}
                    >
                      <div
                        data-plasmic-name={"rectangle33"}
                        data-plasmic-override={overrides.rectangle33}
                        className={classNames(defaultcss.all, sty.rectangle33)}
                      />

                      <div
                        data-plasmic-name={"frame33"}
                        data-plasmic-override={overrides.frame33}
                        className={classNames(defaultcss.all, sty.frame33)}
                      >
                        <div
                          data-plasmic-name={"rectangle34"}
                          data-plasmic-override={overrides.rectangle34}
                          className={classNames(
                            defaultcss.all,
                            sty.rectangle34
                          )}
                        />

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__bWa
                          )}
                        >
                          {"Jobs"}
                        </div>
                      </div>
                    </div>

                    <div
                      data-plasmic-name={"frame34"}
                      data-plasmic-override={overrides.frame34}
                      className={classNames(defaultcss.all, sty.frame34)}
                    >
                      <div
                        data-plasmic-name={"rectangle35"}
                        data-plasmic-override={overrides.rectangle35}
                        className={classNames(defaultcss.all, sty.rectangle35)}
                      />

                      <div
                        data-plasmic-name={"frame35"}
                        data-plasmic-override={overrides.frame35}
                        className={classNames(defaultcss.all, sty.frame35)}
                      >
                        <div
                          data-plasmic-name={"rectangle36"}
                          data-plasmic-override={overrides.rectangle36}
                          className={classNames(
                            defaultcss.all,
                            sty.rectangle36
                          )}
                        />

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__boCl7
                          )}
                        >
                          {"Partners"}
                        </div>
                      </div>
                    </div>

                    <div
                      data-plasmic-name={"frame36"}
                      data-plasmic-override={overrides.frame36}
                      className={classNames(defaultcss.all, sty.frame36)}
                    >
                      <div
                        data-plasmic-name={"rectangle37"}
                        data-plasmic-override={overrides.rectangle37}
                        className={classNames(defaultcss.all, sty.rectangle37)}
                      />

                      <div
                        data-plasmic-name={"frame37"}
                        data-plasmic-override={overrides.frame37}
                        className={classNames(defaultcss.all, sty.frame37)}
                      >
                        <div
                          data-plasmic-name={"rectangle38"}
                          data-plasmic-override={overrides.rectangle38}
                          className={classNames(
                            defaultcss.all,
                            sty.rectangle38
                          )}
                        />

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__clnYs
                          )}
                        >
                          {"News"}
                        </div>
                      </div>
                    </div>

                    <div
                      data-plasmic-name={"frame38"}
                      data-plasmic-override={overrides.frame38}
                      className={classNames(defaultcss.all, sty.frame38)}
                    >
                      <div
                        data-plasmic-name={"rectangle39"}
                        data-plasmic-override={overrides.rectangle39}
                        className={classNames(defaultcss.all, sty.rectangle39)}
                      />

                      <div
                        data-plasmic-name={"frame39"}
                        data-plasmic-override={overrides.frame39}
                        className={classNames(defaultcss.all, sty.frame39)}
                      >
                        <div
                          data-plasmic-name={"rectangle40"}
                          data-plasmic-override={overrides.rectangle40}
                          className={classNames(
                            defaultcss.all,
                            sty.rectangle40
                          )}
                        />

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box___4ICjW
                          )}
                        >
                          {"Press"}
                        </div>
                      </div>
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"frame40"}
                    data-plasmic-override={overrides.frame40}
                    className={classNames(defaultcss.all, sty.frame40)}
                  >
                    <div
                      data-plasmic-name={"rectangle41"}
                      data-plasmic-override={overrides.rectangle41}
                      className={classNames(defaultcss.all, sty.rectangle41)}
                    />

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__qomzL
                      )}
                    >
                      {"Company"}
                    </div>
                  </div>
                </div>

                <div
                  data-plasmic-name={"frame41"}
                  data-plasmic-override={overrides.frame41}
                  className={classNames(defaultcss.all, sty.frame41)}
                >
                  <div
                    data-plasmic-name={"rectangle42"}
                    data-plasmic-override={overrides.rectangle42}
                    className={classNames(defaultcss.all, sty.rectangle42)}
                  />

                  <div
                    data-plasmic-name={"frame42"}
                    data-plasmic-override={overrides.frame42}
                    className={classNames(defaultcss.all, sty.frame42)}
                  >
                    <div
                      data-plasmic-name={"rectangle43"}
                      data-plasmic-override={overrides.rectangle43}
                      className={classNames(defaultcss.all, sty.rectangle43)}
                    />

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box___77RIr
                      )}
                    >
                      {"Legal"}
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"frame43"}
                    data-plasmic-override={overrides.frame43}
                    className={classNames(defaultcss.all, sty.frame43)}
                  >
                    <div
                      data-plasmic-name={"rectangle44"}
                      data-plasmic-override={overrides.rectangle44}
                      className={classNames(defaultcss.all, sty.rectangle44)}
                    />

                    <div
                      data-plasmic-name={"frame44"}
                      data-plasmic-override={overrides.frame44}
                      className={classNames(defaultcss.all, sty.frame44)}
                    >
                      <div
                        data-plasmic-name={"rectangle45"}
                        data-plasmic-override={overrides.rectangle45}
                        className={classNames(defaultcss.all, sty.rectangle45)}
                      />

                      <div
                        data-plasmic-name={"frame45"}
                        data-plasmic-override={overrides.frame45}
                        className={classNames(defaultcss.all, sty.frame45)}
                      >
                        <div
                          data-plasmic-name={"rectangle46"}
                          data-plasmic-override={overrides.rectangle46}
                          className={classNames(
                            defaultcss.all,
                            sty.rectangle46
                          )}
                        />

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__urBfj
                          )}
                        >
                          {"Privacy"}
                        </div>
                      </div>
                    </div>

                    <div
                      data-plasmic-name={"frame46"}
                      data-plasmic-override={overrides.frame46}
                      className={classNames(defaultcss.all, sty.frame46)}
                    >
                      <div
                        data-plasmic-name={"rectangle47"}
                        data-plasmic-override={overrides.rectangle47}
                        className={classNames(defaultcss.all, sty.rectangle47)}
                      />

                      <div
                        data-plasmic-name={"frame47"}
                        data-plasmic-override={overrides.frame47}
                        className={classNames(defaultcss.all, sty.frame47)}
                      >
                        <div
                          data-plasmic-name={"rectangle48"}
                          data-plasmic-override={overrides.rectangle48}
                          className={classNames(
                            defaultcss.all,
                            sty.rectangle48
                          )}
                        />

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box___6DEwl
                          )}
                        >
                          {"Terms"}
                        </div>
                      </div>
                    </div>

                    <div
                      data-plasmic-name={"frame48"}
                      data-plasmic-override={overrides.frame48}
                      className={classNames(defaultcss.all, sty.frame48)}
                    >
                      <div
                        data-plasmic-name={"rectangle49"}
                        data-plasmic-override={overrides.rectangle49}
                        className={classNames(defaultcss.all, sty.rectangle49)}
                      />

                      <div
                        data-plasmic-name={"frame49"}
                        data-plasmic-override={overrides.frame49}
                        className={classNames(defaultcss.all, sty.frame49)}
                      >
                        <div
                          data-plasmic-name={"rectangle50"}
                          data-plasmic-override={overrides.rectangle50}
                          className={classNames(
                            defaultcss.all,
                            sty.rectangle50
                          )}
                        />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div
            data-plasmic-name={"frame50"}
            data-plasmic-override={overrides.frame50}
            className={classNames(defaultcss.all, sty.frame50)}
          >
            <div
              data-plasmic-name={"rectangle51"}
              data-plasmic-override={overrides.rectangle51}
              className={classNames(defaultcss.all, sty.rectangle51)}
            />

            <div
              data-plasmic-name={"frame51"}
              data-plasmic-override={overrides.frame51}
              className={classNames(defaultcss.all, sty.frame51)}
            >
              <div
                data-plasmic-name={"rectangle52"}
                data-plasmic-override={overrides.rectangle52}
                className={classNames(defaultcss.all, sty.rectangle52)}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__q0Htq
                )}
              >
                {"© 2021 MobCycle, LLC. All rights reserved."}
              </div>
            </div>

            <div
              data-plasmic-name={"rectangle53"}
              data-plasmic-override={overrides.rectangle53}
              className={classNames(defaultcss.all, sty.rectangle53)}
            />
          </div>
        </div>
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "footerComponent",
    "rectangle",
    "frame",
    "rectangle2",
    "frame2",
    "rectangle3",
    "frame3",
    "rectangle4",
    "frame4",
    "rectangle5",
    "frame5",
    "rectangle6",
    "frame6",
    "rectangle7",
    "frame7",
    "rectangle8",
    "frame8",
    "rectangle9",
    "frame9",
    "rectangle10",
    "frame10",
    "rectangle11",
    "frame11",
    "rectangle12",
    "frame12",
    "rectangle13",
    "frame13",
    "rectangle14",
    "frame14",
    "rectangle15",
    "frame15",
    "rectangle16",
    "frame16",
    "rectangle17",
    "frame17",
    "rectangle18",
    "frame18",
    "rectangle19",
    "frame19",
    "rectangle20",
    "frame20",
    "rectangle21",
    "frame21",
    "rectangle22",
    "frame22",
    "rectangle23",
    "frame23",
    "rectangle24",
    "frame24",
    "rectangle25",
    "frame25",
    "rectangle26",
    "frame26",
    "rectangle27",
    "frame27",
    "rectangle28",
    "frame28",
    "rectangle29",
    "frame29",
    "rectangle30",
    "frame30",
    "rectangle31",
    "frame31",
    "rectangle32",
    "frame32",
    "rectangle33",
    "frame33",
    "rectangle34",
    "frame34",
    "rectangle35",
    "frame35",
    "rectangle36",
    "frame36",
    "rectangle37",
    "frame37",
    "rectangle38",
    "frame38",
    "rectangle39",
    "frame39",
    "rectangle40",
    "frame40",
    "rectangle41",
    "frame41",
    "rectangle42",
    "frame42",
    "rectangle43",
    "frame43",
    "rectangle44",
    "frame44",
    "rectangle45",
    "frame45",
    "rectangle46",
    "frame46",
    "rectangle47",
    "frame47",
    "rectangle48",
    "frame48",
    "rectangle49",
    "frame49",
    "rectangle50",
    "frame50",
    "rectangle51",
    "frame51",
    "rectangle52",
    "rectangle53"
  ],

  footerComponent: [
    "footerComponent",
    "rectangle",
    "frame",
    "rectangle2",
    "frame2",
    "rectangle3",
    "frame3",
    "rectangle4",
    "frame4",
    "rectangle5",
    "frame5",
    "rectangle6",
    "frame6",
    "rectangle7",
    "frame7",
    "rectangle8",
    "frame8",
    "rectangle9",
    "frame9",
    "rectangle10",
    "frame10",
    "rectangle11",
    "frame11",
    "rectangle12",
    "frame12",
    "rectangle13",
    "frame13",
    "rectangle14",
    "frame14",
    "rectangle15",
    "frame15",
    "rectangle16",
    "frame16",
    "rectangle17",
    "frame17",
    "rectangle18",
    "frame18",
    "rectangle19",
    "frame19",
    "rectangle20",
    "frame20",
    "rectangle21",
    "frame21",
    "rectangle22",
    "frame22",
    "rectangle23",
    "frame23",
    "rectangle24",
    "frame24",
    "rectangle25",
    "frame25",
    "rectangle26",
    "frame26",
    "rectangle27",
    "frame27",
    "rectangle28",
    "frame28",
    "rectangle29",
    "frame29",
    "rectangle30",
    "frame30",
    "rectangle31",
    "frame31",
    "rectangle32",
    "frame32",
    "rectangle33",
    "frame33",
    "rectangle34",
    "frame34",
    "rectangle35",
    "frame35",
    "rectangle36",
    "frame36",
    "rectangle37",
    "frame37",
    "rectangle38",
    "frame38",
    "rectangle39",
    "frame39",
    "rectangle40",
    "frame40",
    "rectangle41",
    "frame41",
    "rectangle42",
    "frame42",
    "rectangle43",
    "frame43",
    "rectangle44",
    "frame44",
    "rectangle45",
    "frame45",
    "rectangle46",
    "frame46",
    "rectangle47",
    "frame47",
    "rectangle48",
    "frame48",
    "rectangle49",
    "frame49",
    "rectangle50",
    "frame50",
    "rectangle51",
    "frame51",
    "rectangle52",
    "rectangle53"
  ],

  rectangle: ["rectangle"],
  frame: [
    "frame",
    "rectangle2",
    "frame2",
    "rectangle3",
    "frame3",
    "rectangle4",
    "frame4",
    "rectangle5",
    "frame5",
    "rectangle6",
    "frame6",
    "rectangle7",
    "frame7",
    "rectangle8",
    "frame8",
    "rectangle9",
    "frame9",
    "rectangle10",
    "frame10",
    "rectangle11",
    "frame11",
    "rectangle12",
    "frame12",
    "rectangle13",
    "frame13",
    "rectangle14",
    "frame14",
    "rectangle15",
    "frame15",
    "rectangle16",
    "frame16",
    "rectangle17",
    "frame17",
    "rectangle18",
    "frame18",
    "rectangle19",
    "frame19",
    "rectangle20",
    "frame20",
    "rectangle21",
    "frame21",
    "rectangle22",
    "frame22",
    "rectangle23",
    "frame23",
    "rectangle24",
    "frame24",
    "rectangle25",
    "frame25",
    "rectangle26",
    "frame26",
    "rectangle27",
    "frame27",
    "rectangle28",
    "frame28",
    "rectangle29",
    "frame29",
    "rectangle30",
    "frame30",
    "rectangle31",
    "frame31",
    "rectangle32",
    "frame32",
    "rectangle33",
    "frame33",
    "rectangle34",
    "frame34",
    "rectangle35",
    "frame35",
    "rectangle36",
    "frame36",
    "rectangle37",
    "frame37",
    "rectangle38",
    "frame38",
    "rectangle39",
    "frame39",
    "rectangle40",
    "frame40",
    "rectangle41",
    "frame41",
    "rectangle42",
    "frame42",
    "rectangle43",
    "frame43",
    "rectangle44",
    "frame44",
    "rectangle45",
    "frame45",
    "rectangle46",
    "frame46",
    "rectangle47",
    "frame47",
    "rectangle48",
    "frame48",
    "rectangle49",
    "frame49",
    "rectangle50",
    "frame50",
    "rectangle51",
    "frame51",
    "rectangle52",
    "rectangle53"
  ],

  rectangle2: ["rectangle2"],
  frame2: [
    "frame2",
    "rectangle3",
    "frame3",
    "rectangle4",
    "frame4",
    "rectangle5",
    "frame5",
    "rectangle6",
    "frame6",
    "rectangle7",
    "frame7",
    "rectangle8",
    "frame8",
    "rectangle9",
    "frame9",
    "rectangle10",
    "frame10",
    "rectangle11",
    "frame11",
    "rectangle12",
    "frame12",
    "rectangle13",
    "frame13",
    "rectangle14",
    "frame14",
    "rectangle15",
    "frame15",
    "rectangle16",
    "frame16",
    "rectangle17",
    "frame17",
    "rectangle18",
    "frame18",
    "rectangle19",
    "frame19",
    "rectangle20",
    "frame20",
    "rectangle21",
    "frame21",
    "rectangle22",
    "frame22",
    "rectangle23",
    "frame23",
    "rectangle24",
    "frame24",
    "rectangle25",
    "frame25",
    "rectangle26",
    "frame26",
    "rectangle27",
    "frame27",
    "rectangle28",
    "frame28",
    "rectangle29",
    "frame29",
    "rectangle30",
    "frame30",
    "rectangle31",
    "frame31",
    "rectangle32",
    "frame32",
    "rectangle33",
    "frame33",
    "rectangle34",
    "frame34",
    "rectangle35",
    "frame35",
    "rectangle36",
    "frame36",
    "rectangle37",
    "frame37",
    "rectangle38",
    "frame38",
    "rectangle39",
    "frame39",
    "rectangle40",
    "frame40",
    "rectangle41",
    "frame41",
    "rectangle42",
    "frame42",
    "rectangle43",
    "frame43",
    "rectangle44",
    "frame44",
    "rectangle45",
    "frame45",
    "rectangle46",
    "frame46",
    "rectangle47",
    "frame47",
    "rectangle48",
    "frame48",
    "rectangle49",
    "frame49",
    "rectangle50"
  ],

  rectangle3: ["rectangle3"],
  frame3: [
    "frame3",
    "rectangle4",
    "frame4",
    "rectangle5",
    "frame5",
    "rectangle6",
    "frame6",
    "rectangle7",
    "frame7",
    "rectangle8",
    "frame8",
    "rectangle9",
    "frame9",
    "rectangle10",
    "frame10",
    "rectangle11",
    "frame11",
    "rectangle12",
    "frame12",
    "rectangle13",
    "frame13",
    "rectangle14",
    "frame14",
    "rectangle15",
    "frame15",
    "rectangle16",
    "frame16",
    "rectangle17",
    "frame17",
    "rectangle18",
    "frame18",
    "rectangle19",
    "frame19",
    "rectangle20",
    "frame20",
    "rectangle21",
    "frame21",
    "rectangle22",
    "frame22",
    "rectangle23",
    "frame23",
    "rectangle24",
    "frame24",
    "rectangle25",
    "frame25",
    "rectangle26",
    "frame26",
    "rectangle27",
    "frame27",
    "rectangle28",
    "frame28",
    "rectangle29",
    "frame29",
    "rectangle30",
    "frame30",
    "rectangle31",
    "frame31",
    "rectangle32",
    "frame32",
    "rectangle33",
    "frame33",
    "rectangle34",
    "frame34",
    "rectangle35",
    "frame35",
    "rectangle36",
    "frame36",
    "rectangle37",
    "frame37",
    "rectangle38",
    "frame38",
    "rectangle39",
    "frame39",
    "rectangle40",
    "frame40",
    "rectangle41",
    "frame41",
    "rectangle42",
    "frame42",
    "rectangle43",
    "frame43",
    "rectangle44",
    "frame44",
    "rectangle45",
    "frame45",
    "rectangle46",
    "frame46",
    "rectangle47",
    "frame47",
    "rectangle48",
    "frame48",
    "rectangle49",
    "frame49",
    "rectangle50"
  ],

  rectangle4: ["rectangle4"],
  frame4: [
    "frame4",
    "rectangle5",
    "frame5",
    "rectangle6",
    "frame6",
    "rectangle7",
    "frame7",
    "rectangle8",
    "frame8",
    "rectangle9",
    "frame9",
    "rectangle10",
    "frame10",
    "rectangle11",
    "frame11",
    "rectangle12",
    "frame12",
    "rectangle13",
    "frame13",
    "rectangle14",
    "frame14",
    "rectangle15",
    "frame15",
    "rectangle16",
    "frame16",
    "rectangle17",
    "frame17",
    "rectangle18",
    "frame18",
    "rectangle19",
    "frame19",
    "rectangle20",
    "frame20",
    "rectangle21",
    "frame21",
    "rectangle22",
    "frame22",
    "rectangle23",
    "frame23",
    "rectangle24",
    "frame24",
    "rectangle25",
    "frame25",
    "rectangle26",
    "frame26",
    "rectangle27"
  ],

  rectangle5: ["rectangle5"],
  frame5: [
    "frame5",
    "rectangle6",
    "frame6",
    "rectangle7",
    "frame7",
    "rectangle8",
    "frame8",
    "rectangle9",
    "frame9",
    "rectangle10",
    "frame10",
    "rectangle11",
    "frame11",
    "rectangle12",
    "frame12",
    "rectangle13",
    "frame13",
    "rectangle14",
    "frame14",
    "rectangle15",
    "frame15",
    "rectangle16"
  ],

  rectangle6: ["rectangle6"],
  frame6: [
    "frame6",
    "rectangle7",
    "frame7",
    "rectangle8",
    "frame8",
    "rectangle9",
    "frame9",
    "rectangle10",
    "frame10",
    "rectangle11",
    "frame11",
    "rectangle12",
    "frame12",
    "rectangle13",
    "frame13",
    "rectangle14",
    "frame14",
    "rectangle15"
  ],

  rectangle7: ["rectangle7"],
  frame7: ["frame7", "rectangle8", "frame8", "rectangle9"],
  rectangle8: ["rectangle8"],
  frame8: ["frame8", "rectangle9"],
  rectangle9: ["rectangle9"],
  frame9: ["frame9", "rectangle10", "frame10", "rectangle11"],
  rectangle10: ["rectangle10"],
  frame10: ["frame10", "rectangle11"],
  rectangle11: ["rectangle11"],
  frame11: ["frame11", "rectangle12", "frame12", "rectangle13"],
  rectangle12: ["rectangle12"],
  frame12: ["frame12", "rectangle13"],
  rectangle13: ["rectangle13"],
  frame13: ["frame13", "rectangle14", "frame14", "rectangle15"],
  rectangle14: ["rectangle14"],
  frame14: ["frame14", "rectangle15"],
  rectangle15: ["rectangle15"],
  frame15: ["frame15", "rectangle16"],
  rectangle16: ["rectangle16"],
  frame16: [
    "frame16",
    "rectangle17",
    "frame17",
    "rectangle18",
    "frame18",
    "rectangle19",
    "frame19",
    "rectangle20",
    "frame20",
    "rectangle21",
    "frame21",
    "rectangle22",
    "frame22",
    "rectangle23",
    "frame23",
    "rectangle24",
    "frame24",
    "rectangle25",
    "frame25",
    "rectangle26",
    "frame26",
    "rectangle27"
  ],

  rectangle17: ["rectangle17"],
  frame17: ["frame17", "rectangle18"],
  rectangle18: ["rectangle18"],
  frame18: [
    "frame18",
    "rectangle19",
    "frame19",
    "rectangle20",
    "frame20",
    "rectangle21",
    "frame21",
    "rectangle22",
    "frame22",
    "rectangle23",
    "frame23",
    "rectangle24",
    "frame24",
    "rectangle25",
    "frame25",
    "rectangle26",
    "frame26",
    "rectangle27"
  ],

  rectangle19: ["rectangle19"],
  frame19: ["frame19", "rectangle20", "frame20", "rectangle21"],
  rectangle20: ["rectangle20"],
  frame20: ["frame20", "rectangle21"],
  rectangle21: ["rectangle21"],
  frame21: ["frame21", "rectangle22", "frame22", "rectangle23"],
  rectangle22: ["rectangle22"],
  frame22: ["frame22", "rectangle23"],
  rectangle23: ["rectangle23"],
  frame23: ["frame23", "rectangle24", "frame24", "rectangle25"],
  rectangle24: ["rectangle24"],
  frame24: ["frame24", "rectangle25"],
  rectangle25: ["rectangle25"],
  frame25: ["frame25", "rectangle26", "frame26", "rectangle27"],
  rectangle26: ["rectangle26"],
  frame26: ["frame26", "rectangle27"],
  rectangle27: ["rectangle27"],
  frame27: [
    "frame27",
    "rectangle28",
    "frame28",
    "rectangle29",
    "frame29",
    "rectangle30",
    "frame30",
    "rectangle31",
    "frame31",
    "rectangle32",
    "frame32",
    "rectangle33",
    "frame33",
    "rectangle34",
    "frame34",
    "rectangle35",
    "frame35",
    "rectangle36",
    "frame36",
    "rectangle37",
    "frame37",
    "rectangle38",
    "frame38",
    "rectangle39",
    "frame39",
    "rectangle40",
    "frame40",
    "rectangle41",
    "frame41",
    "rectangle42",
    "frame42",
    "rectangle43",
    "frame43",
    "rectangle44",
    "frame44",
    "rectangle45",
    "frame45",
    "rectangle46",
    "frame46",
    "rectangle47",
    "frame47",
    "rectangle48",
    "frame48",
    "rectangle49",
    "frame49",
    "rectangle50"
  ],

  rectangle28: ["rectangle28"],
  frame28: [
    "frame28",
    "rectangle29",
    "frame29",
    "rectangle30",
    "frame30",
    "rectangle31",
    "frame31",
    "rectangle32",
    "frame32",
    "rectangle33",
    "frame33",
    "rectangle34",
    "frame34",
    "rectangle35",
    "frame35",
    "rectangle36",
    "frame36",
    "rectangle37",
    "frame37",
    "rectangle38",
    "frame38",
    "rectangle39",
    "frame39",
    "rectangle40",
    "frame40",
    "rectangle41"
  ],

  rectangle29: ["rectangle29"],
  frame29: [
    "frame29",
    "rectangle30",
    "frame30",
    "rectangle31",
    "frame31",
    "rectangle32",
    "frame32",
    "rectangle33",
    "frame33",
    "rectangle34",
    "frame34",
    "rectangle35",
    "frame35",
    "rectangle36",
    "frame36",
    "rectangle37",
    "frame37",
    "rectangle38",
    "frame38",
    "rectangle39",
    "frame39",
    "rectangle40"
  ],

  rectangle30: ["rectangle30"],
  frame30: ["frame30", "rectangle31", "frame31", "rectangle32"],
  rectangle31: ["rectangle31"],
  frame31: ["frame31", "rectangle32"],
  rectangle32: ["rectangle32"],
  frame32: ["frame32", "rectangle33", "frame33", "rectangle34"],
  rectangle33: ["rectangle33"],
  frame33: ["frame33", "rectangle34"],
  rectangle34: ["rectangle34"],
  frame34: ["frame34", "rectangle35", "frame35", "rectangle36"],
  rectangle35: ["rectangle35"],
  frame35: ["frame35", "rectangle36"],
  rectangle36: ["rectangle36"],
  frame36: ["frame36", "rectangle37", "frame37", "rectangle38"],
  rectangle37: ["rectangle37"],
  frame37: ["frame37", "rectangle38"],
  rectangle38: ["rectangle38"],
  frame38: ["frame38", "rectangle39", "frame39", "rectangle40"],
  rectangle39: ["rectangle39"],
  frame39: ["frame39", "rectangle40"],
  rectangle40: ["rectangle40"],
  frame40: ["frame40", "rectangle41"],
  rectangle41: ["rectangle41"],
  frame41: [
    "frame41",
    "rectangle42",
    "frame42",
    "rectangle43",
    "frame43",
    "rectangle44",
    "frame44",
    "rectangle45",
    "frame45",
    "rectangle46",
    "frame46",
    "rectangle47",
    "frame47",
    "rectangle48",
    "frame48",
    "rectangle49",
    "frame49",
    "rectangle50"
  ],

  rectangle42: ["rectangle42"],
  frame42: ["frame42", "rectangle43"],
  rectangle43: ["rectangle43"],
  frame43: [
    "frame43",
    "rectangle44",
    "frame44",
    "rectangle45",
    "frame45",
    "rectangle46",
    "frame46",
    "rectangle47",
    "frame47",
    "rectangle48",
    "frame48",
    "rectangle49",
    "frame49",
    "rectangle50"
  ],

  rectangle44: ["rectangle44"],
  frame44: ["frame44", "rectangle45", "frame45", "rectangle46"],
  rectangle45: ["rectangle45"],
  frame45: ["frame45", "rectangle46"],
  rectangle46: ["rectangle46"],
  frame46: ["frame46", "rectangle47", "frame47", "rectangle48"],
  rectangle47: ["rectangle47"],
  frame47: ["frame47", "rectangle48"],
  rectangle48: ["rectangle48"],
  frame48: ["frame48", "rectangle49", "frame49", "rectangle50"],
  rectangle49: ["rectangle49"],
  frame49: ["frame49", "rectangle50"],
  rectangle50: ["rectangle50"],
  frame50: ["frame50", "rectangle51", "frame51", "rectangle52", "rectangle53"],
  rectangle51: ["rectangle51"],
  frame51: ["frame51", "rectangle52"],
  rectangle52: ["rectangle52"],
  rectangle53: ["rectangle53"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicFooter__ArgProps,
      internalVariantPropNames: PlasmicFooter__VariantProps
    });

    return PlasmicFooter__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFooter";
  } else {
    func.displayName = `PlasmicFooter.${nodeName}`;
  }
  return func;
}

export const PlasmicFooter = Object.assign(
  // Top-level PlasmicFooter renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    footerComponent: makeNodeComponent("footerComponent"),
    rectangle: makeNodeComponent("rectangle"),
    frame: makeNodeComponent("frame"),
    rectangle2: makeNodeComponent("rectangle2"),
    frame2: makeNodeComponent("frame2"),
    rectangle3: makeNodeComponent("rectangle3"),
    frame3: makeNodeComponent("frame3"),
    rectangle4: makeNodeComponent("rectangle4"),
    frame4: makeNodeComponent("frame4"),
    rectangle5: makeNodeComponent("rectangle5"),
    frame5: makeNodeComponent("frame5"),
    rectangle6: makeNodeComponent("rectangle6"),
    frame6: makeNodeComponent("frame6"),
    rectangle7: makeNodeComponent("rectangle7"),
    frame7: makeNodeComponent("frame7"),
    rectangle8: makeNodeComponent("rectangle8"),
    frame8: makeNodeComponent("frame8"),
    rectangle9: makeNodeComponent("rectangle9"),
    frame9: makeNodeComponent("frame9"),
    rectangle10: makeNodeComponent("rectangle10"),
    frame10: makeNodeComponent("frame10"),
    rectangle11: makeNodeComponent("rectangle11"),
    frame11: makeNodeComponent("frame11"),
    rectangle12: makeNodeComponent("rectangle12"),
    frame12: makeNodeComponent("frame12"),
    rectangle13: makeNodeComponent("rectangle13"),
    frame13: makeNodeComponent("frame13"),
    rectangle14: makeNodeComponent("rectangle14"),
    frame14: makeNodeComponent("frame14"),
    rectangle15: makeNodeComponent("rectangle15"),
    frame15: makeNodeComponent("frame15"),
    rectangle16: makeNodeComponent("rectangle16"),
    frame16: makeNodeComponent("frame16"),
    rectangle17: makeNodeComponent("rectangle17"),
    frame17: makeNodeComponent("frame17"),
    rectangle18: makeNodeComponent("rectangle18"),
    frame18: makeNodeComponent("frame18"),
    rectangle19: makeNodeComponent("rectangle19"),
    frame19: makeNodeComponent("frame19"),
    rectangle20: makeNodeComponent("rectangle20"),
    frame20: makeNodeComponent("frame20"),
    rectangle21: makeNodeComponent("rectangle21"),
    frame21: makeNodeComponent("frame21"),
    rectangle22: makeNodeComponent("rectangle22"),
    frame22: makeNodeComponent("frame22"),
    rectangle23: makeNodeComponent("rectangle23"),
    frame23: makeNodeComponent("frame23"),
    rectangle24: makeNodeComponent("rectangle24"),
    frame24: makeNodeComponent("frame24"),
    rectangle25: makeNodeComponent("rectangle25"),
    frame25: makeNodeComponent("frame25"),
    rectangle26: makeNodeComponent("rectangle26"),
    frame26: makeNodeComponent("frame26"),
    rectangle27: makeNodeComponent("rectangle27"),
    frame27: makeNodeComponent("frame27"),
    rectangle28: makeNodeComponent("rectangle28"),
    frame28: makeNodeComponent("frame28"),
    rectangle29: makeNodeComponent("rectangle29"),
    frame29: makeNodeComponent("frame29"),
    rectangle30: makeNodeComponent("rectangle30"),
    frame30: makeNodeComponent("frame30"),
    rectangle31: makeNodeComponent("rectangle31"),
    frame31: makeNodeComponent("frame31"),
    rectangle32: makeNodeComponent("rectangle32"),
    frame32: makeNodeComponent("frame32"),
    rectangle33: makeNodeComponent("rectangle33"),
    frame33: makeNodeComponent("frame33"),
    rectangle34: makeNodeComponent("rectangle34"),
    frame34: makeNodeComponent("frame34"),
    rectangle35: makeNodeComponent("rectangle35"),
    frame35: makeNodeComponent("frame35"),
    rectangle36: makeNodeComponent("rectangle36"),
    frame36: makeNodeComponent("frame36"),
    rectangle37: makeNodeComponent("rectangle37"),
    frame37: makeNodeComponent("frame37"),
    rectangle38: makeNodeComponent("rectangle38"),
    frame38: makeNodeComponent("frame38"),
    rectangle39: makeNodeComponent("rectangle39"),
    frame39: makeNodeComponent("frame39"),
    rectangle40: makeNodeComponent("rectangle40"),
    frame40: makeNodeComponent("frame40"),
    rectangle41: makeNodeComponent("rectangle41"),
    frame41: makeNodeComponent("frame41"),
    rectangle42: makeNodeComponent("rectangle42"),
    frame42: makeNodeComponent("frame42"),
    rectangle43: makeNodeComponent("rectangle43"),
    frame43: makeNodeComponent("frame43"),
    rectangle44: makeNodeComponent("rectangle44"),
    frame44: makeNodeComponent("frame44"),
    rectangle45: makeNodeComponent("rectangle45"),
    frame45: makeNodeComponent("frame45"),
    rectangle46: makeNodeComponent("rectangle46"),
    frame46: makeNodeComponent("frame46"),
    rectangle47: makeNodeComponent("rectangle47"),
    frame47: makeNodeComponent("frame47"),
    rectangle48: makeNodeComponent("rectangle48"),
    frame48: makeNodeComponent("frame48"),
    rectangle49: makeNodeComponent("rectangle49"),
    frame49: makeNodeComponent("frame49"),
    rectangle50: makeNodeComponent("rectangle50"),
    frame50: makeNodeComponent("frame50"),
    rectangle51: makeNodeComponent("rectangle51"),
    frame51: makeNodeComponent("frame51"),
    rectangle52: makeNodeComponent("rectangle52"),
    rectangle53: makeNodeComponent("rectangle53"),
    // Metadata about props expected for PlasmicFooter
    internalVariantProps: PlasmicFooter__VariantProps,
    internalArgProps: PlasmicFooter__ArgProps
  }
);

export default PlasmicFooter;
/* prettier-ignore-end */
