// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: cB98qoa8i3odyeQmSRqxXv
// Component: VzjRiKj8lhN
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_final_not_exported.module.css"; // plasmic-import: cB98qoa8i3odyeQmSRqxXv/projectcss
import * as sty from "./PlasmicHeader.module.css"; // plasmic-import: VzjRiKj8lhN/css
import _1526403428SvgIcon from "../mobicycle_usa/icons/PlasmicIcon___1526403428Svg"; // plasmic-import: xiqG2uIym/icon
import ChevronRightIcon from "./icons/PlasmicIcon__ChevronRight"; // plasmic-import: 57wGom1p3ud/icon

export const PlasmicHeader__VariantProps = new Array();

export const PlasmicHeader__ArgProps = new Array();

function PlasmicHeader__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"frame1Header"}
      data-plasmic-override={overrides.frame1Header}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        defaultcss.all,
        projectcss.root_reset,
        sty.frame1Header
      )}
    >
      <div
        data-plasmic-name={"header"}
        data-plasmic-override={overrides.header}
        className={classNames(defaultcss.all, sty.header)}
      >
        <div
          data-plasmic-name={"darkWithIllustrationDesktop"}
          data-plasmic-override={overrides.darkWithIllustrationDesktop}
          className={classNames(
            defaultcss.all,
            sty.darkWithIllustrationDesktop
          )}
        >
          <div
            data-plasmic-name={"navbar"}
            data-plasmic-override={overrides.navbar}
            className={classNames(defaultcss.all, sty.navbar)}
          >
            <div
              data-plasmic-name={"container"}
              data-plasmic-override={overrides.container}
              className={classNames(defaultcss.all, sty.container)}
            >
              <p.Stack
                as={"div"}
                data-plasmic-name={"content"}
                data-plasmic-override={overrides.content}
                hasGap={true}
                className={classNames(defaultcss.all, sty.content)}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"leadingContent"}
                  data-plasmic-override={overrides.leadingContent}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.leadingContent)}
                >
                  <_1526403428SvgIcon
                    className={classNames(defaultcss.all, sty.svg__o1YGj)}
                    role={"img"}
                  />

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"links"}
                    data-plasmic-override={overrides.links}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.links)}
                  >
                    <div
                      data-plasmic-name={"heroSectionsNavLink"}
                      data-plasmic-override={overrides.heroSectionsNavLink}
                      className={classNames(
                        defaultcss.all,
                        sty.heroSectionsNavLink
                      )}
                    >
                      <div
                        data-plasmic-name={"text"}
                        data-plasmic-override={overrides.text}
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text
                        )}
                      >
                        {"Product"}
                      </div>
                    </div>

                    <div
                      data-plasmic-name={"heroSectionsNavLink2"}
                      data-plasmic-override={overrides.heroSectionsNavLink2}
                      className={classNames(
                        defaultcss.all,
                        sty.heroSectionsNavLink2
                      )}
                    >
                      <div
                        data-plasmic-name={"text2"}
                        data-plasmic-override={overrides.text2}
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text2
                        )}
                      >
                        {"Features"}
                      </div>
                    </div>

                    <div
                      data-plasmic-name={"heroSectionsNavLink3"}
                      data-plasmic-override={overrides.heroSectionsNavLink3}
                      className={classNames(
                        defaultcss.all,
                        sty.heroSectionsNavLink3
                      )}
                    >
                      <div
                        data-plasmic-name={"text3"}
                        data-plasmic-override={overrides.text3}
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text3
                        )}
                      >
                        {"Marketplace"}
                      </div>
                    </div>

                    <div
                      data-plasmic-name={"heroSectionsNavLink4"}
                      data-plasmic-override={overrides.heroSectionsNavLink4}
                      className={classNames(
                        defaultcss.all,
                        sty.heroSectionsNavLink4
                      )}
                    >
                      <div
                        data-plasmic-name={"text4"}
                        data-plasmic-override={overrides.text4}
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text4
                        )}
                      >
                        {"About Us"}
                      </div>
                    </div>
                  </p.Stack>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  data-plasmic-name={"trailingContent"}
                  data-plasmic-override={overrides.trailingContent}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.trailingContent)}
                >
                  <div
                    data-plasmic-name={"heroSectionsNavLink5"}
                    data-plasmic-override={overrides.heroSectionsNavLink5}
                    className={classNames(
                      defaultcss.all,
                      sty.heroSectionsNavLink5
                    )}
                  >
                    <div
                      data-plasmic-name={"text5"}
                      data-plasmic-override={overrides.text5}
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text5
                      )}
                    >
                      {"Log in"}
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"heroSectionsNavButtonLink"}
                    data-plasmic-override={overrides.heroSectionsNavButtonLink}
                    className={classNames(
                      defaultcss.all,
                      sty.heroSectionsNavButtonLink
                    )}
                  >
                    <div
                      data-plasmic-name={"text6"}
                      data-plasmic-override={overrides.text6}
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.text6
                      )}
                    >
                      {"Start free trial"}
                    </div>
                  </div>
                </p.Stack>
              </p.Stack>
            </div>
          </div>

          <div
            data-plasmic-name={"main"}
            data-plasmic-override={overrides.main}
            className={classNames(defaultcss.all, sty.main)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"container2"}
              data-plasmic-override={overrides.container2}
              hasGap={true}
              className={classNames(defaultcss.all, sty.container2)}
            >
              <p.Stack
                as={"div"}
                data-plasmic-name={"content2"}
                data-plasmic-override={overrides.content2}
                hasGap={true}
                className={classNames(defaultcss.all, sty.content2)}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"calloutAndText"}
                  data-plasmic-override={overrides.calloutAndText}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.calloutAndText)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"callout"}
                    data-plasmic-override={overrides.callout}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.callout)}
                  >
                    <div
                      data-plasmic-name={"badge"}
                      data-plasmic-override={overrides.badge}
                      className={classNames(defaultcss.all, sty.badge)}
                    >
                      <div
                        data-plasmic-name={"text7"}
                        data-plasmic-override={overrides.text7}
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text7
                        )}
                      >
                        {"We’re hiring"}
                      </div>
                    </div>

                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"textLink"}
                      data-plasmic-override={overrides.textLink}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.textLink)}
                    >
                      <div
                        data-plasmic-name={"text8"}
                        data-plasmic-override={overrides.text8}
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text8
                        )}
                      >
                        {"Visit our careers page"}
                      </div>

                      <ChevronRightIcon
                        className={classNames(defaultcss.all, sty.svg__u0Ejx)}
                        role={"img"}
                      />
                    </p.Stack>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"text9"}
                    data-plasmic-override={overrides.text9}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.text9)}
                  >
                    <div
                      data-plasmic-name={"heading"}
                      data-plasmic-override={overrides.heading}
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.heading
                      )}
                    >
                      {"A better way to manage "}
                    </div>

                    <div
                      data-plasmic-name={"heading2"}
                      data-plasmic-override={overrides.heading2}
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.heading2
                      )}
                    >
                      {"electronic waste"}
                    </div>

                    <div
                      data-plasmic-name={"supportingText"}
                      data-plasmic-override={overrides.supportingText}
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.supportingText
                      )}
                    >
                      {
                        "Electronic waste is the world's fastest growing waste stream. Improper disposal of these items contributes to climate change. Chemicals are released when electronic waste is burned or landfilled."
                      }
                    </div>

                    <div
                      data-plasmic-name={"supportingText2"}
                      data-plasmic-override={overrides.supportingText2}
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.supportingText2
                      )}
                    >
                      {" Be part of the solution."}
                    </div>
                  </p.Stack>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  data-plasmic-name={"trailingContent2"}
                  data-plasmic-override={overrides.trailingContent2}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.trailingContent2)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"form"}
                    data-plasmic-override={overrides.form}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.form)}
                  >
                    <div
                      data-plasmic-name={"heroSectionsTextInput"}
                      data-plasmic-override={overrides.heroSectionsTextInput}
                      className={classNames(
                        defaultcss.all,
                        sty.heroSectionsTextInput
                      )}
                    >
                      <div
                        data-plasmic-name={"placeholder"}
                        data-plasmic-override={overrides.placeholder}
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.placeholder
                        )}
                      >
                        {"Enter your email"}
                      </div>
                    </div>

                    <div
                      data-plasmic-name={"heroSectionsSubmitButton"}
                      data-plasmic-override={overrides.heroSectionsSubmitButton}
                      className={classNames(
                        defaultcss.all,
                        sty.heroSectionsSubmitButton
                      )}
                    >
                      <div
                        data-plasmic-name={"text10"}
                        data-plasmic-override={overrides.text10}
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.text10
                        )}
                      >
                        {"Start free trial"}
                      </div>
                    </div>
                  </p.Stack>

                  <div
                    data-plasmic-name={"helpText"}
                    data-plasmic-override={overrides.helpText}
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.helpText
                    )}
                  >
                    {
                      "Start your free 14-day trial, no credit card necessary. By providing your email, you agree to our terms or service."
                    }
                  </div>
                </p.Stack>
              </p.Stack>

              <div
                data-plasmic-name={"ewasteCartoon"}
                data-plasmic-override={overrides.ewasteCartoon}
                className={classNames(defaultcss.all, sty.ewasteCartoon)}
              />
            </p.Stack>
          </div>
        </div>
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  frame1Header: [
    "frame1Header",
    "header",
    "darkWithIllustrationDesktop",
    "navbar",
    "container",
    "content",
    "leadingContent",
    "links",
    "heroSectionsNavLink",
    "text",
    "heroSectionsNavLink2",
    "text2",
    "heroSectionsNavLink3",
    "text3",
    "heroSectionsNavLink4",
    "text4",
    "trailingContent",
    "heroSectionsNavLink5",
    "text5",
    "heroSectionsNavButtonLink",
    "text6",
    "main",
    "container2",
    "content2",
    "calloutAndText",
    "callout",
    "badge",
    "text7",
    "textLink",
    "text8",
    "text9",
    "heading",
    "heading2",
    "supportingText",
    "supportingText2",
    "trailingContent2",
    "form",
    "heroSectionsTextInput",
    "placeholder",
    "heroSectionsSubmitButton",
    "text10",
    "helpText",
    "ewasteCartoon"
  ],

  header: [
    "header",
    "darkWithIllustrationDesktop",
    "navbar",
    "container",
    "content",
    "leadingContent",
    "links",
    "heroSectionsNavLink",
    "text",
    "heroSectionsNavLink2",
    "text2",
    "heroSectionsNavLink3",
    "text3",
    "heroSectionsNavLink4",
    "text4",
    "trailingContent",
    "heroSectionsNavLink5",
    "text5",
    "heroSectionsNavButtonLink",
    "text6",
    "main",
    "container2",
    "content2",
    "calloutAndText",
    "callout",
    "badge",
    "text7",
    "textLink",
    "text8",
    "text9",
    "heading",
    "heading2",
    "supportingText",
    "supportingText2",
    "trailingContent2",
    "form",
    "heroSectionsTextInput",
    "placeholder",
    "heroSectionsSubmitButton",
    "text10",
    "helpText",
    "ewasteCartoon"
  ],

  darkWithIllustrationDesktop: [
    "darkWithIllustrationDesktop",
    "navbar",
    "container",
    "content",
    "leadingContent",
    "links",
    "heroSectionsNavLink",
    "text",
    "heroSectionsNavLink2",
    "text2",
    "heroSectionsNavLink3",
    "text3",
    "heroSectionsNavLink4",
    "text4",
    "trailingContent",
    "heroSectionsNavLink5",
    "text5",
    "heroSectionsNavButtonLink",
    "text6",
    "main",
    "container2",
    "content2",
    "calloutAndText",
    "callout",
    "badge",
    "text7",
    "textLink",
    "text8",
    "text9",
    "heading",
    "heading2",
    "supportingText",
    "supportingText2",
    "trailingContent2",
    "form",
    "heroSectionsTextInput",
    "placeholder",
    "heroSectionsSubmitButton",
    "text10",
    "helpText",
    "ewasteCartoon"
  ],

  navbar: [
    "navbar",
    "container",
    "content",
    "leadingContent",
    "links",
    "heroSectionsNavLink",
    "text",
    "heroSectionsNavLink2",
    "text2",
    "heroSectionsNavLink3",
    "text3",
    "heroSectionsNavLink4",
    "text4",
    "trailingContent",
    "heroSectionsNavLink5",
    "text5",
    "heroSectionsNavButtonLink",
    "text6"
  ],

  container: [
    "container",
    "content",
    "leadingContent",
    "links",
    "heroSectionsNavLink",
    "text",
    "heroSectionsNavLink2",
    "text2",
    "heroSectionsNavLink3",
    "text3",
    "heroSectionsNavLink4",
    "text4",
    "trailingContent",
    "heroSectionsNavLink5",
    "text5",
    "heroSectionsNavButtonLink",
    "text6"
  ],

  content: [
    "content",
    "leadingContent",
    "links",
    "heroSectionsNavLink",
    "text",
    "heroSectionsNavLink2",
    "text2",
    "heroSectionsNavLink3",
    "text3",
    "heroSectionsNavLink4",
    "text4",
    "trailingContent",
    "heroSectionsNavLink5",
    "text5",
    "heroSectionsNavButtonLink",
    "text6"
  ],

  leadingContent: [
    "leadingContent",
    "links",
    "heroSectionsNavLink",
    "text",
    "heroSectionsNavLink2",
    "text2",
    "heroSectionsNavLink3",
    "text3",
    "heroSectionsNavLink4",
    "text4"
  ],

  links: [
    "links",
    "heroSectionsNavLink",
    "text",
    "heroSectionsNavLink2",
    "text2",
    "heroSectionsNavLink3",
    "text3",
    "heroSectionsNavLink4",
    "text4"
  ],

  heroSectionsNavLink: ["heroSectionsNavLink", "text"],
  text: ["text"],
  heroSectionsNavLink2: ["heroSectionsNavLink2", "text2"],
  text2: ["text2"],
  heroSectionsNavLink3: ["heroSectionsNavLink3", "text3"],
  text3: ["text3"],
  heroSectionsNavLink4: ["heroSectionsNavLink4", "text4"],
  text4: ["text4"],
  trailingContent: [
    "trailingContent",
    "heroSectionsNavLink5",
    "text5",
    "heroSectionsNavButtonLink",
    "text6"
  ],

  heroSectionsNavLink5: ["heroSectionsNavLink5", "text5"],
  text5: ["text5"],
  heroSectionsNavButtonLink: ["heroSectionsNavButtonLink", "text6"],
  text6: ["text6"],
  main: [
    "main",
    "container2",
    "content2",
    "calloutAndText",
    "callout",
    "badge",
    "text7",
    "textLink",
    "text8",
    "text9",
    "heading",
    "heading2",
    "supportingText",
    "supportingText2",
    "trailingContent2",
    "form",
    "heroSectionsTextInput",
    "placeholder",
    "heroSectionsSubmitButton",
    "text10",
    "helpText",
    "ewasteCartoon"
  ],

  container2: [
    "container2",
    "content2",
    "calloutAndText",
    "callout",
    "badge",
    "text7",
    "textLink",
    "text8",
    "text9",
    "heading",
    "heading2",
    "supportingText",
    "supportingText2",
    "trailingContent2",
    "form",
    "heroSectionsTextInput",
    "placeholder",
    "heroSectionsSubmitButton",
    "text10",
    "helpText",
    "ewasteCartoon"
  ],

  content2: [
    "content2",
    "calloutAndText",
    "callout",
    "badge",
    "text7",
    "textLink",
    "text8",
    "text9",
    "heading",
    "heading2",
    "supportingText",
    "supportingText2",
    "trailingContent2",
    "form",
    "heroSectionsTextInput",
    "placeholder",
    "heroSectionsSubmitButton",
    "text10",
    "helpText"
  ],

  calloutAndText: [
    "calloutAndText",
    "callout",
    "badge",
    "text7",
    "textLink",
    "text8",
    "text9",
    "heading",
    "heading2",
    "supportingText",
    "supportingText2"
  ],

  callout: ["callout", "badge", "text7", "textLink", "text8"],
  badge: ["badge", "text7"],
  text7: ["text7"],
  textLink: ["textLink", "text8"],
  text8: ["text8"],
  text9: ["text9", "heading", "heading2", "supportingText", "supportingText2"],
  heading: ["heading"],
  heading2: ["heading2"],
  supportingText: ["supportingText"],
  supportingText2: ["supportingText2"],
  trailingContent2: [
    "trailingContent2",
    "form",
    "heroSectionsTextInput",
    "placeholder",
    "heroSectionsSubmitButton",
    "text10",
    "helpText"
  ],

  form: [
    "form",
    "heroSectionsTextInput",
    "placeholder",
    "heroSectionsSubmitButton",
    "text10"
  ],

  heroSectionsTextInput: ["heroSectionsTextInput", "placeholder"],
  placeholder: ["placeholder"],
  heroSectionsSubmitButton: ["heroSectionsSubmitButton", "text10"],
  text10: ["text10"],
  helpText: ["helpText"],
  ewasteCartoon: ["ewasteCartoon"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHeader__ArgProps,
      internalVariantPropNames: PlasmicHeader__VariantProps
    });

    return PlasmicHeader__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "frame1Header") {
    func.displayName = "PlasmicHeader";
  } else {
    func.displayName = `PlasmicHeader.${nodeName}`;
  }
  return func;
}

export const PlasmicHeader = Object.assign(
  // Top-level PlasmicHeader renders the root element
  makeNodeComponent("frame1Header"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    darkWithIllustrationDesktop: makeNodeComponent(
      "darkWithIllustrationDesktop"
    ),

    navbar: makeNodeComponent("navbar"),
    container: makeNodeComponent("container"),
    content: makeNodeComponent("content"),
    leadingContent: makeNodeComponent("leadingContent"),
    links: makeNodeComponent("links"),
    heroSectionsNavLink: makeNodeComponent("heroSectionsNavLink"),
    text: makeNodeComponent("text"),
    heroSectionsNavLink2: makeNodeComponent("heroSectionsNavLink2"),
    text2: makeNodeComponent("text2"),
    heroSectionsNavLink3: makeNodeComponent("heroSectionsNavLink3"),
    text3: makeNodeComponent("text3"),
    heroSectionsNavLink4: makeNodeComponent("heroSectionsNavLink4"),
    text4: makeNodeComponent("text4"),
    trailingContent: makeNodeComponent("trailingContent"),
    heroSectionsNavLink5: makeNodeComponent("heroSectionsNavLink5"),
    text5: makeNodeComponent("text5"),
    heroSectionsNavButtonLink: makeNodeComponent("heroSectionsNavButtonLink"),
    text6: makeNodeComponent("text6"),
    main: makeNodeComponent("main"),
    container2: makeNodeComponent("container2"),
    content2: makeNodeComponent("content2"),
    calloutAndText: makeNodeComponent("calloutAndText"),
    callout: makeNodeComponent("callout"),
    badge: makeNodeComponent("badge"),
    text7: makeNodeComponent("text7"),
    textLink: makeNodeComponent("textLink"),
    text8: makeNodeComponent("text8"),
    text9: makeNodeComponent("text9"),
    heading: makeNodeComponent("heading"),
    heading2: makeNodeComponent("heading2"),
    supportingText: makeNodeComponent("supportingText"),
    supportingText2: makeNodeComponent("supportingText2"),
    trailingContent2: makeNodeComponent("trailingContent2"),
    form: makeNodeComponent("form"),
    heroSectionsTextInput: makeNodeComponent("heroSectionsTextInput"),
    placeholder: makeNodeComponent("placeholder"),
    heroSectionsSubmitButton: makeNodeComponent("heroSectionsSubmitButton"),
    text10: makeNodeComponent("text10"),
    helpText: makeNodeComponent("helpText"),
    ewasteCartoon: makeNodeComponent("ewasteCartoon"),
    // Metadata about props expected for PlasmicHeader
    internalVariantProps: PlasmicHeader__VariantProps,
    internalArgProps: PlasmicHeader__ArgProps
  }
);

export default PlasmicHeader;
/* prettier-ignore-end */
