// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vT2hQ48dTqvVqB6oYdpEi1
// Component: toDOefuMNH
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import projectcss from "./plasmic_mobicycle_usa.module.css"; // plasmic-import: vT2hQ48dTqvVqB6oYdpEi1/projectcss
import sty from "./PlasmicHeader.module.css"; // plasmic-import: toDOefuMNH/css

export const PlasmicHeader__VariantProps = new Array();

export const PlasmicHeader__ArgProps = new Array();

function PlasmicHeader__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div
        data-plasmic-name={"headerComponent"}
        data-plasmic-override={overrides.headerComponent}
        className={classNames(defaultcss.all, sty.headerComponent)}
      >
        <div
          data-plasmic-name={"rectangle"}
          data-plasmic-override={overrides.rectangle}
          className={classNames(defaultcss.all, sty.rectangle)}
        />

        <div
          data-plasmic-name={"frame"}
          data-plasmic-override={overrides.frame}
          className={classNames(defaultcss.all, sty.frame)}
        >
          <div
            data-plasmic-name={"rectangle2"}
            data-plasmic-override={overrides.rectangle2}
            className={classNames(defaultcss.all, sty.rectangle2)}
          />

          <div
            data-plasmic-name={"frame2"}
            data-plasmic-override={overrides.frame2}
            className={classNames(defaultcss.all, sty.frame2)}
          >
            <div
              data-plasmic-name={"rectangle3"}
              data-plasmic-override={overrides.rectangle3}
              className={classNames(defaultcss.all, sty.rectangle3)}
            />

            <div
              data-plasmic-name={"frame3"}
              data-plasmic-override={overrides.frame3}
              className={classNames(defaultcss.all, sty.frame3)}
            >
              <div
                data-plasmic-name={"rectangle4"}
                data-plasmic-override={overrides.rectangle4}
                className={classNames(defaultcss.all, sty.rectangle4)}
              />

              <div
                data-plasmic-name={"frame4"}
                data-plasmic-override={overrides.frame4}
                className={classNames(defaultcss.all, sty.frame4)}
              >
                <div
                  data-plasmic-name={"rectangle5"}
                  data-plasmic-override={overrides.rectangle5}
                  className={classNames(defaultcss.all, sty.rectangle5)}
                />

                <div
                  data-plasmic-name={"frame5"}
                  data-plasmic-override={overrides.frame5}
                  className={classNames(defaultcss.all, sty.frame5)}
                >
                  <div
                    data-plasmic-name={"rectangle6"}
                    data-plasmic-override={overrides.rectangle6}
                    className={classNames(defaultcss.all, sty.rectangle6)}
                  />

                  <div
                    data-plasmic-name={"frame6"}
                    data-plasmic-override={overrides.frame6}
                    className={classNames(defaultcss.all, sty.frame6)}
                  >
                    <div
                      data-plasmic-name={"rectangle7"}
                      data-plasmic-override={overrides.rectangle7}
                      className={classNames(defaultcss.all, sty.rectangle7)}
                    />

                    <div
                      data-plasmic-name={"frame7"}
                      data-plasmic-override={overrides.frame7}
                      className={classNames(defaultcss.all, sty.frame7)}
                    >
                      <div
                        data-plasmic-name={"rectangle8"}
                        data-plasmic-override={overrides.rectangle8}
                        className={classNames(defaultcss.all, sty.rectangle8)}
                      />

                      <div
                        data-plasmic-name={"rectangle9"}
                        data-plasmic-override={overrides.rectangle9}
                        className={classNames(defaultcss.all, sty.rectangle9)}
                      />
                    </div>
                  </div>
                </div>

                <div
                  data-plasmic-name={"frame8"}
                  data-plasmic-override={overrides.frame8}
                  className={classNames(defaultcss.all, sty.frame8)}
                >
                  <div
                    data-plasmic-name={"rectangle10"}
                    data-plasmic-override={overrides.rectangle10}
                    className={classNames(defaultcss.all, sty.rectangle10)}
                  />

                  <div
                    data-plasmic-name={"frame9"}
                    data-plasmic-override={overrides.frame9}
                    className={classNames(defaultcss.all, sty.frame9)}
                  >
                    <div
                      data-plasmic-name={"rectangle11"}
                      data-plasmic-override={overrides.rectangle11}
                      className={classNames(defaultcss.all, sty.rectangle11)}
                    />

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__u5Sfh
                      )}
                    >
                      {"About Us"}
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"frame10"}
                    data-plasmic-override={overrides.frame10}
                    className={classNames(defaultcss.all, sty.frame10)}
                  >
                    <div
                      data-plasmic-name={"rectangle12"}
                      data-plasmic-override={overrides.rectangle12}
                      className={classNames(defaultcss.all, sty.rectangle12)}
                    />
                  </div>

                  <div
                    data-plasmic-name={"frame11"}
                    data-plasmic-override={overrides.frame11}
                    className={classNames(defaultcss.all, sty.frame11)}
                  >
                    <div
                      data-plasmic-name={"rectangle13"}
                      data-plasmic-override={overrides.rectangle13}
                      className={classNames(defaultcss.all, sty.rectangle13)}
                    />

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__azWqi
                      )}
                    >
                      {"Marketplace"}
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"frame12"}
                    data-plasmic-override={overrides.frame12}
                    className={classNames(defaultcss.all, sty.frame12)}
                  >
                    <div
                      data-plasmic-name={"rectangle14"}
                      data-plasmic-override={overrides.rectangle14}
                      className={classNames(defaultcss.all, sty.rectangle14)}
                    />

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__japi7
                      )}
                    >
                      {"Products"}
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div
              data-plasmic-name={"frame13"}
              data-plasmic-override={overrides.frame13}
              className={classNames(defaultcss.all, sty.frame13)}
            >
              <div
                data-plasmic-name={"rectangle15"}
                data-plasmic-override={overrides.rectangle15}
                className={classNames(defaultcss.all, sty.rectangle15)}
              />

              <div
                data-plasmic-name={"frame14"}
                data-plasmic-override={overrides.frame14}
                className={classNames(defaultcss.all, sty.frame14)}
              >
                <div
                  data-plasmic-name={"rectangle16"}
                  data-plasmic-override={overrides.rectangle16}
                  className={classNames(defaultcss.all, sty.rectangle16)}
                />

                <div
                  data-plasmic-name={"frame15"}
                  data-plasmic-override={overrides.frame15}
                  className={classNames(defaultcss.all, sty.frame15)}
                >
                  <div
                    data-plasmic-name={"rectangle17"}
                    data-plasmic-override={overrides.rectangle17}
                    className={classNames(defaultcss.all, sty.rectangle17)}
                  />

                  <div
                    data-plasmic-name={"frame16"}
                    data-plasmic-override={overrides.frame16}
                    className={classNames(defaultcss.all, sty.frame16)}
                  >
                    <div
                      data-plasmic-name={"rectangle18"}
                      data-plasmic-override={overrides.rectangle18}
                      className={classNames(defaultcss.all, sty.rectangle18)}
                    />

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__uLFbO
                      )}
                    >
                      {"for the management of electronic waste"}
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"frame17"}
                    data-plasmic-override={overrides.frame17}
                    className={classNames(defaultcss.all, sty.frame17)}
                  >
                    <div
                      data-plasmic-name={"rectangle19"}
                      data-plasmic-override={overrides.rectangle19}
                      className={classNames(defaultcss.all, sty.rectangle19)}
                    />

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__nokgY
                      )}
                    >
                      {"Innovative solutions"}
                    </div>
                  </div>
                </div>

                <div
                  data-plasmic-name={"frame18"}
                  data-plasmic-override={overrides.frame18}
                  className={classNames(defaultcss.all, sty.frame18)}
                >
                  <div
                    data-plasmic-name={"rectangle20"}
                    data-plasmic-override={overrides.rectangle20}
                    className={classNames(defaultcss.all, sty.rectangle20)}
                  />

                  <div
                    data-plasmic-name={"buttonLiveDemo"}
                    data-plasmic-override={overrides.buttonLiveDemo}
                    className={classNames(defaultcss.all, sty.buttonLiveDemo)}
                  >
                    <div
                      data-plasmic-name={"rectangle21"}
                      data-plasmic-override={overrides.rectangle21}
                      className={classNames(defaultcss.all, sty.rectangle21)}
                    />

                    <div
                      data-plasmic-name={"frame19"}
                      data-plasmic-override={overrides.frame19}
                      className={classNames(defaultcss.all, sty.frame19)}
                    >
                      <div
                        data-plasmic-name={"rectangle22"}
                        data-plasmic-override={overrides.rectangle22}
                        className={classNames(defaultcss.all, sty.rectangle22)}
                      />

                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__fyjHp
                        )}
                      >
                        {"Live demo"}
                      </div>
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"buttonGetStarted"}
                    data-plasmic-override={overrides.buttonGetStarted}
                    className={classNames(defaultcss.all, sty.buttonGetStarted)}
                  >
                    <div
                      data-plasmic-name={"rectangle23"}
                      data-plasmic-override={overrides.rectangle23}
                      className={classNames(defaultcss.all, sty.rectangle23)}
                    />

                    <div
                      data-plasmic-name={"frame20"}
                      data-plasmic-override={overrides.frame20}
                      className={classNames(defaultcss.all, sty.frame20)}
                    >
                      <div
                        data-plasmic-name={"rectangle24"}
                        data-plasmic-override={overrides.rectangle24}
                        className={classNames(defaultcss.all, sty.rectangle24)}
                      />

                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__yPora
                        )}
                      >
                        {"Get started"}
                      </div>
                    </div>
                  </div>
                </div>

                <div
                  data-plasmic-name={"frame21"}
                  data-plasmic-override={overrides.frame21}
                  className={classNames(defaultcss.all, sty.frame21)}
                >
                  <div
                    data-plasmic-name={"rectangle25"}
                    data-plasmic-override={overrides.rectangle25}
                    className={classNames(defaultcss.all, sty.rectangle25)}
                  />

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box___7SJnb
                    )}
                  >
                    {
                      "Electronic waste is the world's fastest growing waste stream. Improper disposal contributes to climate change due to the chemicals released when ewaste is burned. Be part of the solution."
                    }
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div
            data-plasmic-name={"frame22"}
            data-plasmic-override={overrides.frame22}
            className={classNames(defaultcss.all, sty.frame22)}
          >
            <div
              data-plasmic-name={"rectangle26"}
              data-plasmic-override={overrides.rectangle26}
              className={classNames(defaultcss.all, sty.rectangle26)}
            />

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__pvSSo
              )}
            >
              {"Log in"}
            </div>
          </div>
        </div>

        <div
          data-plasmic-name={"frame23"}
          data-plasmic-override={overrides.frame23}
          className={classNames(defaultcss.all, sty.frame23)}
        >
          <div
            data-plasmic-name={"rectangle27"}
            data-plasmic-override={overrides.rectangle27}
            className={classNames(defaultcss.all, sty.rectangle27)}
          />

          <div
            data-plasmic-name={"rectangle28"}
            data-plasmic-override={overrides.rectangle28}
            className={classNames(defaultcss.all, sty.rectangle28)}
          />
        </div>
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "headerComponent",
    "rectangle",
    "frame",
    "rectangle2",
    "frame2",
    "rectangle3",
    "frame3",
    "rectangle4",
    "frame4",
    "rectangle5",
    "frame5",
    "rectangle6",
    "frame6",
    "rectangle7",
    "frame7",
    "rectangle8",
    "rectangle9",
    "frame8",
    "rectangle10",
    "frame9",
    "rectangle11",
    "frame10",
    "rectangle12",
    "frame11",
    "rectangle13",
    "frame12",
    "rectangle14",
    "frame13",
    "rectangle15",
    "frame14",
    "rectangle16",
    "frame15",
    "rectangle17",
    "frame16",
    "rectangle18",
    "frame17",
    "rectangle19",
    "frame18",
    "rectangle20",
    "buttonLiveDemo",
    "rectangle21",
    "frame19",
    "rectangle22",
    "buttonGetStarted",
    "rectangle23",
    "frame20",
    "rectangle24",
    "frame21",
    "rectangle25",
    "frame22",
    "rectangle26",
    "frame23",
    "rectangle27",
    "rectangle28"
  ],

  headerComponent: [
    "headerComponent",
    "rectangle",
    "frame",
    "rectangle2",
    "frame2",
    "rectangle3",
    "frame3",
    "rectangle4",
    "frame4",
    "rectangle5",
    "frame5",
    "rectangle6",
    "frame6",
    "rectangle7",
    "frame7",
    "rectangle8",
    "rectangle9",
    "frame8",
    "rectangle10",
    "frame9",
    "rectangle11",
    "frame10",
    "rectangle12",
    "frame11",
    "rectangle13",
    "frame12",
    "rectangle14",
    "frame13",
    "rectangle15",
    "frame14",
    "rectangle16",
    "frame15",
    "rectangle17",
    "frame16",
    "rectangle18",
    "frame17",
    "rectangle19",
    "frame18",
    "rectangle20",
    "buttonLiveDemo",
    "rectangle21",
    "frame19",
    "rectangle22",
    "buttonGetStarted",
    "rectangle23",
    "frame20",
    "rectangle24",
    "frame21",
    "rectangle25",
    "frame22",
    "rectangle26",
    "frame23",
    "rectangle27",
    "rectangle28"
  ],

  rectangle: ["rectangle"],
  frame: [
    "frame",
    "rectangle2",
    "frame2",
    "rectangle3",
    "frame3",
    "rectangle4",
    "frame4",
    "rectangle5",
    "frame5",
    "rectangle6",
    "frame6",
    "rectangle7",
    "frame7",
    "rectangle8",
    "rectangle9",
    "frame8",
    "rectangle10",
    "frame9",
    "rectangle11",
    "frame10",
    "rectangle12",
    "frame11",
    "rectangle13",
    "frame12",
    "rectangle14",
    "frame13",
    "rectangle15",
    "frame14",
    "rectangle16",
    "frame15",
    "rectangle17",
    "frame16",
    "rectangle18",
    "frame17",
    "rectangle19",
    "frame18",
    "rectangle20",
    "buttonLiveDemo",
    "rectangle21",
    "frame19",
    "rectangle22",
    "buttonGetStarted",
    "rectangle23",
    "frame20",
    "rectangle24",
    "frame21",
    "rectangle25",
    "frame22",
    "rectangle26"
  ],

  rectangle2: ["rectangle2"],
  frame2: [
    "frame2",
    "rectangle3",
    "frame3",
    "rectangle4",
    "frame4",
    "rectangle5",
    "frame5",
    "rectangle6",
    "frame6",
    "rectangle7",
    "frame7",
    "rectangle8",
    "rectangle9",
    "frame8",
    "rectangle10",
    "frame9",
    "rectangle11",
    "frame10",
    "rectangle12",
    "frame11",
    "rectangle13",
    "frame12",
    "rectangle14",
    "frame13",
    "rectangle15",
    "frame14",
    "rectangle16",
    "frame15",
    "rectangle17",
    "frame16",
    "rectangle18",
    "frame17",
    "rectangle19",
    "frame18",
    "rectangle20",
    "buttonLiveDemo",
    "rectangle21",
    "frame19",
    "rectangle22",
    "buttonGetStarted",
    "rectangle23",
    "frame20",
    "rectangle24",
    "frame21",
    "rectangle25"
  ],

  rectangle3: ["rectangle3"],
  frame3: [
    "frame3",
    "rectangle4",
    "frame4",
    "rectangle5",
    "frame5",
    "rectangle6",
    "frame6",
    "rectangle7",
    "frame7",
    "rectangle8",
    "rectangle9",
    "frame8",
    "rectangle10",
    "frame9",
    "rectangle11",
    "frame10",
    "rectangle12",
    "frame11",
    "rectangle13",
    "frame12",
    "rectangle14"
  ],

  rectangle4: ["rectangle4"],
  frame4: [
    "frame4",
    "rectangle5",
    "frame5",
    "rectangle6",
    "frame6",
    "rectangle7",
    "frame7",
    "rectangle8",
    "rectangle9",
    "frame8",
    "rectangle10",
    "frame9",
    "rectangle11",
    "frame10",
    "rectangle12",
    "frame11",
    "rectangle13",
    "frame12",
    "rectangle14"
  ],

  rectangle5: ["rectangle5"],
  frame5: [
    "frame5",
    "rectangle6",
    "frame6",
    "rectangle7",
    "frame7",
    "rectangle8",
    "rectangle9"
  ],

  rectangle6: ["rectangle6"],
  frame6: ["frame6", "rectangle7", "frame7", "rectangle8", "rectangle9"],
  rectangle7: ["rectangle7"],
  frame7: ["frame7", "rectangle8", "rectangle9"],
  rectangle8: ["rectangle8"],
  rectangle9: ["rectangle9"],
  frame8: [
    "frame8",
    "rectangle10",
    "frame9",
    "rectangle11",
    "frame10",
    "rectangle12",
    "frame11",
    "rectangle13",
    "frame12",
    "rectangle14"
  ],

  rectangle10: ["rectangle10"],
  frame9: ["frame9", "rectangle11"],
  rectangle11: ["rectangle11"],
  frame10: ["frame10", "rectangle12"],
  rectangle12: ["rectangle12"],
  frame11: ["frame11", "rectangle13"],
  rectangle13: ["rectangle13"],
  frame12: ["frame12", "rectangle14"],
  rectangle14: ["rectangle14"],
  frame13: [
    "frame13",
    "rectangle15",
    "frame14",
    "rectangle16",
    "frame15",
    "rectangle17",
    "frame16",
    "rectangle18",
    "frame17",
    "rectangle19",
    "frame18",
    "rectangle20",
    "buttonLiveDemo",
    "rectangle21",
    "frame19",
    "rectangle22",
    "buttonGetStarted",
    "rectangle23",
    "frame20",
    "rectangle24",
    "frame21",
    "rectangle25"
  ],

  rectangle15: ["rectangle15"],
  frame14: [
    "frame14",
    "rectangle16",
    "frame15",
    "rectangle17",
    "frame16",
    "rectangle18",
    "frame17",
    "rectangle19",
    "frame18",
    "rectangle20",
    "buttonLiveDemo",
    "rectangle21",
    "frame19",
    "rectangle22",
    "buttonGetStarted",
    "rectangle23",
    "frame20",
    "rectangle24",
    "frame21",
    "rectangle25"
  ],

  rectangle16: ["rectangle16"],
  frame15: [
    "frame15",
    "rectangle17",
    "frame16",
    "rectangle18",
    "frame17",
    "rectangle19"
  ],

  rectangle17: ["rectangle17"],
  frame16: ["frame16", "rectangle18"],
  rectangle18: ["rectangle18"],
  frame17: ["frame17", "rectangle19"],
  rectangle19: ["rectangle19"],
  frame18: [
    "frame18",
    "rectangle20",
    "buttonLiveDemo",
    "rectangle21",
    "frame19",
    "rectangle22",
    "buttonGetStarted",
    "rectangle23",
    "frame20",
    "rectangle24"
  ],

  rectangle20: ["rectangle20"],
  buttonLiveDemo: ["buttonLiveDemo", "rectangle21", "frame19", "rectangle22"],
  rectangle21: ["rectangle21"],
  frame19: ["frame19", "rectangle22"],
  rectangle22: ["rectangle22"],
  buttonGetStarted: [
    "buttonGetStarted",
    "rectangle23",
    "frame20",
    "rectangle24"
  ],

  rectangle23: ["rectangle23"],
  frame20: ["frame20", "rectangle24"],
  rectangle24: ["rectangle24"],
  frame21: ["frame21", "rectangle25"],
  rectangle25: ["rectangle25"],
  frame22: ["frame22", "rectangle26"],
  rectangle26: ["rectangle26"],
  frame23: ["frame23", "rectangle27", "rectangle28"],
  rectangle27: ["rectangle27"],
  rectangle28: ["rectangle28"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHeader__ArgProps,
      internalVariantPropNames: PlasmicHeader__VariantProps
    });

    return PlasmicHeader__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHeader";
  } else {
    func.displayName = `PlasmicHeader.${nodeName}`;
  }
  return func;
}

export const PlasmicHeader = Object.assign(
  // Top-level PlasmicHeader renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    headerComponent: makeNodeComponent("headerComponent"),
    rectangle: makeNodeComponent("rectangle"),
    frame: makeNodeComponent("frame"),
    rectangle2: makeNodeComponent("rectangle2"),
    frame2: makeNodeComponent("frame2"),
    rectangle3: makeNodeComponent("rectangle3"),
    frame3: makeNodeComponent("frame3"),
    rectangle4: makeNodeComponent("rectangle4"),
    frame4: makeNodeComponent("frame4"),
    rectangle5: makeNodeComponent("rectangle5"),
    frame5: makeNodeComponent("frame5"),
    rectangle6: makeNodeComponent("rectangle6"),
    frame6: makeNodeComponent("frame6"),
    rectangle7: makeNodeComponent("rectangle7"),
    frame7: makeNodeComponent("frame7"),
    rectangle8: makeNodeComponent("rectangle8"),
    rectangle9: makeNodeComponent("rectangle9"),
    frame8: makeNodeComponent("frame8"),
    rectangle10: makeNodeComponent("rectangle10"),
    frame9: makeNodeComponent("frame9"),
    rectangle11: makeNodeComponent("rectangle11"),
    frame10: makeNodeComponent("frame10"),
    rectangle12: makeNodeComponent("rectangle12"),
    frame11: makeNodeComponent("frame11"),
    rectangle13: makeNodeComponent("rectangle13"),
    frame12: makeNodeComponent("frame12"),
    rectangle14: makeNodeComponent("rectangle14"),
    frame13: makeNodeComponent("frame13"),
    rectangle15: makeNodeComponent("rectangle15"),
    frame14: makeNodeComponent("frame14"),
    rectangle16: makeNodeComponent("rectangle16"),
    frame15: makeNodeComponent("frame15"),
    rectangle17: makeNodeComponent("rectangle17"),
    frame16: makeNodeComponent("frame16"),
    rectangle18: makeNodeComponent("rectangle18"),
    frame17: makeNodeComponent("frame17"),
    rectangle19: makeNodeComponent("rectangle19"),
    frame18: makeNodeComponent("frame18"),
    rectangle20: makeNodeComponent("rectangle20"),
    buttonLiveDemo: makeNodeComponent("buttonLiveDemo"),
    rectangle21: makeNodeComponent("rectangle21"),
    frame19: makeNodeComponent("frame19"),
    rectangle22: makeNodeComponent("rectangle22"),
    buttonGetStarted: makeNodeComponent("buttonGetStarted"),
    rectangle23: makeNodeComponent("rectangle23"),
    frame20: makeNodeComponent("frame20"),
    rectangle24: makeNodeComponent("rectangle24"),
    frame21: makeNodeComponent("frame21"),
    rectangle25: makeNodeComponent("rectangle25"),
    frame22: makeNodeComponent("frame22"),
    rectangle26: makeNodeComponent("rectangle26"),
    frame23: makeNodeComponent("frame23"),
    rectangle27: makeNodeComponent("rectangle27"),
    rectangle28: makeNodeComponent("rectangle28"),
    // Metadata about props expected for PlasmicHeader
    internalVariantProps: PlasmicHeader__VariantProps,
    internalArgProps: PlasmicHeader__ArgProps
  }
);

export default PlasmicHeader;
/* prettier-ignore-end */
