// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vT2hQ48dTqvVqB6oYdpEi1
// Component: RoF3-Bi9hN
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import projectcss from "./plasmic_mobicycle_usa.module.css"; // plasmic-import: vT2hQ48dTqvVqB6oYdpEi1/projectcss
import sty from "./PlasmicOk.module.css"; // plasmic-import: RoF3-Bi9hN/css
import imageVymGGhV8E from "./images/image.png"; // plasmic-import: vymGGhV8E/picture

export const PlasmicOk__VariantProps = new Array();

export const PlasmicOk__ArgProps = new Array();

function PlasmicOk__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <img
        data-plasmic-name={"img"}
        data-plasmic-override={overrides.img}
        alt={""}
        className={classNames(defaultcss.img, sty.img)}
        role={"img"}
        src={imageVymGGhV8E}
      />
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "img"],
  img: ["img"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicOk__ArgProps,
      internalVariantPropNames: PlasmicOk__VariantProps
    });

    return PlasmicOk__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicOk";
  } else {
    func.displayName = `PlasmicOk.${nodeName}`;
  }
  return func;
}

export const PlasmicOk = Object.assign(
  // Top-level PlasmicOk renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    // Metadata about props expected for PlasmicOk
    internalVariantProps: PlasmicOk__VariantProps,
    internalArgProps: PlasmicOk__ArgProps
  }
);

export default PlasmicOk;
/* prettier-ignore-end */
